DFE-Digital/register-early-career-teachers-public

app/views/schools/register_ect_wizard/_appropriate_body_details.html.erb
app/views/schools/register_ect_wizard/independent_school_appropriate_body.html.erb
app/views/schools/register_ect_wizard/state_school_appropriate_body.html.erb

#838
- correction to copy on Appropriate Body selection pages (independent schools and state-funded schools)

Register ECT: update copy on Appropriate Body selection pages

---

app/views/schools/register_ect_wizard/check_answers.html.erb
app/views/schools/register_ect_wizard/email_address.html.erb
app/views/schools/register_ect_wizard/start_date.html.erb
app/views/schools/register_ect_wizard/working_pattern.html.erb
app/wizards/schools/register_ect_wizard/check_answers_step.rb
app/wizards/schools/register_ect_wizard/email_address_step.rb
app/wizards/schools/register_ect_wizard/programme_type_step.rb
app/wizards/schools/register_ect_wizard/start_date_step.rb
app/wizards/schools/register_ect_wizard/working_pattern_step.rb
spec/features/schools/register_an_ect/edge_cases/appropriate_body_selection/independent_school_selects_istip_spec.rb
spec/features/schools/register_an_ect/edge_cases/appropriate_body_selection/independent_school_selects_teaching_school_hub_spec.rb
spec/features/schools/register_an_ect/happy_path_spec.rb
spec/views/schools/register_ect_wizard/check_answers.html.erb_spec.rb
spec/views/schools/register_ect_wizard/start_date.html.erb_spec.rb

https://github.com/DFE-Digital/register-ects-project-board/issues/984 
- correction to step order in Register ECT flow
- fix backlinks

fix: correction to step order in Register ECT flow (including backlinks)

---

lib/trs/api_client.rb
spec/lib/trs/api_client_spec.rb

This should have been in all along!
Refs DfE-Digital/register-ects-project-board#1111

Pull alerts by default from TRS API

---

.github/CODEOWNERS.yml

Now their approval will be needed before any changes that touch the frontend are made.

Add `ecf2-cpd-prod` team to CODEOWNERS

---

.github/workflows/deploy.yml

We should scan the build image using SNYK
Add SNYK key so the build action runs the scan.
Update the base image
https://trello.com/c/9tIfEgW1
Check 
- build log - https://github.com/DFE-Digital/register-early-career-teachers-public/actions/runs/12893955733/job/35951536330
- review app

Add snyk secret token

---

spec/features/schools/register_an_ect/edge_cases/teacher_prohibited_from_teaching_spec.rb

Follow-up PR to #58, adding the missing feature test.

Add feature spec for blocking schools from registering prohibited ECTs

---

app/views/appropriate_bodies/claim_an_ect/errors/induction_already_completed.md.erb
app/views/appropriate_bodies/claim_an_ect/errors/induction_with_another_appropriate_body.md.erb
app/views/appropriate_bodies/claim_an_ect/errors/no_qts.md.erb
app/views/appropriate_bodies/claim_an_ect/errors/prohibited_from_teaching.md.erb

Review prohibited page as content is kept super generic to follow suit with school reg side. Do we need to be more specific?

Update content on error pages

---

.github/workflows/backup-db.yml
.github/workflows/restore-snapshot-db-from-azure-storage.yml

Minor syntax fixes to the db backup workflows
Also added some comments

[893] - minor syntax fixes to the db backup workflows

---

.github/actions/restore-snapshot-database-from-azure-storage/action.yml
Makefile

- Some `make` automations to use `konduit`
- Add extra step to install `psql` when restoring the snapshot db.

[893] - add some more make automations to use konduit

---

.github/actions/restore-snapshot-database-from-azure-storage/action.yml
.github/workflows/backup-db.yml
.github/workflows/directly-copy-main-db-into-snapshot-db.yml
.github/workflows/restore-app-main-db.yml
Makefile

- fix path to environment global config scripts in workflow to restore the main db of an app.
- add Slack notifications
- fix Makefile referring npq-registration instead of our app

[893] - fix workflow to restore main db

---

app/controllers/application_controller.rb
app/presenters/admin/school_period_presenter.rb
app/services/sessions/user.rb
app/services/sessions/users/dfe_persona.rb
app/services/sessions/users/dfe_user.rb
config/blazer.yml
spec/services/sessions/users/appropriate_body_persona_spec.rb
spec/services/sessions/users/appropriate_body_user_spec.rb
spec/services/sessions/users/dfe_persona_spec.rb
spec/services/sessions/users/dfe_user_spec.rb
spec/services/sessions/users/school_persona_spec.rb
spec/services/sessions/users/school_user_spec.rb

This PR:
- fixes the user instance (User) required by Blazer
- fixes a bug displaying the list of teachers to the dfe_user logged in.
- adjust some settings of Blazer. 
[Issue](https://github.com/DFE-Digital/register-ects-project-board/issues/897)

[897] - get blazer ready in production 2

---

app/views/appropriate_bodies/teachers/extensions/new.html.erb

| <img width="627" alt="Screenshot 2025-01-31 at 10 29 01" src="https://github.com/user-attachments/assets/39def32a-3ea3-4fb2-87f1-2dae9938e99a" /> | <img width="646" alt="Screenshot 2025-01-31 at 10 28 26" src="https://github.com/user-attachments/assets/0e3bc80e-6cda-4e45-bf91-592e880a5e09" /> |

Update extensions content so its factually correct

---

app/controllers/appropriate_bodies/teachers_controller.rb
app/views/appropriate_bodies/teachers/index.html.erb
config/initializers/pagy.rb
spec/requests/appropriate_bodies/teachers/index_spec.rb

- **Add pagination to AB teacher index**
- **Add pagination config**

Add pagination to AB teacher index

---

app/views/otp_mailer/otp_code_email.text.erb
config/environments/test.rb

Fix the url to the opt sign in page in the emails containing the otp code when user logs in

[1159] - fix the url to the opt sign in page in the emails containing the otp code when user logs in

---

documentation/site/content/product/roadmap/later.md
documentation/site/content/product/roadmap/now.md

I can never get bullets right in Markdown.
Particularly because they look right in code editor previews and then don't in prod.
It makes me sad.

Fix roadmap

---

app/views/appropriate_bodies/claim_an_ect/register_ect/show.html.erb

| <img width="653" alt="Screenshot 2025-02-11 at 15 41 52" src="https://github.com/user-attachments/assets/c20952be-ca53-4631-8f79-4ff1ebd72635" /> | <img width="665" alt="Screenshot 2025-02-11 at 15 45 20" src="https://github.com/user-attachments/assets/134e8fcb-4538-49e5-b50c-24fb037119da" /> |
Bug ticket: https://github.com/DFE-Digital/register-ects-project-board/issues/1223

Added ECT name to body text

---

.github/workflows/reseed-staging-db.yml

Reseed workflow file had a bad indent in it which caused an error in the YAML parsing.

fix yaml problem

---

.github/workflows/reseed-staging-db.yml

Fix issue where we should specify the cluster credentials for `staging` not `development`

Fix staging reseed workflow

---

lib/appropriate_bodies/importers/importer.rb

We'll essentially be using this to seed the database. CSV needs to be in the following format:
```csv
name,email
Peter Yates,peter.yates@education.gov.uk
```

Add admin importer to the AB importer script

---

db/migrate/20250214124432_remove_unqiue_index_from_appropriate_body_name.rb
db/schema.rb
lib/appropriate_bodies/importers/induction_period_importer.rb
lib/appropriate_bodies/importers/teacher_importer.rb
spec/lib/appropriate_bodies/importers/induction_period_importer_spec.rb

Previosuly we were importing all teachers which had open induction periods but we want to include ones who are 'paused' too, so now select bring in all teachers who are in progress and any induction periods they
have.
Some will have no valid induction period so just the Teacher record will be created.

Import all records with status 'InProgress'

---

app/controllers/appropriate_bodies/teachers_controller.rb
app/helpers/appropriate_body_helper.rb
app/views/appropriate_bodies/teachers/index.html.erb
spec/helpers/appropriate_body_helper_spec.rb
spec/requests/appropriate_bodies/teachers/index_spec.rb

Add a count of claimed inductions to the AB landing page

Add claimed inductions count

---

app/services/appropriate_bodies/claim_an_ect/register_ect.rb
app/services/teachers/manage.rb
spec/services/teachers/full_name_parser_spec.rb
spec/services/teachers/induction_period_spec.rb
spec/services/teachers/induction_spec.rb
spec/services/teachers/induction_status_spec.rb
spec/services/teachers/manage_spec.rb
spec/services/teachers/name_spec.rb
spec/services/teachers/terms_completed_spec.rb

Introduce a new service responsible for making changes to a `Teacher` and recording events when changes are made.

Refactor ECT update services

---

app/views/appropriate_bodies/landing/show.md.erb
spec/features/visiting_the_service_spec.rb

Reverts DFE-Digital/register-early-career-teachers-public#220

Revert "Change landing page content to holding page for go live"

---

app/components/navigation/primary_navigation_component.rb
app/controllers/schools/ects_controller.rb
app/controllers/schools/home_controller.rb
app/controllers/schools/mentors_controller.rb
app/helpers/mentor_helper.rb
app/services/schools/home.rb
app/views/schools/ects/index.html.erb
app/views/schools/mentors/index.html.erb
config/routes.rb
db/seeds.rb
spec/services/schools/home_spec.rb

Add a new tab for a School user's home page listing mentors

Add school user home page mentors tab

---

app/helpers/admin_helper.rb
app/helpers/teacher_helper.rb
app/views/admin/appropriate_bodies/current_ects/index.html.erb
app/views/admin/schools/show.html.erb
app/views/admin/teachers/index.html.erb
app/views/admin/teachers/show.html.erb
app/views/appropriate_bodies/teachers/extensions/edit.html.erb
app/views/appropriate_bodies/teachers/extensions/index.html.erb
app/views/appropriate_bodies/teachers/extensions/new.html.erb
app/views/appropriate_bodies/teachers/initial_teacher_training_records/index.html.erb
app/views/appropriate_bodies/teachers/record_failed_outcome/new.html.erb
app/views/appropriate_bodies/teachers/record_failed_outcome/show.html.erb
app/views/appropriate_bodies/teachers/record_passed_outcome/new.html.erb
app/views/appropriate_bodies/teachers/record_passed_outcome/show.html.erb
app/views/appropriate_bodies/teachers/release_ect/new.html.erb
app/views/appropriate_bodies/teachers/release_ect/show.html.erb
app/views/appropriate_bodies/teachers/show.html.erb
app/views/migration/teacher_failures/index.html.erb
app/views/migration/teachers/index.html.erb
app/views/schools/ects/show.html.erb
app/views/schools/mentorships/new.html.erb
spec/helpers/teacher_helper_spec.rb

- teacher full name helper
- teacher TRN helper

Use Teacher helpers in views

---

config/analytics.yml
config/analytics_blocklist.yml

Requested by @consult1815 who wasn't expecting to see these values in BigQuery.

Move ECF1 teacher values to the blocklist

---

app/controllers/application_controller.rb
spec/requests/admin/appropriate_bodies/appropriate_bodies/current_ects/index_spec.rb
spec/requests/admin/appropriate_bodies/index_spec.rb
spec/requests/admin/teachers/index_spec.rb
spec/requests/admin/teachers/show_spec.rb
spec/requests/appropriate_bodies/claim_an_ect/check_ect_spec.rb
spec/requests/appropriate_bodies/claim_an_ect/find_ect_spec.rb
spec/requests/appropriate_bodies/claim_an_ect/register_ect_spec.rb
spec/requests/appropriate_bodies/teachers/extensions/index_spec.rb
spec/requests/appropriate_bodies/teachers/index_spec.rb
spec/requests/appropriate_bodies/teachers/record_failed_outcome_spec.rb
spec/requests/appropriate_bodies/teachers/record_passed_outcome_spec.rb
spec/requests/appropriate_bodies/teachers/release_ect_spec.rb
spec/requests/schools/mentorships_spec.rb

Reverts DFE-Digital/register-early-career-teachers-public#274

Revert "Redirect to root path when not authenticated"

---

.github/ISSUE_TEMPLATE/onboarding-ticket.md

- Updating the slack channels to be more specific
- Removing JIRA from the list as this is no longer required

Update onboarding template

---

.github/workflows/restore-app-main-db.yml

Adds migration to the list of environment targets for the db restore workflow

Add migration as a target for DB restore

---

.github/actions/deploy-environment-to-aks/action.yml
.github/actions/directly-backup-and-restore-snapshot-database/action.yml
.github/actions/restore-snapshot-database-from-azure-storage/action.yml
.github/workflows/backup-db.yml
.github/workflows/delete_review_app.yml
.github/workflows/deploy.yml
.github/workflows/deploy_to_environment.yml
.github/workflows/directly-copy-main-db-into-snapshot-db.yml
.github/workflows/nightly-copy-production_db_into_snapshot_db_and_store_dump.yml
.github/workflows/reseed-staging-db.yml
.github/workflows/restore-app-main-db.yml
.github/workflows/restore-snapshot-db-from-azure-storage.yml
Makefile
config/terraform/application/terraform.tf

Replace long lived azure credentials with OIDC for enhanced security and ease of maintenance as secrets won't expire.
Check workflow runs:
| Workflow   | Test Run  |
|---|---|
| Build Deploy   |  https://github.com/DFE-Digital/register-early-career-teachers-public/actions/runs/13725280979/job/38390239537 |
| Delete review app  | https://github.com/DFE-Digital/register-early-career-teachers-public/actions/runs/13725434998  |
| Backup database to Azure storage  | https://github.com/DFE-Digital/register-early-career-teachers-public/actions/runs/13725753154/job/38391906041 (storage account missing in staging, but authentication works)  |
| Manually deploy an environment  | https://github.com/DFE-Digital/register-early-career-teachers-public/actions/runs/13729510825/job/38403740565  |
| …

[2201] Github actions OIDC

---

db/seeds.rb

testing the deploy to different environments.
Currently the commit-sha don't match in all of them.

rephrase comment

---

app/components/teachers/details/current_induction_period_component.html.erb
app/components/teachers/details/induction_summary_component.html.erb
app/controllers/admin/induction_periods_controller.rb
app/models/concerns/interval.rb
app/models/induction_period.rb
app/models/pending_induction_submission.rb
app/services/admin/create_induction_period.rb
app/services/admin/update_induction_period.rb
app/views/admin/induction_periods/new.html.erb
app/views/layouts/shared/_main_preamble.html.erb
config/routes.rb
spec/features/appropriate_bodies/claim_an_ect_spec.rb
spec/models/concerns/interval_spec.rb
spec/requests/admin/induction_periods_spec.rb
spec/requests/appropriate_bodies/teachers/record_failed_outcome_spec.rb
spec/requests/appropriate_bodies/teachers/record_passed_outcome_spec.rb
spec/requests/appropriate_bodies/teachers/release_ect_spec.rb
spec/services/admin/create_induction_period_spec.rb
spec/services/admin/current_teachers_spec.rb
spec/services/admin/update_induction_period_spec.rb
spec/services/teachers/induction_spec.rb

Admin - Add induction period

---

documentation/service-rules/school-admins.md

I've added a lot of rules here for what we've built so far for schools.
1 bit, on previously used details, isn't built fully yet, but I was on a roll and think it's useful to document for now anyway.
Would really appreciate some reviews of this, to add tech detail and double check I've explained things correctly.
I'd quite like to break this down a bit more too, as they're getting a bit long!

Update service rules for schools

---

app/components/teachers/details/induction_summary_component.html.erb
app/components/teachers/details/induction_summary_component.rb
spec/components/teachers/details/induction_summary_component_spec.rb

Appropriate Body
Admin
Fixes #DFE-Digital/register-ects-project-board#1411

Wrap add induction link in role-based conditional

---

documentation/service-rules/school-admins.md

Update service rules from Emily M's review

---

app/views/layouts/shared/_footer.html.erb
app/views/pages/support.html.erb

Ticket: https://github.com/DFE-Digital/register-ects-project-board/issues/1415
Added link to footer and refined content on support page. Content reviewed by @robthompson16 
| <img width="1046" alt="Screenshot 2025-03-27 at 12 08 46" src="https://github.com/user-attachments/assets/97ea4649-0efd-44bd-8539-6f665dca3e10" /> | <img width="1002" alt="Screenshot 2025-03-27 at 12 08 52" src="https://github.com/user-attachments/assets/8765e024-9d00-4d08-8580-de97d452b8d5" /> |
| <img width="1246" alt="Screenshot 2025-03-27 at 12 08 38" src="https://github.com/user-attachments/assets/3594d178-54c4-48c4-ae95-51b6af723967" /> | <img width="1148" alt="Screenshot …

Added support link to footer and iterated support page

---

documentation/service-rules/ecf1/finance-users.md
documentation/service-rules/ecf1/financial-statements.md
documentation/site/content/index.html

JIRA ticket: https://dfedigital.atlassian.net/browse/CPDLP-4073
* Financial statements service manual write up

[CPDLP-4073] financial statements service manual write up

---

documentation/service-rules/ecf1/lead-provider-api.md
documentation/site/content/stylesheet.scss
documentation/site/layouts/ecf1-service-rules.html

- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-4108
We need a comprehensive section in our service manual detailing how our payment calculators work.
* Add documentation on how payment calculators work.
https://github.com/DFE-Digital/register-early-career-teachers-public/blob/cd0d77caa86b0b4f25eff41b93c3883b9194a5bc/documentation/service-rules/ecf1/lead-provider-api.md

[CPDLP-4071] Add documentation on how payment calculators work

---

.github/workflows/database-restore-ptr.yml

There is a requirement for applications to be DR ready.
This PR add/enhances db related workflows
Database restore point in time workflow - new
Review the following runs
backups available in respective environments in azure
Restore database from point in time to new database server
TBD
[[https://trello.com/c/EDFsxSCM/2231-faltrn-plan-for-dr-test-april-2025](https://trello.com.mcas.ms/c/EDFsxSCM/2231-faltrn-plan-for-dr-test-april-2025?McasTsid=11760&McasCtx=4)](https://trello.com/c/F08hjfxH/2288-ec2-plan-for-dr-test-april-2025)

Add DB PTR workflow

---

app/models/teacher.rb
db/migrate/20250411105110_change_limit_of_trs_induction_status_field.rb
db/schema.rb
spec/models/teacher_spec.rb

RequiredToComplete is 18 characters long.
This will eventually be a database type, so just nudging it up for now.

Allow 18 character TRS induction statuses

---

documentation/service-rules/appropriate-body-users.md
documentation/service-rules/ecf1/appropriate-body-users.md

- Ticket: [CPDLP-4158](https://dfedigital.atlassian.net/browse/CPDLP-4158)
We need to update a few places we mention programme types to the new values.
- Update mentions to FIP/CIP in ABs documentation
Review app

[CPDLP-4158] Update mentions to FIP/CIP in ABs documentation

---

.github/workflows/backup-db.yml
.github/workflows/restore-snapshot-db-from-azure-storage.yml
config/terraform/application/config/sandbox.tfvars.json

There is a requirement for applications to be DR ready.
Adding sandbox env to the DB workflows
Enabling backup storage for database 
Review the workflow runs
https://trello.com/c/elTjxV9c/2289-ec2-dr-test-april-2025

Adding sandbox env to the DB workflows 

---

documentation/site/content/user-needs/school-admins.md

This is a draft page setting up user needs for school admins.
In a separate pull request I'll link to these user needs off the homepage for the service manual.

Create a user needs page for school admins

---

app/controllers/schools/register_mentor_wizard_controller.rb
app/models/event.rb
app/services/events/record.rb
app/services/schools/register_mentor.rb
app/wizards/schools/register_mentor_wizard/check_answers_step.rb
app/wizards/schools/register_mentor_wizard/mentor.rb
app/wizards/schools/register_mentor_wizard/step.rb
app/wizards/schools/register_mentor_wizard/wizard.rb
spec/factories/sessions/school_user_factory.rb
spec/services/events/record_spec.rb
spec/services/schools/register_mentor_spec.rb
spec/wizards/schools/register_mentor_wizard/mentor_spec.rb

Fixes #521 
- **Reformat attr_reader list**
- **Add school_user factory**
- **Add teacher_registered_as_mentor event**
- **Make mentor reg wizard record an event on completion**

Record an event when mentors are registered

---

app/controllers/schools/register_ect_wizard_controller.rb
app/models/event.rb
app/services/events/record.rb
app/services/schools/register_ect.rb
app/wizards/schools/register_ect_wizard/check_answers_step.rb
app/wizards/schools/register_ect_wizard/ect.rb
app/wizards/schools/register_ect_wizard/wizard.rb
spec/services/events/record_spec.rb
spec/services/schools/register_ect_spec.rb
spec/wizards/schools/register_ect_wizard/ect_spec.rb

This follows on from #523 and should be rebased/reviewed once it's merged.
Fixes #526

Record ECT registration event

---

documentation/service-rules/ecf1/lead-provider-api.md
documentation/service-rules/ecf1/participants.md

- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-4162
We need a comprehensive section in our service manual detailing how our participants endpoint journeys work.
* Add participants documentation
Review app

[CPDLP-4162] Add participants endpoint documentation

---

app/models/lead_provider_active_period.rb
app/models/lead_provider_delivery_partnership.rb
app/models/training_period.rb
db/migrate/20250429103001_add_unique_index_to_lead_provider_active_periods.rb
db/migrate/20250429103024_add_unique_index_to_lead_provider_delivery_partnerships.rb
db/migrate/20250429103043_add_unique_index_to_school_partnerships.rb
db/schema.rb
db/seeds.rb
spec/components/schools/summary_card_component_spec.rb
spec/factories/training_period_factory.rb
spec/migration/builders/ect/training_periods_spec.rb
spec/migration/builders/mentor/training_periods_spec.rb
spec/models/lead_provider_active_period_spec.rb
spec/models/lead_provider_delivery_partnership_spec.rb
spec/models/school_partnership_spec.rb
spec/models/training_period_spec.rb
spec/views/schools/ects/show.html.erb_spec.rb

[Jira-4216](https://dfedigital.atlassian.net.mcas.ms/browse/CPDLP-4216)
Adds indexes and uniqueness validations to ensure only single combinations of the various partnership models can be created.
Fixes some duplication and typos in the seeds that were violating the new constraints.

Add uniqueness constraints to partnership models

---

app/presenters/admin/teacher_presenter.rb
app/views/migration/teachers/index.html.erb

Fixes a namespacing issue and prevents viewing non-migrated teacher details in migration view

Fix a couple of issues appearing in migration environment

---

app/jobs/fail_ect_induction_job.rb
app/jobs/pass_ect_induction_job.rb
app/services/teachers/induction_status.rb
spec/jobs/fail_ect_induction_job_spec.rb
spec/jobs/pass_ect_induction_job_spec.rb
spec/services/teachers/induction_status_spec.rb

Reverts DFE-Digital/register-early-career-teachers-public#555

Revert "1510 fix TRS updates and syncs"

---

documentation/site/content/product/roadmap/introduction.md
documentation/site/content/product/roadmap/later.md
documentation/site/content/product/roadmap/next.md
documentation/site/content/product/roadmap/now.md

Here I've:
- tried to explain how the services connect
- updated what we're doing now and next

Update roadmap intro

---

app/components/test_guidance_component.rb
app/views/schools/register_ect_wizard/induction_failed.html.erb
app/wizards/schools/register_ect_wizard/ect.rb
app/wizards/schools/register_ect_wizard/find_ect_step.rb
app/wizards/schools/register_ect_wizard/induction_failed_step.rb
app/wizards/schools/register_ect_wizard/national_insurance_number_step.rb
app/wizards/schools/register_ect_wizard/wizard.rb
config/routes.rb
spec/features/schools/register_an_ect/edge_cases/appropriate_body_selection/independent_school_selects_istip_spec.rb
spec/features/schools/register_an_ect/edge_cases/appropriate_body_selection/independent_school_selects_teaching_school_hub_spec.rb
spec/features/schools/register_an_ect/edge_cases/induction_completed/find_ect_step_spec.rb
spec/features/schools/register_an_ect/edge_cases/induction_completed/national_insurance_number_step_spec.rb
spec/features/schools/register_an_ect/edge_cases/induction_exempt/find_ect_spec.rb
spec/features/schools/register_an_ect/edge_cases/induction_exempt/national_insurance_number_spec.rb
spec/features/schools/register_an_ect/edge_cases/induction_failed/find_ect_spec.rb
spec/features/schools/register_an_ect/edge_cases/induction_failed/find_ect_step_spec.rb
spec/features/schools/register_an_ect/edge_cases/induction_failed/national_insurance_number_spec.rb
spec/features/schools/register_an_ect/edge_cases/induction_failed/national_insurance_number_step_spec.rb
spec/support/shared_contexts/fake_trs_api_client.rb
spec/views/schools/register_ect_wizard/induction_failed.html.erb_spec.rb
spec/wizards/schools/register_ect_wizard/ect_spec.rb
spec/wizards/schools/register_ect_wizard/find_ect_step_spec.rb
spec/wizards/schools/register_ect_wizard/national_insurance_number_step_spec.rb

[Issue](https://github.com/DFE-Digital/register-ects-project-board/issues/1392)
Video:
https://github.com/user-attachments/assets/defff024-f466-46c2-a0c1-d8645c60d28c

1392 - Block ECTs from being registered for training if they have failed induction

---

app/views/schools/register_ect_wizard/_start_date.html.erb
spec/views/schools/register_ect_wizard/shared_examples/start_date_view.rb

#1634 update page title/heading

---

app/helpers/batch_helper.rb
app/jobs/process_batch_action_job.rb
app/models/concerns/batch_rows.rb
app/views/appropriate_bodies/process_batch/actions/show.html.erb
spec/forms/appropriate_bodies/process_batch_form_spec.rb
spec/models/concerns/batch_rows_spec.rb

A bug has been introduced into bulk upload whilst defending against an edge case
Prevent Data objects from raising ArgumentError now that we compact asymmetric CSV data
Upload an action or claim template CSV containing blank cells

Pre-bug-party snags

---

documentation/service-rules/ecf1/lead-provider-api.md
documentation/service-rules/ecf1/transfers.md

Ticket: https://dfedigital.atlassian.net/browse/CPDLP-4250
* Service manual for transfers

[CPDLP-4250] Service manual for transfers

---

db/seeds.rb

Ticket: https://github.com/DFE-Digital/register-ects-project-board/issues/1639
* Updated lead provider names with 5 pretty unique names that are hard to recognise.
* Added 2021 for Ambitious and Better practice network.

[1639] Updated lead provider names, 5 providers only, included 2021 cohort

---

app/helpers/ect_helper.rb
app/views/schools/register_ect_wizard/not_found.html.erb
app/views/schools/register_ect_wizard/trn_not_found.html.erb
spec/views/schools/register_ect_wizard/not_found.html.erb_spec.rb
spec/views/schools/register_ect_wizard/trn_not_found.html.erb_spec.rb

When I was reviewing Lorenzo's PR, I found some other bad links.
This is a copy of Claire's PR to be able to deploy the review app that was failing in hers.

Update the incorrect link to Check a teacher's recordFix check a teacher link

---

.github/actions/refresh-migration-database/action.yml
.github/workflows/refresh_migration_database.yml

We want to be able to restore the production database to our migration environment for both the data migration and parity check testing.

Add migration DB restore workflow

---

.github/actions/refresh-migration-database/action.yml
Makefile

Minor fixes to the migration DB refresh action for issues found during testing it. Also fixes bugs in the konduit Makefile commands.

Fix migration db refresh action

---

app/assets/stylesheets/swagger-ui.scss
app/assets/stylesheets/swagger.scss
app/views/layouts/api_docs.html.erb
package.json
public/api/docs/v3/swagger.yaml
spec/requests/api/docs/v3/statements_spec.rb
spec/support/shared_contexts/api_doc_request_auth.rb
spec/swagger_helper.rb
spec/swagger_schemas/attributes/id.rb
spec/swagger_schemas/filters/pagination.rb
spec/swagger_schemas/filters/statements.rb
spec/swagger_schemas/models/statement.rb
spec/swagger_schemas/responses/not_found.rb
spec/swagger_schemas/responses/statement.rb
spec/swagger_schemas/responses/statements.rb
spec/swagger_schemas/responses/unauthorised.rb

Ticket: https://github.com/DFE-Digital/register-ects-project-board/issues/1690
Branches off: https://github.com/DFE-Digital/register-early-career-teachers-public/pull/684
* API auth doc spec
* `/api/v3/statements` endpoint doc
* `/api/v3/statements/{id}` endpoint doc
* Doc url: https://cpd-ec2-review-703-web.test.teacherservices.cloud/api/docs/v3

[1690] Add statements documentation

---

app/views/schools/register_ect_wizard/registered_before.html.erb

Nothing much to see here, just fixing indentation

Fix indentation in registered before template

---

app/components/navigation/primary_navigation_component.rb
app/views/layouts/api_guidance.html.erb
spec/components/navigation/primary_navigation_component_spec.rb

This option was added into the Design System in version 5.11.0
| ----- | ----- |
| ![Screenshot From 2025-06-27 17-14-38](https://github.com/user-attachments/assets/b08d010a-bd41-4ede-953e-a11a0d702481) |![Screenshot From 2025-06-27 17-14-42](https://github.com/user-attachments/assets/e755a8ff-974b-46d3-a2a2-72d1f6d60380) |

Invert phase banner colour on the API guidance

---

spec/features/appropriate_bodies/process_batch_combo_spec.rb

Event order is not always consistent for background jobs
Loosen spec requirements

Fix flaky spec

---

app/controllers/admin/finance/adjustments_controller.rb
app/models/event.rb
app/services/events/record.rb
config/analytics_blocklist.yml
db/migrate/20250630105005_add_statement_to_events.rb
db/migrate/20250630105049_add_statement_adjustment_to_events.rb
db/schema.rb
spec/features/admin/finance/adjustments/create_adjustment_spec.rb
spec/features/admin/finance/adjustments/delete_adjustment_spec.rb
spec/features/admin/finance/adjustments/update_adjustment_spec.rb
spec/models/event_spec.rb
spec/services/events/record_spec.rb

Ticket: https://github.com/DFE-Digital/register-ects-project-board/issues/1788
* Added/updated/deleted events for statement adjustments

[1788] added/updated/deleted events for statement adjustments

---

app/components/teachers/details/current_induction_period_component.rb
app/components/teachers/details/past_induction_periods_component.html.erb
app/components/teachers/details/past_induction_periods_component.rb
app/helpers/programme_helper.rb
app/views/admin/induction_periods/confirm_delete.html.erb
app/views/schools/register_ect_wizard/registered_before.html.erb
spec/views/admin/induction_period/confirm_delete.html.erb_spec.rb

In readiness for enabling new programme types in RIAB and deprecating the feature flag.
- Add customisable fallback value to global helper
- Use the helper wherever possible for consistency
- Add missing flag to induction deletion template

Consolidate induction programme type decoration

---

app/controllers/admin/lead_providers_controller.rb
app/views/admin/lead_providers/index.html.erb
app/views/admin/organisations/index.html.erb
config/routes.rb
spec/features/admin/organisations/lead_providers_spec.rb

Ticket: https://github.com/DFE-Digital/register-ects-project-board/issues/1122
* List lead providers page under orgisations section

[1122] Admin console organisations lead providers page

---

config/blazer.yml

Blazer is not as user-friendly as it could be. Improve admin console bulk upload dashboards and queries with: 
- dropdowns
- tooltips
- hyperlinks
Blazer config for `smart_variables`, `smart_columns`, and `linked_columns`
Visit `/admin/blazer/queries/docs?data_source=main` for guidance on available settings.
Create or view a query

Blazer smart config (specifically for bulk feature)

---

db/scripts/remove_failed_pending_induction_submission_batches.rb

13 from initial feature release
Convenience housekeeping script

Add script to delete failed bulk uploads

---

.github/ISSUE_TEMPLATE/onboarding-ticket.md
README.md
documentation/service-rules/appropriate-body-users.md

Our urls have changed, we should update the links.

Update ECF doc URLS

---

spec/models/teacher_spec.rb

Fixes a small linter issue on main

Fix linting issue on main

---

Gemfile.lock
package-lock.json
package.json

Upgrade to playwright 1.54

---

app/views/api/guidance/release_notes.yml

[Ticket #1847 ](https://github.com/DFE-Digital/register-ects-project-board/issues/1847)

Publish schools endpoint added to sandbox release note

---

app/jobs/process_batch_job.rb

Review apps still sometimes struggle with retrying large files
Copy same settings used elsewhere

Clone TRS::RetryableClient values for bulk

---

Gemfile

We started adding factory bot to seeds, however the gems aren't included for staging env
Include factory bot gems for staging
oops

Add FactoryBot to staging to allow replanting seeds

---

.github/workflows/refresh-mermaid-erd.yml
lib/mermaid_erd/generator.rb
lib/tasks/mermaid_erd.rake
spec/lib/mermaid_erd/generator_spec.rb

We want to refresh the mermaid ERD periodically, so that changes to the models are picked up.
- Refresh Mermaid ERD periodically
I tested this by running it under a different workflow, you can see the run [here](https://github.com/DFE-Digital/register-early-career-teachers-public/actions/runs/17152169904) and the corresponding PR it raised [here](https://github.com/DFE-Digital/register-early-career-teachers-public/pull/1206).

Refresh Mermaid ERD periodically

---

Gemfile.lock
package-lock.json
package.json

Upgrade to playwright 1.55

---

documentation/csv-processing.md

Following user testing with admins we need clarification on what status indicators mean.
Update documentation and explain the batch statuses for uploaded CSV files.

CSV upload statuses

---

db/seeds/school_partnerships.rb

I switched this ages ago while refactoring and didn't notice' it'd slipped in!

Fix school name in partnership seed output

---

app/services/appropriate_bodies/process_batch/base.rb
app/services/appropriate_bodies/process_batch/claim.rb
spec/services/appropriate_bodies/process_batch/claim_spec.rb

Follow up to #1367 
Add bulk claim checks for exempt, passed and failed ECTs

Fix AB bulk ECT claims when TRS status is Exempt, Passed or Failed

---

config/routes.rb
config/routes/school.rb
config/routes/schools.rb
spec/routing/wizardable_spec.rb

Closes #1439
Wrap RECT related routes with feature flag constraint

Add constraint around school interface routes

---

db/seeds/lead_provider_delivery_partnerships.rb

Now there are a lot of lead provider delivery partnerships it's difficult to see what's going on from the seed output. This change itemises them by year and lead provider.
|----- | ------ |
| <img width="895" height="612" alt="Screenshot From 2025-10-06 13-06-53" src="https://github.com/user-attachments/assets/a1e7a9d9-5d3d-4ff7-b7e9-16c2cf651cc0" /> | <img width="658" height="629" alt="image" src="https://github.com/user-attachments/assets/fc583a43-03be-4eb4-9857-9f0a3a39dd2c" /> |

Improve LPDP seed output
