DFE-Digital/register-early-career-teachers-public

app/controllers/appropriate_bodies/teachers/record_failed_outcome_controller.rb
app/controllers/appropriate_bodies/teachers/record_passed_outcome_controller.rb
app/controllers/appropriate_bodies/teachers/release_ect_controller.rb
app/services/pending_induction_submissions/build.rb
app/views/appropriate_bodies/teachers/_outcome_form.html.erb
app/views/appropriate_bodies/teachers/record_failed_outcome/new.html.erb
app/views/appropriate_bodies/teachers/record_passed_outcome/new.html.erb
app/views/appropriate_bodies/teachers/release_ect/new.html.erb
spec/requests/appropriate_bodies/teachers/record_failed_outcome_spec.rb
spec/requests/appropriate_bodies/teachers/record_passed_outcome_spec.rb
spec/requests/appropriate_bodies/teachers/release_ect_spec.rb
spec/services/pending_induction_submissions/build_spec.rb

When we're closing an induction period we populate a `PendingInductionSubmission` record and use it to close the `InductionPeriod`. We do this because soon we'll add bulk editing (via CSV uploads/API) and this allows us to do everything in a consistent manner.
We always want to ensure the `finished_on` date is later than the `started_on` date, so this change adds a `PendingInductionSubmissions::Build` class that lets use use the `InductionPeriod` (which will soon be closed) to initalize the `PendingInductionSubmissions,` so we can compare the two dates.
Also add some specs covering this as it bucks the trend a little 🤏🏽

Improve the `finished_on` validation when closing induction periods

---

app/models/teacher.rb
lib/full_text_search/query.rb
spec/lib/full_text_search/query_spec.rb
spec/models/teacher_spec.rb

Now search terms will receive a wildcard suffix that means results will be returned if all of the provided words match a teacher's name fields.
This means we can find John Smith by searching for:
* John Smith
* john smith
* jo sm
* jo
* sm

Make teacher search work on word prefixes

---

app/migration/migrators/mentorship_period.rb

Remove the `id` of the missing ECT from the failure message in order to keep the message more generic so that we can group failure types more easily.

Remove id from migration failure message

---

app/components/teachers/induction_summary_component.rb
app/helpers/appropriate_body_helper.rb
app/models/concerns/interval.rb
app/services/teachers/induction_status.rb
app/views/admin/teachers/index.html.erb
app/views/appropriate_bodies/claim_an_ect/check_ect/edit.html.erb
app/views/appropriate_bodies/teachers/index.html.erb
spec/factories/induction_period_factory.rb
spec/helpers/appropriate_body_helper_spec.rb
spec/models/concerns/interval_spec.rb
spec/services/teachers/induction_status_spec.rb

This change makes the status retrieved from TRS visible in the appropriate body UI.
The statuses on our test records aren't very exciting but here the top record with 'None' is pulled from TRS using the service written in #23.
I made up the colours, feedback on them welcome. The values in the PR map to [these tag variants](https://design-system.service.gov.uk/components/tag/#additional-colours).
Fixes #1026

Show the TRS induction status from teacher record

---

app/views/appropriate_bodies/teachers/index.html.erb
spec/views/appropriate_bodies/teachers/index.html.erb_spec.rb

The reset button was just doing the [default HTML reset behaviour](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/reset) but it's a bit unintuitive. This changes it to a link back to the teachers index page, which is effectively a reset as the GET params are lost.
I also changed the styling from button to link, because that's what it is.
| ----- | ----- |
| ![image](https://github.com/user-attachments/assets/29138ca6-2df9-443e-b8ef-135f5c390071) |![image](https://github.com/user-attachments/assets/eb7e4692-dd03-4c6a-9e5b-befba1bb5361) |

Switch reset button to link

---

app/models/induction_period.rb
spec/models/induction_period_spec.rb

We previously had an extra rule that prevents number_of_terms from being between 0 and 1 because of feedback from within DfE, but we want to relax that because there are circumstances where shorter values need to be recorded.

Allow any value zero or over for number of terms

---

app/components/teachers/past_induction_periods_component.html.erb
app/components/teachers/past_induction_periods_component.rb
app/views/admin/teachers/show.html.erb
spec/views/appropriate_bodies/teachers/show.html.erb_spec.rb

This was added for admins and incorrectly shown on the AB side too. Now it can be configured with the enable_edit argument which defaults to false.
| ----- | ------ |
| ![Screenshot From 2025-01-19 17-03-06](https://github.com/user-attachments/assets/16f00e27-9a68-49f7-a497-ca8a3c5e3d7a) | ![Screenshot From 2025-01-19 17-03-21](https://github.com/user-attachments/assets/12bc57aa-c8d9-44ce-8dc3-0867f27e03d5)

Hide the edit link for AB past induction periods

---

app/models/pending_induction_submission.rb
spec/models/pending_induction_submission_spec.rb

While this is alredy covered by the inclusion check the validation message isn't great when the input is blank.
| ------ | ------ |
| ![Screenshot From 2025-01-19 17-29-39](https://github.com/user-attachments/assets/7e4ceded-d618-4461-9371-b2621a4a5603) | ![Screenshot From 2025-01-19 17-29-50](https://github.com/user-attachments/assets/69db0d1d-437d-4366-aec9-b0f1babdb028) |

Add a presence check to number_of_terms

---

app/views/appropriate_bodies/claim_an_ect/register_ect/show.html.erb
spec/requests/appropriate_bodies/claim_an_ect/register_ect_spec.rb
spec/views/appropriate_bodies/claim_an_ect/register_ect/show.html.erb_spec.rb

Updating and replacing confirmation screen content and also updating grey buttons to links as per 'Success (teacher claimed)' page - heuristic improvements
[#732](https://github.com/DFE-Digital/register-ects-project-board/issues/732)
|<img width="1002" alt="Screenshot 2025-01-16 at 17 15 43" src="https://github.com/user-attachments/assets/63530a73-9419-4053-89d7-a26d965d3234" /> |<img width="684" alt="Screenshot 2025-01-16 at 17 08 04" src="https://github.com/user-attachments/assets/33b68b9e-e11d-43b0-bc81-2b6fbd3ea000" /> |

Replacing placeholder content on confirmation screen

---

app/services/teachers/refresh_trs_attributes.rb
db/migrate/20250115130749_add_last_refreshed_timestamp_to_teachers.rb
db/schema.rb
spec/services/teachers/refresh_trs_attributes_spec.rb

It'll be useful to know when the teacher record was last synced with TRS and we might even use it to ensure we don't leave any records too long between sync.

Add TRS refresh timestamp to teachers table

---

app/views/appropriate_bodies/claim_an_ect/find_ect/new.html.erb

The original target was removed in DFE-Digital/register-early-career-teachers-public#61 and the test guidance box isn't included in the tests so this wasn't picked up.
Fixes DFE-Digital/register-ects-project-board#1156

Remove link to deleted error page

---

.github/workflows/deploy.yml

To prevent issues with testing, fixing data and running migrations I've removed the `migration` environment from the default deploy workflow.
Ideally we should add a separate workflow to deploy to migration in a subsequent PR.

Remove migration from github workflow

---

app/views/appropriate_bodies/teachers/_outcome_form.html.erb
app/views/appropriate_bodies/teachers/extensions/new.html.erb
spec/features/appropriate_bodies/record_failed_outcome_spec.rb
spec/features/appropriate_bodies/record_passed_outcome_spec.rb
spec/requests/appropriate_bodies/teachers/extensions/new_spec.rb

Induction period closure changed on all 3 pages: pass induction, fail induction and release.
|<img width="668" alt="Screenshot 2025-01-17 at 14 18 49" src="https://github.com/user-attachments/assets/8aedb7d5-b2c3-4c54-9221-f84a9ffb596e" /> |<img width="694" alt="Screenshot 2025-01-17 at 16 29 10" src="https://github.com/user-attachments/assets/5104c1f2-36b6-4e51-a420-aa6c8057dd5f" />|
| <img width="652" alt="Screenshot 2025-01-17 at 16 30 24" src="https://github.com/user-attachments/assets/03d9a90e-8e8b-4568-80bd-4de938ff8022" /> |<img width="680" alt="Screenshot 2025-01-17 at 16 29 47" src="https://github.com/user-attachments/assets/dd970f34-63f9-4713-82fd-d5f10ff8f14a" />| …

Updated existing content and added help text decimal places for terms

---

.github/workflows/restore-snapshot-db-from-azure-storage.yml

The valid syntax to call an action from a workflow needs to start by `./.github/...` instead of `.github/...`

[893]: fix syntax on GitHub workflow

---

app/views/schools/register_mentor_wizard/cannot_register_mentor.html.erb
app/wizards/schools/register_mentor_wizard/cannot_register_mentor_step.rb
app/wizards/schools/register_mentor_wizard/find_mentor_step.rb
app/wizards/schools/register_mentor_wizard/wizard.rb
config/routes.rb
spec/features/schools/register_mentor/edge_cases/mentor_prohibited_from_teaching_spec.rb
spec/views/schools/register_mentor_wizard/cannot_register_mentor.html.erb_spec.rb
spec/wizards/schools/register_mentor_wizard/find_mentor_step_spec.rb

Ticket: https://github.com/DFE-Digital/register-ects-project-board/issues/972
This PR prevents mentors who are prohibited from teaching from being registered in the service.
We don't anticipate schools attempting to register mentors who are prohibited from teaching. However, we implemented this functionality as an added safeguard.
Since this involves sensitive safeguarding information, we display a more generic page stating that the mentor cannot be registered.

Restrict the registration of mentors who are prohibited from teaching

---

app/models/concerns/common_induction_period_validation.rb
app/models/concerns/shared_induction_period_validation.rb
app/models/induction_period.rb
app/models/pending_induction_submission.rb
spec/components/teachers/past_induction_periods_component_spec.rb
spec/models/induction_period_spec.rb
spec/models/pending_induction_submission_spec.rb
spec/services/appropriate_bodies/claim_an_ect/register_ect_spec.rb

I chose 1 September 2021 as the cutoff. Seems sensible but happy to change if there's a cause to be creating them before then.

Prevent induction start dates that are too early

---

README.md

We had to do this because we shuffled our repos around.

Update the repo links in the readme

---

app/services/teachers/induction_status.rb
spec/views/appropriate_bodies/claim_an_ect/check_ect/edit.html.erb_spec.rb

Add spec covering the use of the TRS induction status on the check ECT page.
This should really have been included in #53.

Add spec covering pending induction submission status

---

app/services/appropriate_bodies/claim_an_ect/register_ect.rb
app/services/appropriate_bodies/record_outcome.rb
app/services/events/record.rb
app/services/induction_periods/create_induction_period.rb
app/services/teachers/name.rb
spec/services/appropriate_bodies/claim_an_ect/register_ect_spec.rb
spec/services/events/record_spec.rb
spec/services/induction_periods/create_induction_period_spec.rb
spec/services/teachers/extensions/update_extension_spec.rb

This follows on from #62 and attempts to make the functionality cleaner and more robust by:
* introducing `InductionPeriods::CreateInductionPeriod` which is responsible for creating the induction period and, if the creation is successful, logging the event.
* Making `Events::Record` throw immediately when unpersisted objects are given to it
Given these extra steps I've switched the event jobs back to `perform_later`.

Separate service objects for record updating

---

.github/actions/backup-and-restore-snapshot-database/action.yml
.github/workflows/nightly-copy-production_db_into_snapshot_db_and_store_dump.yml
.github/workflows/nightly_copy_production_db_straight_into_snapshot_db.yml
.github/workflows/restore-snapshot-db-from-azure-storage.yml

The `backup-db` workflow stores compressed db dump files in Azure Storage.
Therefore, the restore workflow needs to append `.gz` at the end of the `backup-file` name.
Also, renaming some related workflows for clarity.

[893] - fix backup-file name to restore from Azure Storage

---

.github/workflows/nightly-backup-of-production-db.yml
.github/workflows/nightly-copy-production_db_into_snapshot_db_and_store_dump.yml
.github/workflows/nightly_copy_production_db_straight_into_snapshot_db.yml

Run db workflows on `ubuntu-latest` to prevent issues with different versions when dumping and restoring a database.

[893] - match ubuntu versions for backing up and restoring databases

---

.github/workflows/deploy_migration.yml
.github/workflows/deploy_to_environment.yml

The migration environment is no longer in the normal deploy workflow to prevent issues with deployments being triggered by merges during migration or while fixing/reviewing data.
In addition, the introduction of DfE Analytics will prevent manual deployments to envs as terraform apply in the console now requires gcloud logins and not all developers will have gcloud accounts or access.
This PR adds a workflow that enables deploying to an environment manually (this is virtually identical to a workflow added to ECFv1).

Adding a manual workflow for deploying to an environment

---

.github/actions/restore-snapshot-database-from-azure-storage/action.yml
.github/workflows/backup-db.yml
.github/workflows/nightly-copy-production_db_into_snapshot_db_and_store_dump.yml

- Nightly production db backups will create dump files named `cpdec2_pd_adhoc_day_of_week`. 
This way every week the new backups will be overwriting those from the previous one keeping so only the last 7 days copies in Azure Storage.
- Display full path to the backup file in Azure Storage on Slack notifications.

[893] - keep only the last 7 days of backups in Azure Storage

---

spec/wizards/schools/register_ect/find_ect_step_spec.rb
spec/wizards/schools/register_mentor_wizard/find_mentor_step_spec.rb

This makes it clearer for people unfamiliar with the codebase that create and build are from FactoryBot.

Prefix FactoryBot methods with `FactoryBot`.

---

documentation/site/content/product/objectives.md
documentation/site/content/product/roadmap/introduction.md
documentation/site/content/product/roadmap/later.md
documentation/site/content/product/roadmap/next.md
documentation/site/content/product/roadmap/now.md

In this PR I am trying to:
- Separate our team objectives to a different page, to reduce clutter on our roadmap
- Add what we've done so far in rebuilding the ECF1 services
- Update what we're doing now, next and later

Update the roadmap for our team

---

app/forms/schools/assign_mentor_form.rb
app/models/ect_at_school_period.rb
app/models/mentorship_period.rb
app/services/schools/register_ect.rb
app/services/schools/register_mentor.rb
app/views/schools/mentorships/new.html.erb
app/views/schools/register_mentor_wizard/cannot_mentor_themself.md.erb
app/wizards/schools/register_ect_wizard/ect.rb
app/wizards/schools/register_mentor_wizard/cannot_mentor_themself_step.rb
app/wizards/schools/register_mentor_wizard/find_mentor_step.rb
app/wizards/schools/register_mentor_wizard/wizard.rb
config/routes.rb
spec/features/schools/register_mentor/edge_cases/cannot_mentor_themself_spec.rb
spec/models/mentorship_period_spec.rb
spec/services/schools/assign_mentor_form_spec.rb
spec/services/schools/register_ect_spec.rb
spec/services/schools/register_mentor_spec.rb
spec/views/schools/register_mentor_wizard/already_active_at_school.md.erb_spec.rb
spec/views/schools/register_mentor_wizard/cannot_mentor_themself.md.erb_spec.rb
spec/wizards/schools/register_mentor_wizard/find_mentor_step_spec.rb

[Issue](https://github.com/DFE-Digital/register-ects-project-board/issues/1059)
This story blocks school users from adding an ECT as the ECT's own mentor as this is against the policy intent. This is most likely to happen in error if a user enters the ECT's TRN instead of the mentor's TRN - this new page will block the journey in this case.
This PR:
- adds a new step to display an error page when the user enters the TRN of the ECT to mentor in FindMentorStep.
- allow registering a teacher a second time as a mentor if it was already an ECT or viceverse. Otherwise, raise an exception
- prevents ECTs from auto-assigning themselves as mentors if they are already registered as mentors.
Better review commit by commit.
Video: 
https://github.com/user-attachments/assets/3874d17c-b156-4e3a-a96f-69a …

[1059] - block school user from adding an ect as their own mentor

---

app/controllers/appropriate_bodies/claim_an_ect/check_ect_controller.rb
app/controllers/appropriate_bodies/claim_an_ect/find_ect_controller.rb
app/helpers/induction_helper.rb
app/services/teachers/induction.rb
app/views/appropriate_bodies/claim_an_ect/check_ect/edit.html.erb
app/views/schools/register_ect_wizard/review_ect_details.html.erb
app/views/schools/register_mentor_wizard/review_mentor_details.html.erb
spec/features/appropriate_bodies/claim_an_ect_spec.rb
spec/helpers/induction_helper_spec.rb
spec/services/teachers/induction_spec.rb
spec/views/appropriate_bodies/claim_an_ect/check_ect/edit.html.erb_spec.rb

- replace "Claim induction" CTA when ECT is already claimed by another body
- fix redirect when claiming an already claimed ECT
Try ECT `3002582`

ECT claiming fixes

---

config/blazer.yml
config/terraform/application/application.tf
config/terraform/application/config/production.yml

This PR sets up `BLAZER_DATABASE_URL` for all the environments:
- pointing to the snapshot database in production
- pointing to the main database otherwise

[897] - setup blazer in production

---

app/controllers/health_check_controller.rb
config/routes.rb
spec/requests/health_check_controller_spec.rb

Being able to use the health check to determine the overall state of the app is useful. For example, app won't function without the database, so we should ensure it's working.

Make the health check more informative

---

app/controllers/appropriate_bodies/claim_an_ect/register_ect_controller.rb
app/models/pending_induction_submission.rb
db/migrate/20250131171406_increase_induction_status_limit.rb
db/migrate/20250131171406_remove_induction_status_limit.rb
db/schema.rb
spec/factories/pending_induction_submission_factory.rb
spec/models/pending_induction_submission_spec.rb
spec/requests/appropriate_bodies/claim_an_ect/register_ect_spec.rb
spec/services/appropriate_bodies/claim_an_ect/register_ect_spec.rb

Character limit prevented ECTs with a status of "RequiredToComplete" from being processed.
- ~Increase size of `PendingInductionSubmission` `trs_induction_status` character limit from `16` to `18`.~
- Remove `PendingInductionSubmission` `trs_induction_status` character limit.
- Add validation when registering.

Bugfix: Allow data from TRS API to be persisted

---

app/jobs/fail_ect_induction_job.rb
app/jobs/pass_ect_induction_job.rb
app/services/appropriate_bodies/release_ect.rb
db/migrate/20250205135949_add_delete_at_timestamp_to_pending_induction_submissions.rb
db/schema.rb
spec/features/appropriate_bodies/release_an_ect_spec.rb
spec/jobs/fail_ect_induction_job_spec.rb
spec/jobs/pass_ect_induction_job_spec.rb
spec/services/appropriate_bodies/release_ect_spec.rb

We encounter a few bugs where the Pending Induction Submission is deleted too quickly and we can't see it on the confirmation screen. This change, instead of deleting it, adds a `delete_at` timestamp.
We can add a scheduled job which deletes any pending induction submission records with a `delete_at` in the past. This will follow in a subsequent PR.
- **Add delete_at timestamp to pending induction submission**
- **Schedule pending induction deletion on pass/fail**
- **Schedule pending induction deletion on release**

Schedule future deletions of pending induction submissions 

---

app/helpers/appropriate_body_helper.rb
spec/helpers/appropriate_body_helper_spec.rb

DIY is an internal term, we should use terms the users will understand in the UI. This was brought up earlier this morning in a UR session.

Replace 'Do it yourself' with 'School-based induction programme'

---

Dockerfile
Gemfile
Gemfile.lock
config/environments/production.rb
config/initializers/rack_attack.rb
config/routes.rb
config/terraform/application/application.tf
spec/requests/rate_limiting_spec.rb

Add and configure `rack-attack` to protect against abusive requests.
For this to work in production we need to enable the Redis cache. It's already provisioned and present for the production-like environments.
To test locally you need to enable the cache in dev.
```
bundle exec rails dev:cache
```
Then create a siege file, e.g. in `~/protected-paths`:
```
HOST=http://localhost:3000
$(HOST)/sign-in
$(HOST)/otp-sign-in
```
Now we can run it with `siege ~/protected-paths`. Hopefully things are quickly throttled, like this:

Configure rack attack

---

app/mailers/otp_mailer.rb
app/views/otp_mailer/otp_code_email.text.erb
config/application.rb
spec/mailers/otp_mailer_spec.rb

This fixes DFE-Digital/register-ects-project-board#1205
The cause appears to be Notify not wanting to render links in level one headings.
|------|-------|
|![Screenshot From 2025-02-06 13-13-28](https://github.com/user-attachments/assets/d4562041-955e-4f2d-8cdc-99dccf0b5426)|![Screenshot From 2025-02-06 13-21-50](https://github.com/user-attachments/assets/b3029252-97e1-47f2-bd3f-89724c703a84) |
- **Add spec/mailers/previews to config**
- **Minor rewordings**
- **Take the link out of the header**

Fix weird email rendering issue

---

app/models/induction_period.rb
db/migrate/20250130172854_add_unknown_and_pre_september_2021_induction_programmes.rb
db/schema.rb
lib/appropriate_bodies/importers/induction_period_importer.rb
spec/lib/appropriate_bodies/importers/induction_period_importer_spec.rb
spec/models/induction_period_spec.rb

ECF started in September 2021 so any induction periods that started before then shouldn't have an ECF programme type; they will be assigned `pre_september_2021`.
Any induction period that starts on or after 1 Septmeber 2021 should have an induction type, but some in DQT don't so we're setting them as `unknown`.
Refs #65

Add `unknown` and `pre_september_2021` induction programmes

---

lib/appropriate_bodies/importers/importer.rb
lib/appropriate_bodies/importers/induction_period_importer.rb
spec/lib/appropriate_bodies/importers/induction_period_importer_spec.rb

There should never be a `number_of_terms` present on an ongoing induction period.

Unset `number_of_terms` when induction periods aren't finished

---

app/jobs/begin_ect_induction_job.rb
spec/jobs/begin_ect_induction_job_spec.rb

Rather than delete immediately schedule the deletion for 24 hours in the future. Then it someone presses back in their browser the record will still be visible.

Schedule the deletion of the pending submission

---

app/views/appropriate_bodies/landing/show.md.erb

Make the start button in ab home page link to DfE Sign In page
[Issue](https://github.com/DFE-Digital/register-ects-project-board/issues/1158)
Only testable in [Sandbox](https://sandbox.register-early-career-teachers.education.gov.uk/appropriate-body) or [Production](https://www.register-early-career-teachers.education.gov.uk/appropriate-body)

[1158] - make the start button in ab home page link to DfE Sign In page

---

app/controllers/migration/teachers_controller.rb
app/presenters/admin/teacher_presenter.rb

Fix a bug in the `Migration::TeachersController` which was still expecting the `params[:id]` to be the `trn` and this is no longer the case.

fix id param is not trn

---

config/terraform/application/config/sandbox.yml

This PR updates the terraform config which was introduced by [#158](https://github.com/DFE-Digital/register-early-career-teachers-public/pull/158), to enable the dfe analytics on sandbox.

Enable dfe analytics on sandbox

---

config/environments/production.rb

This should ensure cookies are set with `secure: true`.

Force SSL in prod

---

README.md
config/initializers/dfe_analytics.rb

Manually deploying to migration is failing.
It appears to be related to analytics and the `Migration::` models built for connecting to ECTv1 tables.
DfE Analytics has a config option to exclude models so attempting to see if we can exclude the entire `Migration::` namespace of models to remedy the issue.

Try and fix migration deployment

---

config/terraform/application/gcp_wif.tf

The initial plan was to append events to the existing ECF1 dataset. However, both ECF1 and ECF2 share common table names, which makes it difficult to distinguish the origin of the events between the two services.
This PR updates the Terraform configuration to use a dedicated BigQuery dataset for ECF2, ensuring a clear separation of data between the two services.
Related PRs: #122 and #158

Use a new dataset for DfE Analytics to prevent collisions with ECF1

---

config/terraform/application/gcp_wif.tf

ECF2 requires new tables for populating events into big query.
New table will be created for review apps to which the events would be published.
New tables for staging, sandbox, production environments.

Add ecf2 big query tables

---

.github/workflows/reseed-staging-db.yml

As we have a limited number of test DQT candidate data, we want to be able to reseed the `staging` environment database to enable further/new rounds of testing to take place.
This PR adds a workflow that can be invoked to reseed the DB.

Add a workflow to enable reseed of Staging DB

---

app/views/appropriate_bodies/claim_an_ect/find_ect/new.html.erb

Cleaned up content and removed duplication / extra acronyms 
| <img width="672" alt="Screenshot 2025-02-12 at 11 08 13" src="https://github.com/user-attachments/assets/933294cf-94f1-4b26-bca8-f225cbd8915f" /> | <img width="630" alt="Screenshot 2025-02-12 at 11 08 21" src="https://github.com/user-attachments/assets/a873274f-a4e9-4648-8577-5329e5ec09fd" /> |
Bug ticket: https://github.com/DFE-Digital/register-ects-project-board/issues/1233

Removed duplication on find ect page

---

app/controllers/appropriate_bodies/teachers/extensions_controller.rb
app/controllers/appropriate_bodies/teachers/initial_teacher_training_records_controller.rb
app/controllers/appropriate_bodies/teachers/record_failed_outcome_controller.rb
app/controllers/appropriate_bodies/teachers/record_passed_outcome_controller.rb
app/controllers/appropriate_bodies/teachers/release_ect_controller.rb
app/controllers/appropriate_bodies/teachers_controller.rb
app/services/appropriate_bodies/ects.rb
app/services/teachers/search.rb
app/views/appropriate_bodies/teachers/record_failed_outcome/show.html.erb
app/views/appropriate_bodies/teachers/record_passed_outcome/show.html.erb
app/views/appropriate_bodies/teachers/release_ect/show.html.erb
spec/features/appropriate_bodies/release_an_ect_spec.rb
spec/requests/appropriate_bodies/teachers/record_failed_outcome_spec.rb
spec/requests/appropriate_bodies/teachers/record_passed_outcome_spec.rb
spec/services/appropriate_bodies/ects_spec.rb

Content refined to bring in line with 'claim success page' and changed button to link. 
We agree that design for this could be better, including pass and fail journeys. MVP+1 would be to remove these success pages and show ECT record with relevant notification banner (https://design-system.service.gov.uk/components/notification-banner/) confirming the users action. 
| <img width="790" alt="Screenshot 2025-02-12 at 13 12 50" src="https://github.com/user-attachments/assets/71b84094-0fa8-458a-9fc1-8f5b3896bb37" /> | <img width="697" alt="Screenshot 2025-02-12 at 13 35 54" src="https://github.com/user-attachments/assets/36af61e9-422b-4aa3-937d-13cd9c5757b3" /> |
Bug ticket: …

Refine content on successful release page

---

.github/workflows/reseed-staging-db.yml

Staging reseed workflow fails because it requires an azure login

Add azure login to reseed workflow

---

app/views/appropriate_bodies/teachers/record_failed_outcome/new.html.erb
spec/views/appropriate_bodies/teachers/record_failed_outcome/new.html.erb_spec.rb
spec/views/appropriate_bodies/teachers/record_passed_outcome/new.html.erb_spec.rb

| ------ | ------- |
| ![Screenshot From 2025-02-12 09-52-19](https://github.com/user-attachments/assets/3d7ce1f5-71d8-4781-873f-5c3949b77201) | ![Screenshot From 2025-02-12 09-52-27](https://github.com/user-attachments/assets/a082fc9d-f933-4330-84d8-359de22814f7) |
Also, I added some view specs covering these pages.
- **Make the fail button red**
- **Add view specs for the pass/fail induction pages**

Make the record failing outcome button red

---

app/jobs/fail_ect_induction_job.rb
app/jobs/pass_ect_induction_job.rb
app/services/appropriate_bodies/claim_an_ect/register_ect.rb
app/services/appropriate_bodies/record_outcome.rb
lib/trs/api_client.rb
spec/jobs/fail_ect_induction_job_spec.rb
spec/jobs/pass_ect_induction_job_spec.rb
spec/lib/trs/api_client_spec.rb
spec/services/appropriate_bodies/claim_an_ect/register_ect_spec.rb
spec/services/appropriate_bodies/record_outcome_spec.rb

This PR contains a few small changes, I suggest reviewing commit-by commit.
- **Fix the TRS induction status names**
- **Add start_date param to API client pass/fail**
- **Ensure we send start date when completing inductions**
- **Make the API client take dates instead of strings**

Send start date to TRS when completing inductions

---

db/migrate/20250213115105_allow_null_dfe_sign_in_organisation_ids.rb
db/schema.rb
lib/appropriate_bodies/importers/appropriate_body_importer.rb
lib/appropriate_bodies/importers/importer.rb
lib/appropriate_bodies/importers/teacher_importer.rb
spec/lib/appropriate_bodies/importers/appropriate_body_importer_spec.rb
spec/lib/appropriate_bodies/importers/teacher_importer_spec.rb

This PR adds the following things to the AB data importer:
* it allows  the `dfe_sign_in_organisation_id` to be `null` and only sets it if there's a corresponding value in the mapping table
* it sets the name of the appropriate body to the value from the mapping table if present, otherwise falls back to the DQT value
It also adds specs for the AB importer.

Add DfE Sign-in AB mappings

---

config/terraform/application/application.tf
config/terraform/application/config/review.tfvars.json
config/terraform/application/gcp_wif.tf
config/terraform/application/variables.tf

It is rarely required for review apps and creating many datasets confuses the analytics team
Make it optional using variable `create_bigquery_dataset`
- Create review app from main
- Run terraform plan from branch, but set create_bigquery_dataset to true
- Run the tfmv.sh script to rename the resources
- Set create_bigquery_dataset to false
- The dataset should be deleted
- Stop merges
- rename terraform resources using the tfmv.sh script
- remove the TEMP commit

[2241] Make BQ dataset creation optional

---

.github/workflows/restore-app-main-db.yml
config/global_config/sandbox.sh

- add `sandbox` and `staging` options to the `restore-app-main-db` GitHub workflow
- add missing envar to sandbox global config script.

Add missing environment options to some workflows

---

app/services/appropriate_bodies/claim_an_ect/register_ect.rb
spec/services/appropriate_bodies/claim_an_ect/register_ect_spec.rb

We only want to send updates to TRS when someone starts an induction. We eventually should do this by checking the induction status but we can use the presence of an induction period to indicate whether it's beginnning the induction or not.
Fixes DFE-Digital/register-ects-project-board#1160

Only send begin notification to TRS on first induction period

---

app/views/appropriate_bodies/teachers/_outcome_form.html.erb
app/views/appropriate_bodies/teachers/extensions/new.html.erb

Added suffix text to term labels on both the release page: https://staging.register-early-career-teachers.education.gov.uk/appropriate-body/teachers/311/release/new and the extensions page: https://staging.register-early-career-teachers.education.gov.uk/appropriate-body/teachers/311/extensions/new
| <img width="641" alt="Screenshot 2025-02-12 at 15 49 48" src="https://github.com/user-attachments/assets/da59ba9a-ba7a-4d8c-9dde-ccb126a03e93" /> | <img width="645" alt="Screenshot 2025-02-12 at 15 49 55" src="https://github.com/user-attachments/assets/d16027f3-772d-41bd-ac19-86d145f86845" /> |
| <img width="703" alt="Screenshot 2025-02-12 at 15 51 14" …

FTE terms suffix added to relevant pages

---

app/views/appropriate_bodies/teachers/record_failed_outcome/new.html.erb

Bug ticket: https://github.com/DFE-Digital/register-ects-project-board/issues/1234 
Added ECT appeal content and left existing content as it is because we have the red CTA now which indicates a fail quite obviously. 
Content does need cleaning up / refining post MVP but for now, it's good to go.
| <img width="605" alt="Screenshot 2025-02-14 at 15 11 07" src="https://github.com/user-attachments/assets/00de984f-06fe-46e3-9948-968c92489092" /> | <img width="634" alt="Screenshot 2025-02-14 at 15 07 25" src="https://github.com/user-attachments/assets/4eeac822-81dd-4ac2-9692-f2527530229b" /> |

Add appeal content to fail induction page

---

lib/appropriate_bodies/importers/importer.rb
lib/appropriate_bodies/importers/teacher_importer.rb
spec/lib/appropriate_bodies/importers/teacher_importer_spec.rb

Previously we brought in all teachers who had statuses of `InProgress` and `RequiredToComplete`, which left us with lots of teacher records that had no induction periods.
Now we're more selective and bring in teachers who have a status of `InProress` and `RequiredToComplete` and have at least one induction period. As a result the import is significantly faster.

Improve teacher filtering on import

---

app/views/appropriate_bodies/teachers/_outcome_form.html.erb

Added content to explain the max terms a user is able to enter. Added this content to all the relevant pages that have this behaviour / logic. Content added on:
- Release 
- Pass 
- Fail
New help text reviewed by Rob T.
Bug ticket: https://github.com/DFE-Digital/register-ects-project-board/issues/1228 
| <img width="710" alt="Screenshot 2025-02-13 at 13 25 27" src="https://github.com/user-attachments/assets/f27f59f5-ae40-4031-956f-7a60856dbce0" /> | <img width="624" alt="Screenshot 2025-02-14 at 17 25 51" src="https://github.com/user-attachments/assets/a01ffc50-eeab-458a-b435-78e0be57205a" /> |
| <img width="651" alt="Screenshot 2025-02-13 at 13 28 …

Added content to explain max number of terms

---

config/initializers/filter_parameter_logging.rb

@shaheislamdfe [pointed out we weren't filtering email addresses out of logs](https://kibana-uk1.logit.io/s/b2876053-0173-44fc-983d-99567292ba31/app/discover#/doc/filebeat-*/filebeat-2025.02.06?id=RsOc25QBZOOvpK1CzFoX).
This change adds fields containing personal information to Rails' list of `filter_parameters`.
- **Reformat and sort the filter param list**
- **Filter params that might contain personal data**
Checking the logs with this enabled we can see:
```
Parameters: {"authenticity_token"=>"[FILTERED]", "email"=>"[FILTERED]", "name"=>"[FILTERED]", "appropriate_body_id"=>"5", "school_urn"=>"", "dfe_staff"=>"false", "commit"=>"[FILTERED]", "provider"=>"persona"}
Started GET "/appropriate-body/teachers?q=[FILTERED]" for 127.0.0.1 at 2025-02-07 15:12:20 +0000
Processing by …
```

Add personal info to filtered params config

---

config/analytics.yml
config/analytics_blocklist.yml

Blocklist unused teacher fields that are not used by analytics and should not be included in BigQuery event tables:
- corrected_name
- trs_first_name
- trs_last_name

Add trs name fields and corrected_name to the blocklist

---

app/views/appropriate_bodies/landing/show.md.erb
spec/features/visiting_the_service_spec.rb

Landing page content changed for the interim to be a holding page. We will revert back to the landing page content once holding page is no longer needed.
Content consistent with the email that went out to ABs and has the same date and time: https://educationgovuk.sharepoint.com/:w:/r/sites/TeacherServices/Shared%20Documents/Teacher%20Continuing%20Professional%20Development/Teacher%20CPD%20Team/Register%20early%20career%20teachers/Record%20Inductions%20as%20an%20Appropriate%20Body/Content%20design/Service%20downtime%20content.docx?d=w4aae0068b02f4cbda84c1edf7b0cbc90&csf=1&web=1&e=Ldr9n8
Design and content pattern following: https://design-system.service.gov.uk/patterns/service-unavailable-pages/ 
| <img width="1349" …

Change landing page content to holding page for go live

---

app/helpers/application_helper.rb
app/helpers/environment_helper.rb
spec/helpers/application_helper_spec.rb
spec/helpers/environment_helper_spec.rb

We're missing this in production and there should be something there, or we may as well drop the banner altogether.

Add fallback phase banner text

---

config/terraform/application/config/production.yml

This PR updates the terraform config, introduced by https://github.com/DFE-Digital/register-early-career-teachers-public/pull/158, to enable the dfe analytics on production.

Enable dfe analytics on production

---

app/services/sessions/users/builder.rb
spec/services/sessions/users/builder_spec.rb

This should provide us a little more clarity on what's going on when the org isn't found and we can't fall back to personas.
Currently in Sentry the error doesn't make it clear who is failing to log in.

Add a custom error when DfE Sign-in org not found

---

spec/requests/appropriate_bodies/teachers/extensions/edit_spec.rb
spec/requests/appropriate_bodies/teachers/extensions/index_spec.rb
spec/requests/appropriate_bodies/teachers/extensions/new_spec.rb
spec/requests/appropriate_bodies/teachers/index_spec.rb
spec/services/admin/current_teachers_spec.rb
spec/validators/appropriate_body_validator_spec.rb
spec/validators/date_of_birth_validator_spec.rb
spec/validators/ect_start_date_validator_spec.rb
spec/validators/programme_type_validator_spec.rb
spec/validators/working_pattern_validator_spec.rb
spec/wizards/schools/register_ect/ect_spec.rb
spec/wizards/schools/register_ect/email_address_step_spec.rb
spec/wizards/schools/register_ect/independent_school_appropriate_body_step_spec.rb
spec/wizards/schools/register_ect/programme_type_step_spec.rb
spec/wizards/schools/register_ect/start_date_step_spec.rb
spec/wizards/schools/register_ect/state_school_appropriate_body_step_spec.rb
spec/wizards/schools/register_ect/working_pattern_step_spec.rb

The rails_helper is configured in the .rspec to be loaded by default.

Remove redundant require from spec files

---

db/migrate/20250220114713_remove_mentor_school_start_constraint.rb
db/schema.rb

Currently the is a constraint in the DB that prevents a mentor being at multiple schools with the same `started_on` date.
We want to allow mentoring at multiple schools and sometimes they are added on the same day to multiple schools (e.g. a multi-academy trust updating all their schools).

Remove mentor at school start date constraint to allow mentoring at multiple schools

---

db/seeds.rb

We have this test organisation set up in the DfE Sign-in dev environment so it makes sense to just hardcode it in the seeds rather than manually going and finding it every time.

Add a working DfE Sign-in ID to the seeds

---

app/helpers/teacher_helper.rb
app/views/appropriate_bodies/claim_an_ect/find_ect/new.html.erb
app/views/appropriate_bodies/claim_an_ect/register_ect/edit.html.erb
app/views/appropriate_bodies/teachers/_outcome_form.html.erb
spec/helpers/teacher_helper_spec.rb

Added hint text for dates so users know what format they should  be in. 
Ticket: https://github.com/DFE-Digital/register-ects-project-board/issues/1250 
NOT added to extensions as there is no date field in that journey. 
Added to:
- Release
- Pass/Fail
- Claim
| <img width="707" alt="Screenshot 2025-02-19 at 14 59 06" src="https://github.com/user-attachments/assets/b94ab42b-4368-4b2c-b96b-e6020203d84f" /> | <img width="743" alt="Screenshot 2025-02-19 at 14 58 57" src="https://github.com/user-attachments/assets/b1231fb6-728b-4e9b-80b0-8294d63566dc" /> |
| <img width="676" alt="Screenshot 2025-02-19 at 14 58 45" …

Add hint text for dates on relevant pages

---

app/wizards/schools/register_ect_wizard/state_school_appropriate_body_step.rb
spec/views/schools/register_ect_wizard/state_school_appropriate_body.html.erb_spec.rb
spec/wizards/schools/register_ect/state_school_appropriate_body_step_spec.rb

The previous page of State School Appropriate Body page was changed to the Working Pattern page in the Register ECT journey, but the change was never reflected in the code.
This PR sets the previous step to the correct step.

Fix navigation in the register ect journey

---

app/components/migration/induction_record_component.rb
app/components/migration/mentorship_period_component.rb
app/components/migration/school_period_component.rb
app/components/migration/teacher_migration_failure_component.rb
app/components/migration/training_period_component.rb
app/controllers/migration/teachers_controller.rb
app/migration/builders/ect/school_periods.rb
app/migration/builders/ect/training_periods.rb
app/migration/builders/mentor/school_periods.rb
app/migration/builders/mentor/training_periods.rb
app/migration/builders/mentorship_periods.rb
app/migration/builders/teacher.rb
app/migration/mentorship_period_extractor.rb
app/migration/migrators/mentorship_period.rb
app/migration/migrators/teacher.rb
app/presenters/migration/induction_record_presenter.rb
app/presenters/migration/migration_failure_presenter.rb
app/presenters/migration/school_period_presenter.rb
config/analytics.yml
config/analytics_blocklist.yml
db/migrate/20250219165051_rename_appropriate_body_legacy_id_to_dqt_id.rb
db/migrate/20250221132033_rename_legacy_migration_fields.rb
db/schema.rb
spec/migration/builders/ect/school_periods_spec.rb
spec/migration/builders/ect/training_periods_spec.rb
spec/migration/builders/mentor/school_periods_spec.rb
spec/migration/builders/mentor/training_periods_spec.rb
spec/migration/builders/mentorship_periods_spec.rb
spec/migration/builders/teacher_spec.rb

The name `legacy_id` isn't much help, `dqt_id` at least hints at the source of the value.
Refs DFE-Digital/register-ects-project-board#1199
**Note**, this follows on from #240 and should be rebased once it's merged. No point in updating all the importer scripts with this change only to delete them.
This now includes renaming `legacy_` fields used for ECF migration into much nicer things

Rename`legacy_id` type fields more appropriately

---

.gitignore
app/models/induction_period.rb
spec/models/induction_period_spec.rb
spec/requests/admin/induction_periods_spec.rb
spec/services/admin/update_induction_period_service_spec.rb

This is done in a way that can be rolled out to other period types.

Change induction period overlap validation to target the offending date

---

app/controllers/admin/induction_periods_controller.rb
app/models/event.rb
app/services/admin/update_induction_period_service.rb
app/services/events/describe_modifications.rb
app/services/events/record.rb
config/analytics_blocklist.yml
db/migrate/20250221120813_add_modifications_field_to_events.rb
db/schema.rb
spec/requests/admin/induction_periods_spec.rb
spec/services/admin/update_induction_period_service_spec.rb
spec/services/events/describe_modifications_spec.rb
spec/services/events/record_spec.rb

When admins make changes to induction periods we want to record an event that tells us what changed, and later, why.
We will do this by triggering an `Events::Record` method from the service class that does the update.
We'll have lots of this style of event in the future so we spent some time ensuring it's easy, and we don't end up with too much _change describing_ code littered around.
* there is a new column, `modifications`, on the `events` table, it's a `varchar[]` column and is intended to contain a human readable list of changes we can display in a `<ul>`
* there's a new class called `Events::DescribeModifications` which takes a set of changes from `ActiveRecord#changes` and convers them to the human readable list. We're using the word modifications instead of changes because …

Record events for admin induction period updates

---

app/controllers/admin/appropriate_bodies/current_ects_controller.rb
app/controllers/admin/appropriate_bodies_controller.rb
app/views/admin/appropriate_bodies/current_ects/index.html.erb
app/views/admin/appropriate_bodies/index.html.erb
app/views/admin/appropriate_bodies/show.html.erb
config/routes.rb
spec/requests/admin/appropriate_bodies/appropriate_bodies/current_ects/index_spec.rb
spec/views/admin/appropriate_bodies/current_ects/index.html.erb_spec.rb
spec/views/admin/appropriate_bodies/index.html.erb_spec.rb
spec/views/admin/appropriate_bodies/show.html.erb_spec.rb

This adds some basic admin functionality to the admin pages that allow information about appropriate bodies to be viewed and their ECTs listed/searched.
| Appropriate body page | ECTs at AB page |
| -------------- | ----------------- |
| ![Screenshot From 2025-02-24 18-49-23](https://github.com/user-attachments/assets/260115cd-5106-432c-8dbf-9f18123829af) | ![Screenshot From 2025-02-24 18-49-33](https://github.com/user-attachments/assets/cd6cd8b0-9eb5-40ac-b205-6a881d28d142) |
The AB ECT list page is more or less the same as the main ECT list page but searching is limited to ECTs who are currently with the ECT.

Admin interface for viewing appropriate bodies

---

app/migration/training_period_extractor.rb

This was previously a PR but had infra issues with creating the review app so has needed to be recreated
When trying to migrate InductionRecords into RECT, we attempt to build `TrainingPeriod` records to reflect the time spent with a LP/DP for FIP training. There are some FIP `InductionProgramme` records in ECF that do not have a `Partnership` associated with them and this means we cannot build a `TrainingPeriod` as there is no LP/DP for these.  This PR skips recording a FIP training period in these cases instead of (eventually) raising an error because it cannot find a `NULL` provider.

[Migration] Skip FIP induction programmes without partnerships

---

.github/workflows/restore-app-main-db.yml

To prevent accidentally restore the main database in the production environment of the service:
- Remove `production` from the list of restorable databases in the `environment` input field.
- Also only allow non production databases to be restored by the the restoring job

remove production from the list of restorable databases and also from the restoring job

---

app/models/concerns/interval.rb
app/services/admin/update_induction_period_service.rb
spec/models/concerns/interval_spec.rb

We'll undoubtably need to filter all kinds of periods by whether they started before, on or after a certain date. This change adds some common scopes that means we can do it consistently without having to use snippets of SQL.
- **Add started before/on or after scopes to interval**
- **Use started_before scope instead of where clause**

Add before and after scopes to interval

---

app/controllers/application_controller.rb
spec/requests/admin/appropriate_bodies/appropriate_bodies/current_ects/index_spec.rb
spec/requests/admin/appropriate_bodies/index_spec.rb
spec/requests/admin/teachers/index_spec.rb
spec/requests/admin/teachers/show_spec.rb
spec/requests/appropriate_bodies/claim_an_ect/check_ect_spec.rb
spec/requests/appropriate_bodies/claim_an_ect/find_ect_spec.rb
spec/requests/appropriate_bodies/claim_an_ect/register_ect_spec.rb
spec/requests/appropriate_bodies/teachers/extensions/index_spec.rb
spec/requests/appropriate_bodies/teachers/index_spec.rb
spec/requests/appropriate_bodies/teachers/record_failed_outcome_spec.rb
spec/requests/appropriate_bodies/teachers/record_passed_outcome_spec.rb
spec/requests/appropriate_bodies/teachers/release_ect_spec.rb
spec/requests/schools/mentorships_spec.rb

We've had people ending up on the sign-in page in production and it's only really intended for use by admins. We should redirect to the homepage instead when someone's not authenticated.
Refs #1308

Redirect to root path when not authenticated

---

app/services/schools/teacher_email.rb
app/views/schools/register_ect_wizard/cant_use_email.html.erb
app/wizards/schools/register_ect_wizard/cant_use_email_step.rb
app/wizards/schools/register_ect_wizard/ect.rb
app/wizards/schools/register_ect_wizard/email_address_step.rb
app/wizards/schools/register_ect_wizard/wizard.rb
app/wizards/schools/register_mentor_wizard/mentor.rb
config/routes.rb
spec/factories/ect_at_school_period_factory.rb
spec/factories/mentor_at_school_period_factory.rb
spec/features/schools/register_an_ect/edge_cases/cant_use_email_spec.rb
spec/services/schools/teacher_email_spec.rb
spec/views/schools/register_ect_wizard/cant_use_email.html.erb_spec.rb
spec/wizards/schools/register_ect_wizard/ect_spec.rb
spec/wizards/schools/register_mentor_wizard/mentor_spec.rb

This PR introduces a new step in the Register an ECT journey to prevent the use of email addresses already associated with an ongoing school period.
Ticket: https://github.com/DFE-Digital/register-ects-project-board/issues/964
- Adds the `Schools::TeacherEmail` service class to check if a given email is used by any other teacher in their ongoing school period
- Introduces a new page that informs schools when an email is unavailable and prompts them to provide a different one
- Refactors the equivalent Mentor decorator to re-use the `Schools::TeacherEmail`

Ensure only available email addresses can be used when registering an ECT

---

app/helpers/appropriate_body_helper.rb
app/views/appropriate_bodies/claim_an_ect/check_ect/edit.html.erb
spec/helpers/appropriate_body_helper_spec.rb
spec/requests/appropriate_bodies/claim_an_ect/check_ect_spec.rb

Ticket: https://github.com/DFE-Digital/register-ects-project-board/issues/1225
Added some context and next steps for when non prohibited alerts are present. Kept content and link similar to prohibited alert page (to use CTR service). 
Interim solution design / content wise as it's a pretty rare occurrence so we should revisit later down the line
Can't show before screenshot as no TRNs with alerts in staging environment but it just says 'Yes' with no other context currently.
Screenshots: 
| After |
| ------ |
| <img width="685" alt="Screenshot 2025-02-24 at 16 10 30" src="https://github.com/user-attachments/assets/ba309f20-de29-414f-872a-d72accab102e" /> |

created helper and added content for non prohibited alerts

---

app/models/concerns/interval.rb
app/models/ect_at_school_period.rb
app/models/induction_period.rb
app/models/mentor_at_school_period.rb
app/models/mentorship_period.rb
app/models/training_period.rb
app/services/admin/update_induction_period_service.rb
spec/models/concerns/interval_spec.rb
spec/models/ect_at_school_period_spec.rb
spec/models/induction_period_spec.rb
spec/models/mentor_at_school_period_spec.rb
spec/models/mentorship_period_spec.rb
spec/models/training_period_spec.rb

- replace scopes of type `siblings_of(instance)` with instance methods `instance#siblings`
- throw `NotImplementedError` exception on `Interval#siblings` method to indicate that models including the `Interval` module should overide this method.
- define a set of instance methods in `Interval` to deal with predecessors and successors of a given `*Period` instance
- override `siblings` in `ECTAtSchoolPeriod` to define it based on the `ect_at_school_periods` of the `teacher` of an instance.
- same for `InductionPeriod` model.
- for `MentorAtSchoolPeriod` mode, overide it based on the `teacher` and `school` of the given instance.
- `MentorshipPeriod`: leave `#mentee_siblings` for now. Maybe in the future we should renamed it to just `siblings` and benefit from the new methods defined on …

Extend Interval to cope with predecessors and successors siblings of an interval

---

app/views/schools/register_ect_wizard/start.html.erb
spec/views/schools/register_ect_wizard/start.html.erb_spec.rb

We use smart quotes on gov.uk services.
https://smartquotesforsmartpeople.com/
---------|--------
|<img width="710" alt="image" src="https://github.com/user-attachments/assets/983f99a3-0be4-4d8c-a771-da10086b55c9" />|<img width="739" alt="image" src="https://github.com/user-attachments/assets/aaae1081-35d0-4523-9ded-c3cc8b5a53e2" />|

[xxx] Use smart quotes on the `What you’ll need to register a new ECT` page

---

app/views/schools/register_ect_wizard/check_answers.html.erb
spec/features/schools/register_an_ect/happy_path_spec.rb

Ticket: https://github.com/DFE-Digital/register-ects-project-board/issues/1302
This PR removes the date of birth from the check your answers page for ECT registration by schools

Remove the DoB from the check answers page

---

Gemfile
Gemfile.lock
app/helpers/application_helper.rb
spec/helpers/application_helper_spec.rb

**Add helper method to convert 'dumb' quotes to 'smart' quotes using RubyPants.**
This PR introduces a helper method: `smart_quotes`, that automatically converts straight quotes (`"`, `'`) into smart quotes (`“`, `”`, `‘`, `’`). This will help to maintain a consistent gov.uk typography style across the app.
---
- Added the RubyPants gem
- Added `smart_quotes` helper method.
- Configured `RubyPants` with custom smart quote options.
---
You can wrap text output with the helper to apply smart quotes automatically:
```erb
<p><%= smart_quotes("He said 'hello'") %></p>
```
outputs: 
https://github.com/DFE-Digital/register-ects-project-board/issues/1329

[1329] Add helper method to render smart quotes using RubyPants

---

app/views/schools/register_ect_wizard/_review_ect_details.html.erb
app/wizards/schools/register_ect_wizard/ect.rb
spec/wizards/schools/register_ect_wizard/ect_spec.rb

Ticket: https://github.com/DFE-Digital/register-ects-project-board/issues/1303
This PR fixes a bug on the ECT's review details page where the TRS full name gets replaced when the name is corrected.

Display the ECT’s TRS full name by default on the details review page

---

config/analytics.yml
config/analytics_blocklist.yml

The analytics team requested to blocklist the `mentor_completion_date` and `mentor_completion_reason` fields.

Stop streaming the mentor completion date and completion reason fields to BigQuery

---

app/services/teachers/induction_status.rb
spec/services/teachers/induction_status_spec.rb

We ran into a bug in staging where teachers with no induction periods are marked as 'Induction paused' because they have no ongoing induction periods either.
This shouldn't happen in production yet but we can still fix the bug by only overriding the TRS induction status when we have both a teacher record and it has induction periods.

Make statuses dependant on induction period presence

---

app/views/appropriate_bodies/teachers/extensions/edit.html.erb
app/views/appropriate_bodies/teachers/extensions/new.html.erb
documentation/service-rules/appropriate-body-users.md

This change adds service rules for the extensions.
It also changes the button text on the forms for 'Add extension' and' Update extension' because 'Continue' is misleading.
@PriyaNahar2 I think we need to do a bit of surgery on the edit page next week, I'm not sure it makes sense at the moment!

Add service rules for induction extensions

---

app/components/schools/teacher_profile_summary_list_component.html.erb
app/components/schools/teacher_profile_summary_list_component.rb
app/views/schools/ects/show.html.erb
spec/components/schools/teacher_profile_summary_list_component_spec.rb

This PR introduces the `TeacherProfileSummaryListComponent` component, which renders a summary list with key details about an ECT (Early Career Teacher). The component displays the following information:
- Teacher's name
- Email address
- Mentor information
- School start date
- Working pattern
- Add `TeacherProfileSummaryListComponent` to render a summary list of ECT details.
- Include helper methods to format teacher name, mentor details and school start date.
- Add tests for the component to ensure it renders the correct details.

Refactor `ECT details` summary list into `ViewComponent`

---

.github/actions/directly-backup-and-restore-snapshot-database/action.yml
.github/actions/restore-snapshot-database-from-azure-storage/action.yml
.github/workflows/backup-db.yml
.github/workflows/nightly-copy-production_db_into_snapshot_db_and_store_dump.yml
.github/workflows/restore-app-main-db.yml

- Fix the workflow that restores the main database of an environment to be able to do it from any file stored in any other environment's Azure storage account.
- Add failure notification to the workflow that dumps an environment's main database and stores it in their Azure Storage account.

restore from any dump in any azure storage account

---

app/components/migration/induction_record_component.html.erb
app/components/migration/participant_profile_component.html.erb

Add `created_at` timestamp to view of `ParticipantProfile` and `InductionRecord` in the migration UI.

[Migration] Add created_at to view components

---

app/wizards/schools/register_ect_wizard/ect.rb
documentation/service-rules/appropriate-body-users.md
spec/services/teachers/refresh_trs_attributes_spec.rb
spec/support/shared_contexts/fake_trs_api_client.rb

'Pass' was used in DQT but since moving to TRS the status is 'Passed'.
https://preprod.teacher-qualifications-api.education.gov.uk/swagger/index.html#model-InductionStatus

Replace induction status 'Pass' with 'Passed'

---

app/controllers/admin/teachers/timeline_controller.rb
app/services/events/list.rb
spec/services/events/list_spec.rb

Follows on from #297
This PR adds `Events::List`, a class responsible for pulling the events from the database for a given record (and eventually) filtering and ordering them.

Improve event retrieval

---

documentation/service-rules/lead-provider-users.md

Add API management guidelines and breaking changes explanations to service manual for lead providers:
- Explain what a breaking change is vs non breaking change
- Release management of changes to the API
- Versioning extract and how we should follow best practices going forward
This was done by @shahadRah

Update lead provider service manual

---

app/services/appropriate_bodies/release_ect.rb
app/services/events/record.rb
db/scripts/set_induction_period_event_happened_at_times_so_they_are_teacher_orientated.rb
spec/services/appropriate_bodies/release_ect_spec.rb
spec/services/events/record_spec.rb
spec/services/induction_periods/create_induction_period_spec.rb

I implemented this wrong first time around because I was thinking of the event from the point of view of when it was recorded, not from the actual final timeline.
On the timeline we want the date the person started or finished an induction period, not the date the AB informed us.
We'll need to fix some records in prod but that is thankfully straightfoward.

Fix the induction event happened_at values

---

spec/models/induction_period_spec.rb

The main branch is failing, this PR fixes that by abiding by the RSpec/ImplicitSubject rule.
Don't use implicit subject. (https://www.rubydoc.info/gems/rubocop-rspec/RuboCop/Cop/RSpec/ImplicitSubject)

Appease rubocop on main branch

---

spec/services/admin/create_induction_period_spec.rb

Prevent a spec from attempting to make a real connection to a (non existent) TRS API.
Somehow #266 was automerged despite having a failing test, something I'll investigate.

Stop attempted real connection to TRS API

---

app/components/schools/summary_card_component.rb
app/views/schools/ects/show.html.erb
spec/components/schools/summary_card_component_spec.rb
spec/factories/ect_at_school_period_factory.rb
spec/views/schools/ects/show.html.erb_spec.rb

Following on from #313, we are refactoring the `govuk_summary_cards` used in `ects/show` into a ViewComponent.
This change improves reusability and enables us to write targeted tests for the component, ensuring consistent rendering across different contexts.
I considered making this more generic so it could be used for other summary cards, with helper methods in the view. However, that would introduce a lot of logic into the view, making it harder to maintain. Since this component is scoped to schools, I felt it was reasonable to tie it more closely to this domain.
Would a more generic summary card component be worth considering, or does keeping it scoped to schools feel like the right level of abstraction for now?
- **Not `provider_led`**  
- **`provider_led`**  
---
- **With …

Refactor `govuk_summary_cards` used in `ects/show` into a ViewComponent

---

config/global_config/sandbox.sh

This was missing and made the aks-ssh make command fail as it was incorrectly building this name `"cpd-ec2--web"` instead of `"cpd-ec2-sandbox-web"`.
Fixes #270

Add `ENVIRONMENT` var to sandbox's config

---

.github/workflows/deploy.yml

We are having some statefile issues with sandbox so want to bypass it while we're fixing them.

Temporarily remove sandbox from deployment flow

---

app/components/teachers/details_component.rb
app/views/admin/teachers/show.html.erb
spec/components/teachers/details_component_spec.rb

- Added support for passing an `is_admin` flag to `DetailsComponent`.
- Updated `InductionSummaryComponent` to handle `is_admin`, ensuring correct rendering.
The **extensions section** in the teacher view incorrectly displays **Add/View** links in the **admin console**. These links should only appear in the **Appropriate Body (AB) interface**, but the shared component wasn’t handling this correctly.
This update ensures that the `DetailsComponent` behaves correctly across different views.
[Sentry errors](https://dfe-teacher-services.sentry.io/issues/6223619216/?environment=production&project=4508369974788096&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&sort=date&stream_index=0)

Add support for rendering `DetailsComponent` for admins

---

app/views/layouts/shared/_head.html.erb
app/views/layouts/shared/_js_enabled.html.erb
config/initializers/content_security_policy.rb

Before/after
```diff
HTTP/2.0 200 OK
cache-control: max-age=0, private, must-revalidate
content-length: 0
+ content-security-policy: default-src 'self' https:; font-src 'self' https: data:; img-src 'self' https: data:; object-src 'none'; script-src 'self' https: 'nonce-'; style-src 'self' https: 'nonce-'
content-type: text/html; charset=utf-8
link: </assets/application-a2ba66bf.css>; rel=preload; as=style; nopush
referrer-policy: strict-origin-when-cross-origin
strict-transport-security: max-age=31536000; includeSubDomains
vary: Accept
x-content-type-options: nosniff
x-frame-options: SAMEORIGIN
x-permitted-cross-domain-policies: none
x-xss-protection: 0
```
Note, [viewing in dev tools won't show nonces](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/nonce#accessing_non …

Enable content security policy (CSP)

---

.rubocop.yml
.rubocop_todo.yml
spec/components/appropriate_bodies/claim_ect_actions_component_spec.rb
spec/requests/appropriate_bodies/claim_an_ect/check_ect_spec.rb
spec/requests/appropriate_bodies/claim_an_ect/register_ect_spec.rb
spec/services/appropriate_bodies/claim_an_ect/register_ect_spec.rb
spec/services/teachers/extensions/create_extension_spec.rb
spec/services/teachers/extensions/update_extension_spec.rb
spec/views/schools/register_mentor_wizard/check_answers.html.erb_spec.rb
spec/wizards/schools/register_ect_wizard/find_ect_step_spec.rb
spec/wizards/schools/register_mentor_wizard/find_mentor_step_spec.rb
spec/wizards/schools/register_mentor_wizard/national_insurance_number_step_spec.rb

We're gradually working through the rubocop violations listed in `.rubocop_todo.yml`.
Here we clean up the following violations: 
- **Abide by** [Capybara/CurrentPathExpectation](https://www.rubydoc.info/gems/rubocop-rspec/1.19.0/RuboCop/Cop/RSpec/Capybara/CurrentPathExpectation) (this change excludes the feature tests from this cop because we use Playwright (not Capybara) for those. Leaving it enabled elsewhere in case Capybara matchers are used in other test types.)
- **Exclude feature tests from** [Capybara/VisibilityMatcher](https://www.rubydoc.info/gems/rubocop-capybara/RuboCop/Cop/Capybara/VisibilityMatcher) (this change helps to avoid ambiguity by being more explicit and using the preferred `:visible` symbol instead of `true`.)
I've addressed each cop in single commit, so it would …

Fix Capybara Rubocop Violations

---

app/helpers/content_helper.rb
app/views/schools/register_ect_wizard/_email_address.html.erb
spec/helpers/content_helper_spec.rb

Update the email field label to discourage use of generic email addresses (e.g. admin@example.com).
- Extracted a new helper method `generic_email_label` in `ContentHelper` to render the label text.
- Included a `govuk_link_to` link styled with `govuk-link--no-visited-state`.
- Updated the content on the form page to use this new helper.
- Use smart quotes
| <img width="618" alt="image" src="https://github.com/user-attachments/assets/ed1da5e4-abd8-4bc4-bc89-bb45b8e11132" /> | <img width="699" alt="image" src="https://github.com/user-attachments/assets/133064ad-a037-4b65-9829-2630a727f6e5" /> |
This change affects the **Register ECT** email page in the following places:
- **When registering an ECT** …

Update email label to discourage use of generic addresses

---

config/blazer.yml

Blazer was being blocked by the CSP changes made in #374 and I didn't test it at the time. Blazer comes with an `override_csp` setting that lets Blazer use its own settings without affecting the rest of the app.
I've tested this locally and it works, we don't have Blazer enabled in review apps so it won't be testable there.
In prod when looking at the browser console there was lots of this kind of error:
```
Content-Security-Policy: The page’s settings blocked an inline style (style-src-elem) 
```

Override Blazer's CSP settings

---

documentation/site/content/product/api-versioning.md

Made cosmetic changes so the content reads more smoothly and uses the correct terminology - e.g delivery ECF policy because deliver ECF based training. Appreciate it should probably be deliver Early Career Teacher Entitlement but given this is internal facing have tweaked slightly.

Update api-versioning to fix typos and tweak some sentences.md

---

app/views/schools/register_ect_wizard/_appropriate_body_details.html.erb
app/views/schools/register_ect_wizard/_independent_school_appropriate_body.html.erb
app/views/schools/register_ect_wizard/_lead_provider.html.erb
app/views/schools/register_ect_wizard/_lead_provider_details.html.erb
app/views/schools/register_ect_wizard/_state_school_appropriate_body.html.erb
app/views/schools/register_ect_wizard/_use_previous_ect_choices.html.erb
app/views/schools/register_ect_wizard/start.html.erb
spec/features/schools/register_an_ect/happy_path_spec.rb
spec/views/schools/register_ect_wizard/shared_examples/independent_school_appropriate_body_view.rb
spec/views/schools/register_ect_wizard/shared_examples/state_school_appropriate_body_view.rb
spec/views/schools/register_ect_wizard/start.html.erb_spec.rb

We are updating some of the content in the journey to register an ECT that explains the different organisation types, as well as some other content updates on the first page of the journey.
| <img width="738" alt="image" src="https://github.com/user-attachments/assets/d7d98cda-c10f-43f8-a645-c40e9d220869" /> | <img width="692" alt="image" src="https://github.com/user-attachments/assets/5f590fda-2431-41ef-a17e-44b885839bc8" /> |
| <img width="748" alt="image" src="https://github.com/user-attachments/assets/4eeef28f-a8a9-472c-985a-a978eff74c96" /> | <img width="735" alt="image" src="https://github.com/user-attachments/assets/ea30fc89-3d3f-4a8a-8dc2-dc4f7b541aaa" /> |
| <img …

Update organisation roles guidance in the ECT registration journey

---

app/views/schools/register_ect_wizard/_appropriate_body_details.html.erb
app/views/schools/register_ect_wizard/_lead_provider_details.html.erb

This removes unnecessary `govuk-!-margin-top-5` classes that wasn't affecting the layout. Simplifies the markup slightly without changing the visual appearance.
Recommend hiding whitespace changes to make the diff clearer - it’s a very small change.

Remove unnecessary top margins

---

app/controllers/schools/register_mentor_wizard_controller.rb
app/services/schools/register_ect.rb
app/wizards/application_wizard.rb
app/wizards/schools/register_mentor_wizard/cannot_mentor_themself_step.rb
app/wizards/schools/register_mentor_wizard/cannot_register_mentor_step.rb
app/wizards/schools/register_mentor_wizard/check_answers_step.rb
app/wizards/schools/register_mentor_wizard/find_mentor_step.rb
app/wizards/schools/register_mentor_wizard/mentor.rb
app/wizards/schools/register_mentor_wizard/national_insurance_number_step.rb
app/wizards/schools/register_mentor_wizard/review_mentor_details_step.rb
app/wizards/schools/register_mentor_wizard/step.rb
app/wizards/schools/register_mentor_wizard/wizard.rb
spec/views/schools/register_mentor_wizard/already_active_at_school.md.erb_spec.rb
spec/views/schools/register_mentor_wizard/check_answers.html.erb_spec.rb
spec/views/schools/register_mentor_wizard/confirmation.md.erb_spec.rb
spec/views/schools/register_mentor_wizard/shared_examples/email_view.rb
spec/views/schools/register_mentor_wizard/shared_examples/review_mentor_details_view.rb
spec/wizards/application_wizard_spec.rb
spec/wizards/schools/register_ect_wizard/ect_spec.rb
spec/wizards/schools/register_ect_wizard/find_ect_step_spec.rb
spec/wizards/schools/register_ect_wizard/review_ect_details_step_spec.rb
spec/wizards/schools/register_mentor_wizard/change_mentor_details_step_spec.rb
spec/wizards/schools/register_mentor_wizard/national_insurance_number_step_spec.rb
spec/wizards/schools/register_mentor_wizard/review_mentor_details_step_spec.rb
spec/wizards/schools/register_mentor_wizard/shared_examples/review_mentor_details_step.rb
spec/wizards/schools/register_mentor_wizard/wizard_spec.rb

[Issue](https://github.com/DFE-Digital/register-early-career-teachers-public/issues/268)
Even though each step of the Register Mentor journey has a previous_step and next_step logic included to redirect the user to the appropriate next step, nothing prevents them from redirecting their browser to any random step at any time or navigate though them via the back and forward buttons of the browser.
Therefore, we need a way to be able to redirect the user's browser to the appropriate next step based on the overall state in the journey and the currently visited step.
The proposal in this PR is to extend the journey with functionality so that it can compute the list of allowed steps (steps we consider 'visitable') based on the current overall state in the journey, the actually visited step and …

Mentor wizard: redirect user to the first allowed step

---

.github/workflows/rspec.yml

Not sure why we were using this old version but support's about to expire so let's switch to a more modern one.

Update from Ubuntu 20.04 to latest for running specs

---

app/controllers/admin/appropriate_bodies_controller.rb
spec/requests/admin/appropriate_bodies/show_spec.rb

Problem was caused by the clash of the `Teachers` namespace so changing to `::Teachers` is necessary.

Fix the appropriate bodies show page

---

lib/tasks/db.rake

This reverts commit 6a16570c410a5eae29233894d3559be5b7e47944. The change appears to be flakey; it will sometimes boot the review app and other times it will fail when running the migrations.
Reverting to unblock the pipeline until we can can fix it properly.

Revert "Fix `db:prepare` rake task when ran without database"

---

config/terraform/application/config/production.tfvars.json

s189p01-cpdec2-pd-pg-snapshot isn't very healthy
Need to recreate db server and will increase to a B2s from B1ms (from 2G to 4G memory)
add postgres_snapshot_flexible_server_sku to production tfvars
make production terraform-plan

Increase snapshot db to B2s from B1ms sku

---

app/models/appropriate_body.rb
db/migrate/20250319234928_add_type_to_appropriate_bodies.rb

Do not call `AppropriateBody` model inside migrations.
Replace it with pure SQL to prevent errors recreating the database (CI for instance) if the model code or its columns change in future migrations.

Populate appropriate bodies via SQL in a migration

---

lib/tasks/db.rake

This was removed as we thought it was causing problems with the review app but it turns out it wasn't the culprit, see #434.

Re-add database exists check before adding search settings

---

app/views/schools/register_ect_wizard/_working_pattern.html.erb

A small tweak to the content on the working pattern page.
|<img width="822" alt="image" src="https://github.com/user-attachments/assets/bfbbc3ac-5ecf-458d-807f-f3e9f629b93c" />|<img width="838" alt="image" src="https://github.com/user-attachments/assets/55ddacc4-4bb7-43ec-ae79-c705063e0bd2" />|

Update title on working pattern partial

---

app/jobs/teachers/schedule_trs_sync_job.rb
app/models/teacher.rb
spec/jobs/teachers/schedule_trs_sync_job_spec.rb
spec/models/teacher_spec.rb

@emily-prudence-dfe noticed a bug where the same TRS records were being repeatedly refreshed. This is because, when ordering by a column `asc` it defaults to `nulls last`:
> The `NULLS FIRST` and `NULLS LAST` options can be used to determine whether nulls appear before or after non-null values in the sort ordering. By default, null values sort as if larger than any non-null value; that is, **`NULLS FIRST` is the default for `DESC` order, and `NULLS LAST` otherwise.**
Given we have an assortment of present and null refresh timestamps:
```
ecf2_development=# select id, trs_data_last_refreshed_at from teachers order by id asc;
┌────┬────────────────────────────┐
│ id │ trs_data_last_refreshed_at │
├────┼────────────────────────────┤
│  1 │ 2025-04-10 10:59:46.707283 │
│  2 │ 2025-04-10 …
```

Fix TRS sync ordering bug

---

app/services/teachers/manage.rb
db/scripts/remove_incorrectly_created_trs_sync_events.rb
spec/services/teachers/manage_spec.rb

There's a problem in production where events are always being written regardless of whether a name has changed or not.
It was caused by a mismatch between the variable names `induction_status_before` and `new_induction_status`. Because we were using instance variables they were interpolated as empty strings which were written to the events log.

Fix status change events

---

app/services/teachers/manage.rb
db/scripts/remove_blank_teacher_attributes_updated_from_trs_events.rb
spec/services/teachers/manage_spec.rb

We currently write the event regardless of whether anything actually changed.
This change skips the event recording when the modifications hash is empty. It also adds some more specs

Only write a TRS attrs updated event when things change

---

app/components/timeline_component.rb
spec/components/timeline_component_spec.rb
spec/factories/event_factory.rb

We have been recording a list of what changed on a record for certain event types for a while, but not exposing that data in the timeline.
This change just adds a 'Changes' header with a list of the changes pulled directly from the modifications column. When there are no modifications listed neither the heading or list are rendered.
Preview
* TRS QTS awarded on set to '14 Jan 2024'
* TRS QTS status description set to 'Qualified'
* TRS initial teacher training provider name set to 'Something'

Add list of modifications to the timeline

---

app/components/schools/mentors/summary_component.rb
app/models/mentor_at_school_period.rb
app/views/schools/mentors/index.html.erb
spec/components/schools/mentors/summary_component_spec.rb
spec/models/mentor_at_school_period_spec.rb
spec/rails_helper.rb

This PR updates the mentors index page to display the mentor's TRN and their currently assigned ECTs. 
To keep the view clean and maintainable, the summary card has been extracted into a dedicated SummaryComponent.
**Note:** The last commit with the route, is only here to make the view work. It's part of #464, so there's no need to review that commit.
|<img width="759" alt="image" src="https://github.com/user-attachments/assets/b0adfdbb-7851-49d6-8882-2413788b5aec" />|<img width="821" alt="image" src="https://github.com/user-attachments/assets/1fd90426-22d0-435d-ad00-3d3228d1e010" />|

[1344] Update mentor list and mentor details page to show assigned ECTs

---

spec/factories/induction_period_factory.rb
spec/services/admin/update_induction_period_spec.rb

We have a flakey spec in `spec/services/admin/update_induction_period_spec.rb:43`
The factory sets a `random number_of_terms` between `1` and `6`, which sometimes matches the expected value of `4` in a test. This caused the `.to change` matcher to fail since the value didn't actually change.
There is no value in setting this number dynamically so we are setting it to `1` in the factory as that is the most common `number_of_terms`.

Fix flaky spec in main by setting `random number_of_terms` to `1` in factory

---

db/scripts/remove_one_day_overlapping_induction_periods.rb

We had a problem with imported data where some records were adjusted so they had a length of 1 day instead of 0 (no longer allowed). That adjustment meant there's a chance they overlap other periods.
We want to delete those periods that:
- start on the same day as another period
- are 1 day long
The included query:
- finds all teachers that have 2 induction periods starting on the same day
- finds induction periods belonging to those teachers
- limits those induction periods to ones that are 1 day long
Rather than execute the deletion SQL directly we'll just hardcode the IDs of the 100 offending records.

Add script that deletes one day overlapping periods

---

app/components/schools/mentors/details_component.rb
app/components/schools/mentors/ect_mentor_training_details_component.html.erb
app/components/schools/mentors/ect_mentor_training_details_component.rb
app/components/schools/mentors/summary_component.rb
app/controllers/schools/mentors_controller.rb
app/helpers/mentor_helper.rb
app/views/schools/ects/show.html.erb
app/views/schools/mentors/show.html.erb
config/routes.rb
spec/components/schools/mentors/details_component_spec.rb
spec/components/schools/mentors/ect_mentor_training_details_component_spec.rb
spec/features/schools/mentors/viewing_a_mentor_spec.rb
spec/rails_helper.rb
spec/support/features/view_helpers.rb
spec/views/schools/mentors/show.html.erb_spec.rb

This PR introduces the ability to view individual mentor details and full end to end navigation support between mentors and ECTs.
---
- **New route, controller action, and view** for `/schools/mentors/:id`
- **Mentor summary details**: name, email, and list of assigned ECTs
- **ECT mentor training section**, rendered only when relevant (i.e. for `provider-led` ECTs)
- **Dynamic Back link navigation** between mentor show and ECT show pages
- **Helper methods** to enable easier testing
-  New `Schools::Mentors::DetailsComponent`
- New `Schools::Mentors::ECTMentorTrainingDetailsComponent`
**Conditionally render training section** if at least one ECT is `provider-led`
---
When viewing a mentor:
- You'll see their details and a list of assigned ECTs
- If any ECTs are **provider-led**, the "ECT …

[1301] View Individual Mentor Details

---

config/terraform/application/application.tf

Set `send_traffic_to_maintenance_page = true` can be used to send traffic to the maintenance page regardless of the app's state. Leaving it in the config as when we need it it might not be obvious where to put it, etc

Add disaster recovery hint to app config

---

app/controllers/schools/ects_controller.rb
app/services/teachers/search.rb
app/views/schools/ects/index.html.erb
config/initializers/pagy.rb
spec/requests/appropriate_bodies/teachers/index_spec.rb
spec/services/teachers/search_spec.rb

This change was more difficult that originally thought.
As outlined in [this comment](https://github.com/DFE-Digital/register-ects-project-board/issues/1266#issuecomment-2809341690), sorting ECTs by whether they have a mentor is complex.
| Before | After (2 items per page for demo purposes) |
| ----- | ------ |
| ![image](https://github.com/user-attachments/assets/517bca44-1400-46b9-8dfd-5ffe2484d695) |![Screenshot From 2025-04-17 14-56-37](https://github.com/user-attachments/assets/3444252a-1f81-4735-9eef-9b50e5572263) |
1. Make the ECT index page use `Teachers::Search`
2. Allow `Teachers::Search` to find teachers who are currently ECTs at a school
3. Add a custom sort order so we can put mentorless ECTs first, and then sort by most-recently registered
4. change the global pagination …

Change sorting on schools' ECT index page

---

app/helpers/appropriate_body_helper.rb
app/services/teachers/induction_extensions.rb
app/views/appropriate_bodies/claim_an_ect/check_ect/edit.html.erb
spec/services/teachers/induction_extensions_spec.rb
spec/views/appropriate_bodies/claim_an_ect/check_ect/edit.html.erb_spec.rb

Surfacing the `extensions` number on the check ECT record page because it's useful information for appropriate bodies.
|<img width="565" alt="image" src="https://github.com/user-attachments/assets/8dcc7ac3-cac6-4acc-9a3b-34df47a8403c" />|<img width="583" alt="image" src="https://github.com/user-attachments/assets/35642a98-26be-4b7a-8879-c1f1bf9a9fd2" />|
- Fix pluralisation of decimal term counts
- Surface extensions on the check details page
- Optimise calculation by using active record

[1500] Make extensions visible on the claim ECT record check page

---

.github/workflows/deploy.yml

At the moment, if we branch off a branch other than `main` and raise a PR it will not trigger a CI run.
As we are working on a non-main base branch for the partnerships spike we would like to run CI on all pull requests.
PR to demonstrate it working: https://github.com/DFE-Digital/register-early-career-teachers-public/pull/535

Run CI on all pull requests

---

spec/features/admin/teachers/edit_induction_period_spec.rb

This spec is now failing, it seems to be date-related; moving to the following month fixes it, so I've pinned it to the next month of the previous year.

Fix flakey admin feature spec

---

app/views/schools/register_mentor_wizard/trn_not_found.md.erb

This fixes:
- the lack of a break
- the lack of full stops

Fix typo on mentor TRN not found page

---

.env.example

These environment variables need to be populated in order for the GIAS school import rake task to run.

Add example env vars for GIAS import

---

app/models/school.rb
app/models/school_partnership.rb
app/models/training_period.rb
app/services/api/school_partnerships/create.rb
app/services/api/school_partnerships/update.rb
config/analytics_blocklist.yml
db/migrate/20250501130805_add_ecf_id_to_models.rb
db/schema.rb
spec/models/school_partnership_spec.rb
spec/models/school_spec.rb
spec/models/training_period_spec.rb
spec/services/api/school_partnerships/create_spec.rb
spec/services/api/school_partnerships/update_spec.rb

[Jira-4222](https://dfedigital.atlassian.net.mcas.ms/browse/CPDLP-4222)
Add support for creating and updating partnerships by replicating the service behaviour in ECF.
Add `ecf_id` to `School`, `DeliveryPartner` and `LeadProvider` models.
Add convenience methods to `School` for eligibility checks.
Add `Create` and `Update` services.
Accept expressions of interest for the same school when creating a `SchoolPartnership`.
There's going to be some difficulty with keeping parity with ECF and also adopting the RECT modelling/terminology. I've opted to keep the service request/attribute naming consistent with RECT, however we'll need to translate the attributes back into what we currently return in ECF (along with any error messages - replacing `registration year` with `cohort`, for example). We …

Support creating/updating partnerships

---

spec/components/schools/mentors/details_component_spec.rb
spec/components/schools/mentors/ect_mentor_training_details_component_spec.rb
spec/components/schools/mentors/summary_component_spec.rb
spec/features/schools/mentors/viewing_a_mentor_spec.rb
spec/rails_helper.rb
spec/views/appropriate_bodies/claim_an_ect/check_ect/edit.html.erb_spec.rb
spec/views/schools/mentors/show.html.erb_spec.rb
spec/wizards/schools/register_mentor_wizard/find_mentor_step_spec.rb
spec/wizards/schools/register_mentor_wizard/national_insurance_number_step_spec.rb

Including modules at a high level makes it hard to see where methods are coming from, and when they overlap with Rails methods (create, build) it's confusing for people new to the codebase. Instead let's be explicit when we're using FactoryBot.

Make FactoryBot calls explicit

---

spec/services/teachers/refresh_trs_attributes_spec.rb

I introduced this flaky spec, it appears the tests run much slower in CI than on my computer. Switching over to `freeze_time` is clearly a better idea.

Use `freeze_time` instead of approximation

---

app/views/schools/ects/index.html.erb
app/views/schools/mentors/index.html.erb
spec/features/schools/register_an_ect/edge_cases/find_teacher_using_national_insurance_number_spec.rb
spec/features/schools/register_an_ect/edge_cases/teacher_with_national_insurance_number_is_not_found_spec.rb
spec/features/schools/register_an_ect/happy_path_spec.rb
spec/views/schools/ects/index.html.erb_spec.rb
spec/views/schools/mentors/index.html.erb_spec.rb

We want to render different content on the mentor and ECT index pages when there are no teachers. 
Note that on the ECT index page, we are also rendering different content on the CTA button. The previous content will render if there are teachers.

[1498] Handle no teachers on ECT and Mentor index pages

---

README.md

It feels like unnecessary clutter to have this in the README, the diagram will autogenerate when a migration is run and this should be committed with the migration.
Therefore the diagram should always be up to date and there should be no need for someone to manually regenerate.

Remove regeneration steps from readme

---

documentation/service-rules/ecf1/lead-provider-api.md
documentation/service-rules/ecf1/partnerships.md

[Jira-4249](https://dfedigital.atlassian.net.mcas.ms/browse/CPDLP-4249)
We want to document how partnerships are structured, formed and used in the early careers framework. This will help us when migrating the functionality and behaviour into RECT.

Add partnerships documentation to ECF1 service rules

---

.github/pull_request_template.md

As discussed in slack, add an optional simple PR template. This is based off the [ECF template](https://github.com/DFE-Digital/early-careers-framework/blob/main/.github/PULL_REQUEST_TEMPLATE.md)
Format from [docs](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository#adding-a-pull-request-template)

Add optional pull request template

---

Dockerfile
bin/docker-entrypoint
config/terraform/application/application.tf
config/terraform/application/variables.tf

This is wholesale lifted from https://github.com/DFE-Digital/itt-mentor-services/.
There it was intended to ensure there are no problems caused by multiple containers trying to run the same migrations simultaneously. Here we'll benefit from that too, but also it will simplify our Dockerfile and mean we only need to worry about starting the app, not doing database migration stuff too.

Run migrations before trying to boot the app

---

app/helpers/ect_helper.rb
app/views/schools/register_mentor_wizard/start.html.erb
spec/views/schools/register_mentor_wizard/start.html.erb_spec.rb

[Issue](https://github.com/DFE-Digital/register-ects-project-board/issues/1438)
When a school user clicks 'Assign mentor...' to one of their ECTs listed, they can be redirected either to (1) an intermediate page (if there are potential mentors already registered at the school) listing potential mentors + add a new one or (2) straight to the start of the journey to add a new mentor (if there are no potential mentors already registered at the school).
The back link in the view of the start of the journey to add a new mentor (What you will need to register a new mentor) is always linking back to the list of ECTs of the school. 
This ticket will amend that behavior so that in (1) it will redirect the user back to the intermediate view listing the potential mentors of the ECT and in (2) back …

[1438] - Back link from the start of register mentor journey depends on the referer page

---

app/views/admin/teachers/show.html.erb
spec/requests/admin/teachers/show_spec.rb
spec/views/admin/teachers/show.html.erb_spec.rb

Ready to surface the admin event timeline 
Add link to ECT's timeline on their admin page
Login as admin and navigate to an ECT and click `View change history`
Fixes #619

Add admin timeline link

---

spec/models/statement_spec.rb

We are getting a warning from using `validate_inclusion_of` on a boolean value in the model
Change spec to `allow_value` instead and add a test for when the value is `nil` as well 
Rerun test `spec/models/statement_spec.rb` and there should be no warning

Use `allow_value` instead of shoulda matcher `validate_inclusion_of`

---

app/forms/appropriate_bodies/process_batch_form.rb
app/presenters/pending_induction_submission_batch_presenter.rb
public/bulk-actions-template.csv
spec/features/appropriate_bodies/process_batch_action_spec.rb
spec/fixtures/invalid_duplicate_trns_action.csv
spec/fixtures/invalid_duplicate_trns_claim.csv
spec/fixtures/invalid_missing_columns.csv
spec/fixtures/seeds_action.csv
spec/fixtures/seeds_claim.csv
spec/fixtures/valid_complete_action.csv
spec/fixtures/valid_complete_claim.csv
spec/forms/appropriate_bodies/process_batch_form_spec.rb
spec/presenters/pending_induction_submission_batch_presenter_spec.rb
spec/requests/appropriate_bodies/process_batch/actions/show_spec.rb

Bulk upload bug party snags
Testers saw errors due to:
1. Non-CSV data being parsed and treated as if it were CSV data rather than being told the file was not a CSV (https://github.com/DFE-Digital/register-early-career-teachers-public/pull/603 stops exposing these internal errors now we are done with testing)
2. After having edited and exported from XLS files, testers had created files with many additional blank rows
3. Using software that delimited headers by spaces
1. Upload images, Excel spreadsheets, anything 
2. Upload a valid file with completely empty rows anywhere, either at the end, in the middle of the data or at the start `,,,,,,,`
[test 3.csv](https://github.com/user-attachments/files/20406375/test.3.csv)
3. Using capable software like LibreOffice, by default the template CSV, …

Bulk upload outcomes: post-party snag list

---

app/controllers/api/base_controller.rb
app/controllers/concerns/api/token_authenticatable.rb
app/models/api/token.rb
app/models/api_token.rb
app/models/event.rb
app/models/lead_provider.rb
app/services/api/token_manager.rb
app/services/events/record.rb
db/seeds.rb
spec/factories/api_token_factory.rb
spec/models/api/token_spec.rb
spec/models/api_token_spec.rb
spec/models/lead_provider_spec.rb
spec/rails_helper.rb
spec/requests/api/v3/declarations_spec.rb
spec/requests/api/v3/delivery_partners_spec.rb
spec/requests/api/v3/participant_transfers_spec.rb
spec/requests/api/v3/participants_spec.rb
spec/requests/api/v3/partnerships_spec.rb
spec/requests/api/v3/schools_spec.rb
spec/requests/api/v3/statements_spec.rb
spec/requests/api/v3/unfunded_mentors_spec.rb
spec/services/api/token_manager_spec.rb
spec/services/events/record_spec.rb
spec/support/requests/api_helper.rb
spec/support/shared_contexts/api/token_authenticated_endpoint.rb

We want to use the new `APIToken` model in order to authenticate API requests. We also want to include known tokens for seeded lead providers so that we can easily test in development.
- Add methods to create/find API tokens
Add a method to create a new `APIToken` for a `LeadProvider`. It will default to a randomly generated `token` if not specified and a predefined `description`.
Add method to retrieve an `APIToken` for a given `token`. It will touch the `last_used_at` timestamp when doing so.
- Add APIToken seeds for each LeadProvider
Generate a known token for each lead provider in the seeds.
- Authenticate API controllers
Add `API::TokenAuthenticatable` concern and include it in the `API::BaseController`.
Add `ApiHelper` to easily make authenticated requests in the specs.
Add shared …

Add `APIToken` functionality/seeds

---

config/initializers/rack_attack.rb
spec/requests/rate_limiting_spec.rb
spec/support/rack_attack.rb
spec/support/requests/api_helper.rb
spec/support/shared_examples/rate_limiting_support.rb

Ticket: https://github.com/DFE-Digital/register-ects-project-board/issues/1655
* Updated rack attack config to throttle `/api/` requests, 1000 requests per 5 minutes
* Added fall back throttle for 1000 requests per 5 minutes
* Added `remote_ip` changes from https://github.com/DFE-Digital/early-careers-framework/pull/4085
* Added rspec tests

[1655] Rate limiting for /api/ with rack attack

---

config/personas.yml

When I demoed the personas in staging and review apps, it was asked what they're for.
Many are just alternatives, but this persona does have a specific reason to exist, so we should make it clear.
Add to school-type that it has no prior ECTs registered
Check I haven't broken anything

Be more specific on why the Felix Starling persona exists

---

app/migration/migrators/registration_period.rb
spec/factories/migration/cohort_factory.rb
spec/migration/migrators/registration_period_spec.rb

Ticket: https://github.com/DFE-Digital/register-ects-project-board/issues/1669
This PR primarily adds specs for the registration period migrator.
It also updates the migrator to include the `started_on` and `finished_on` values when creating RegistrationPeriod records. The started_on is set to the cohort’s registration_start_date, and the finished_on is calculated as one year later, minus one day.
- Add factory to create ecf cohorts
- Add specs for the registration period migrator
- Update the migrator to include the missing started_on and finished_on fields

Add specs for the registration period migrators

---

.devcontainer/devcontainer.json
.devcontainer/docker-compose.yml

This appeared to have broken because of two recent changes:
* adding database encryption for API token fields #627
* adding a secondary ECF database connection #646
It also gets rid of the [VSCode tslint plugin](https://github.com/microsoft/vscode-tslint) which is deprecated.
| Seeded Codespace | Running Codespace |
| -------- | ----------|
| ![Screenshot From 2025-06-02 17-12-40](https://github.com/user-attachments/assets/5b669590-e17b-46a4-a4d2-1131e8ae2d74) | ![Screenshot From 2025-06-02 17-13-26](https://github.com/user-attachments/assets/140e9b1a-dce9-4e80-9388-a8111bef7eca) |
Sometimes when building it failed because repos weren't reachable etc. Not really sure what the cause is, but it worked on a retry.

Fix Codespaces

---

app/components/navigation/primary_navigation_component.rb
app/controllers/admin/finance/statements_controller.rb
app/controllers/admin/finance_controller.rb
app/controllers/admin/organisations_controller.rb
app/helpers/application_helper.rb
app/presenters/admin/statement_presenter.rb
app/views/admin/finance/show.html.erb
app/views/admin/finance/statements/index.html.erb
app/views/admin/finance/statements/show.html.erb
app/views/admin/organisations/index.html.erb
config/routes.rb
spec/helpers/application_helper_spec.rb
spec/presenters/admin/statement_presenter_spec.rb
spec/requests/admin/finance/finance_spec.rb
spec/requests/admin/finance/statements/statements_spec.rb
spec/views/admin/finance/show.html.erb_spec.rb
spec/views/admin/finance/statements/index.html.erb_spec.rb
spec/views/admin/finance/statements/show.html.erb_spec.rb

This is a rough draft containing statements pages.
The design will be iterated but for now they just list the statements as per the prototype and add a finance page that has a link to the statements index.
It's intended to be a starting off point and to allow us to review data in the app.
* no filters - we need to decide how they're going to work, hopefully avoiding the current broken state where you can select incompatible years/statements and get no results
* no secondary horizontal nav - this is in the prototype but for now I've reused the extra nav page style from organisations. It keeps the hierarchy in tact and doesn't require new code/styles.
- **Fix the organisations layout**
- **Add routes for finance and statements**
- **Add boolean to yes or no helper**
- **Add statement …

Add admin finance page and statements list

---

spec/requests/appropriate_bodies/claim_an_ect/register_ect_spec.rb

The date is now more than 2 years ago so it was before the default `trs_qts_awarded_on` date set by the pending induction submissions factory.
I've both made the date dynamic and set the `trs_qts_awarded_on` explicitly to make the relationship between them clear.

Remove hardcoded date from AB reg spec

---

.env.example
app/services/teachers/refresh_trs_attributes.rb
config/application.rb
config/terraform/application/config/sandbox.yml
spec/services/teachers/refresh_trs_attributes_spec.rb

We do not want to allow syncs/data pulls from TRS in the sandbox environment to overwrite data in the database (as this may end up confusing lead providers).
- Disable reading from TRS in sandbox environment
Introduce a `trs_write_only` config variable which is `false` by default and `true` in sandbox to prevent the `Teachers::RefreshTRSAttributes` service from making any changes.
The main source of TRS overwriting our local teacher data is in the recurring jobs which are only enabled in production. There are, however, two jobs `FailECTInductionJob` and `PassECTInductionJob` which both write data to TRS and then read it back via the `Teachers::RefreshTRSAttributes` service.

Disable reading from TRS in sandbox environment

---

app/services/api/add_api_token_to_lead_provider.rb
lib/tasks/api_token.rake
spec/lib/tasks/api_token_spec.rb
spec/rails_helper.rb
spec/services/api/add_api_token_to_lead_provider_spec.rb
spec/spec_helper.rb

[Issue #1688](https://github.com/DFE-Digital/register-ects-project-board/issues/1688)
We need to setup API tokens for providers to test the API in sandbox.
- Create a task to generate API tokens for providers;
- Generates tokens for all lead providers: `rake 'lead_provider:generate_api_token'`
- Generates token for a specific lead provider by name: `rake 'lead_provider:generate_api_token[Ambitious Institute]'`
- Generates token for a specific lead provider by id: `rake 'lead_provider:generate_api_token[1]'`

[1688] Add task to set up API tokens

---

config/terraform/application/config/review.yml

We had this set to Next for API testing early on when releasing RIAB but now there's something causing it to crash, so for now push this back to the stable verison.
Fixes DFE-Digital/register-ects-project-board#1723

Use TRS API version 20250203 instead of Next in Review

---

app/views/appropriate_bodies/process_batch/actions/_failed.html.erb
spec/views/appropriate_bodies/process_batch/actions/failed.html.erb_spec.rb

Bulk outcomes has a `failed` state that should never be needed but if an upload suffers an internal error this is the view partial that the user will see.
https://cpd-ec2-review-699-web.test.teacherservices.cloud/appropriate-body/bulk/actions/1

Update failed batch action view content

---

config/application.rb
config/terraform/application/config/migration.yml

We want to be able to enable the parity check functionality only on the migration environment.
Add config option to enable the parity check. This is nested as we will end up with other options under the parity check config (for tokens and environment URLs).

Add toggle to enable/disable parity check

---

spec/migration/migrators/statement_spec.rb

There's a flakey spec:
`rspec "./spec/migration/migrators/statement_spec.rb[1:1:9:6:1]`
Spec was flakey due the statement records already in the db to possible have the same month/year of the record to be migrated and for both having the same lead provider.

Fix flakey spec in the statements migrator specs

---

app/views/schools/register_ect_wizard/_lead_provider.html.erb
app/views/schools/register_mentor_wizard/review_mentor_eligibility.html.erb
documentation/glossary.md

We agreed in UR to remove this content.
We also agreed to add the bits on learning platforms
1. Remove the content on if you're not sure who is providing training for mentors
2. Add content on learning platform to the lead provider question

Remove content on if you're not sure on who is providing training for mentors and add content to LP description on learning platform

---

.github/workflows/refresh_migration_database.yml

There was a missing closing quote causing the refresh to fail.
[Successful run](https://github.com/DFE-Digital/register-early-career-teachers-public/actions/runs/15683544563)

Fix token generation during migration DB refresh

---

spec/services/events/record_spec.rb

Webmock is now being used, one spec calls TRS via a background job prior to the fake API being included
Reorder the spec

Fix issue with TRS API in event spec

---

app/components/admin/statements/adjustments.html.erb
app/components/admin/statements/adjustments.rb
app/controllers/admin/finance/adjustments_controller.rb
app/helpers/number_helper.rb
app/models/statement.rb
app/models/statement/adjustment.rb
app/views/admin/finance/adjustments/_fields.html.erb
app/views/admin/finance/adjustments/delete.html.erb
app/views/admin/finance/adjustments/edit.html.erb
app/views/admin/finance/adjustments/new.html.erb
app/views/admin/finance/statements/show.html.erb
config/routes.rb
spec/components/admin/statements/adjustments_spec.rb
spec/features/admin/finance/adjustments/create_adjustment_spec.rb
spec/features/admin/finance/adjustments/delete_adjustment_spec.rb
spec/features/admin/finance/adjustments/list_adjustments_spec.rb
spec/features/admin/finance/adjustments/update_adjustment_spec.rb
spec/helpers/number_helper_spec.rb
spec/models/statement/adjustment_spec.rb
spec/models/statement_spec.rb
spec/views/admin/finance/statements/show.html.erb_spec.rb

Ticket: https://github.com/DFE-Digital/register-ects-project-board/issues/1749
* New component `Admin::Statements::Adjustments`
* Using summary card instead of table (ecf1)
* Add/change/remove adjustments for statements
* `NumberHelper` added for £
* Login as admin
* Go to an open statement

[1749] Adjustments for statements

---

app/migration/migrators/reconcile_adjustment.rb
app/migration/migrators/statement_adjustment.rb
app/models/migration/finance_adjustment.rb
spec/factories/migration/finance_adjustment_factory.rb
spec/migration/migrators/reconcile_adjustment_spec.rb
spec/migration/migrators/statement_adjustment_spec.rb

Add a migrator for ECF `Finance::Adjustment` records. These are attached to a `Statement` and so are dependent on the statement migrator being run beforehand.
There are 2 migrators for this:
1. a migrator that migrates the existing `Finance::Adjustment` records from ECF and creates `Statement::Adjustment` records in RECT
2. a migrator that creates `Statement::Adjustment` records for ECF `Finance::Statement` records that have a non-zero `reconcile_amount`
Statements with a `reconcile_amount` value was how an adjustment was performed prior to the introduction of the adjustment record functionality in ECF. There are only 8 statements with a non-zero `reconcile_amount` value in ECF
I split this into 2 migrators because they are performing different queries against different tables so more …

Add migrator for statement adjustments

---

.env.example
app/migration/migrators/active_lead_provider.rb
app/migration/migrators/base.rb
app/migration/migrators/lead_provider.rb
app/migration/migrators/statement.rb
app/migration/parity_check/token_provider.rb
app/models/lead_provider.rb
config/analytics_blocklist.yml
db/migrate/20250617185849_rename_api_id_to_ecf_id_in_lead_providers.rb
db/schema.rb
spec/factories/lead_provider_factory.rb
spec/migration/migrators/active_lead_provider_spec.rb
spec/migration/migrators/lead_provider_spec.rb
spec/migration/migrators/reconcile_adjustment_spec.rb
spec/migration/migrators/statement_adjustment_spec.rb
spec/migration/migrators/statement_spec.rb
spec/migration/parity_check/client_spec.rb
spec/migration/parity_check/configuration_spec.rb
spec/migration/parity_check/request_builder_spec.rb
spec/migration/parity_check/token_provider_spec.rb
spec/models/lead_provider_spec.rb

We will be importing the `uuid` from ECF1 into RECT. IDs required for the API will be stored in columns called `api_id` Those values will autogenerate when not set and will never be `null`. 
IDs required for the migration and to make moving data easier, however not needed for the API and likely to be removed after will be called `ecf_id`. Those IDs are not auto generated and can be `null`
Lead provider ids are not surfaced in the API so can be renamed to `ecf_id`
- Rename the column `api_id` to `ecf_id` in Lead providers
- Rename all occurrences of this column name in migrators and parity check to `ecf_id`

Rename Lead Provider `api_id` to `ecf_id`

---

app/services/ect_at_school_periods/training.rb
spec/services/ect_at_school_periods/training_spec.rb

These specs were commented out as part of #507.
Now it's done they are being reinstated.
I rejigged the service class so it adheres to the new schema.
It also now eager loads the whole set of training data up front so we're not firing query after query while traversing.
Fixes #767

Rework `ECTAtSchoolPeriods::Training` and uncomment the disabled specs

---

app/migration/migrators/delivery_partner.rb
app/migration/migrators/lead_provider_delivery_partnership.rb
app/models/delivery_partner.rb
app/models/lead_provider_delivery_partnership.rb
spec/factories/migration/provider_relationship_factory.rb
spec/migration/migrators/delivery_partner_spec.rb
spec/migration/migrators/lead_provider_delivery_partnership_spec.rb

We were missing a migrator for `LeadProviderDeliveryPartner` so this adds one to migrate `ProviderRelationship` records in ECF to `LeadProviderDeliveryPartner` in RECT.
This also required `DeliveryPartner` which was in-place but wasn't using/storing `api_id` from ECF so have updated that migrator too.

Add a migrator for `LeadProviderDeliveryPartnerships` and update `DeliveryPartner` migrator

---

app/migration/migrators/statement.rb
app/models/statement.rb
app/presenters/admin/statement_presenter.rb
app/services/sandbox_seed_data/statements.rb
app/services/statements/query.rb
config/analytics_blocklist.yml
db/migrate/20250620092940_rename_statements_state_to_status.rb
db/schema.rb
db/seeds/statements.rb
spec/factories/statement_factory.rb
spec/migration/migrators/statement_spec.rb
spec/models/statement_spec.rb
spec/presenters/admin/statement_presenter_spec.rb
spec/serializers/statement_serializer_spec.rb
spec/services/sandbox_seed_data/statements_spec.rb
spec/services/statements/query_spec.rb

We have lots of status columns in the app already and having one called 'state' (as it is in ECF1) will likely be confusing.
This change renames the column, enumerated type and all refences to 'state' to 'status'
Fixes #715
Did I miss anywhere? It's hard to search for with `state` being the first half of `statement` and a common general term :grimacing:

Rename `statements.state` to `status`

---

app/migration/parity_check/dynamic_request_content.rb
app/migration/parity_check/request_builder.rb
documentation/parity-check.md
spec/migration/parity_check/dynamic_request_content_spec.rb
spec/migration/parity_check/request_builder_spec.rb

To avoid the `RequestBuilder` bloating with all the dynamic request content we will be adding as we add new endpoints, it makes sense to extract them to their own class to keep things cleaner.

Extract dynamic request content from RequestBuilder

---

bin/dev

I started to notice job worker crashes with `Process memory map` when I was working on a new laptop.
Whilst investigating, I spotted a potential cause, or at least something that could be changed.
SolidQueue is started via foreman and also via rake.

Remove redundant SolidQueue rake task from bin/dev script

---

app/controllers/migration/parity_checks_controller.rb
app/helpers/parity_check_helper.rb
app/migration/parity_check/runner.rb
app/migration/parity_check/seed_endpoints.rb
app/models/parity_check/endpoint.rb
app/models/parity_check/request.rb
app/models/parity_check/response.rb
app/models/parity_check/run.rb
app/views/migration/parity_checks/_form.html.erb
app/views/migration/parity_checks/new.html.erb
config/parity_check_endpoints.yml
config/routes.rb
spec/features/migration/run_parity_check_spec.rb
spec/fixtures/files/parity_check_endpoints.yml
spec/helpers/parity_check_helper_spec.rb
spec/migration/parity_check/runner_spec.rb
spec/migration/parity_check/seed_endpoints_spec.rb
spec/models/parity_check/endpoint_spec.rb
spec/models/parity_check/request_spec.rb
spec/models/parity_check/response_spec.rb
spec/models/parity_check/run_spec.rb
spec/requests/migration/parity_check_spec.rb

We want to add a page available to DfE users that allows us to kick off a parity check. It should only be accessible if you are a DfE user and the parity check is enabled on the environment. We want to list and allow the user to select endpoints for the run.
- Support multiple endpoints with the same method/path
At the moment if we define two endpoints with the same path under the same request method in the YAML file we only get one after parsing the file due to it being structured in a hash.
To avoid this, we can change the endpoints to be array items; this will allow duplicates. The use case for this is when testing, for example, an index action once with pagination and a separate time with filters.
- Add group_name and description to Endpoint
When we come to render an endpoint in a …

Add parity check start page

---

app/components/admin/statements/payment_authorisation_component.html.erb
app/components/admin/statements/payment_authorisation_component.rb
app/controllers/admin/finance/statements_controller.rb
app/helpers/application_helper.rb
app/models/statement.rb
app/presenters/admin/statement_presenter.rb
app/services/statements/authorise_payment.rb
app/views/admin/finance/statements/show.html.erb
config/routes.rb
public/api/docs/v3/swagger.yaml
spec/components/admin/statements/payment_authorisation_component_spec.rb
spec/features/admin/finance/statements/payment_authorisation_spec.rb
spec/helpers/application_helper_spec.rb
spec/models/statement_spec.rb
spec/presenters/admin/statement_presenter_spec.rb
spec/services/statements/authorise_payment_spec.rb
spec/swagger_helper.rb

Ticket: https://github.com/DFE-Digital/register-ects-project-board/issues/1781
* Created `Admin::Statements::PaymentAuthorisationComponent` component
* Created `Statements::AuthorisePayment` service class
* Controller action to authorise payment
* In DfE admin, go to statements
* Select a `payable` statement

[1781] Authorise for payment action on statement

---

Gemfile
Gemfile.lock
spec/rails_helper.rb

It's really good for comparing hashes, arrays and strings but it seems to dump a ton of ActiveRecord stuff into the terminal when inspecting records.

Remove `super_diff` gem

---

app/assets/stylesheets/migration/parity_check.scss
app/controllers/migration/parity_checks/requests_controller.rb
app/controllers/migration/parity_checks_controller.rb
app/helpers/parity_check_helper.rb
app/models/parity_check/response.rb
app/views/migration/parity_checks/completed.html.erb
app/views/migration/parity_checks/requests/show.html.erb
app/views/migration/parity_checks/show.html.erb
config/routes.rb
db/seeds/parity_checks.rb
spec/factories/parity_check/request_factory.rb
spec/features/migration/view_completed_parity_checks_spec.rb
spec/features/migration/view_parity_check_request_spec.rb
spec/features/migration/view_parity_check_spec.rb
spec/features/migration/view_pending_and_in_progress_parity_checks_spec.rb
spec/helpers/parity_check_helper_spec.rb
spec/models/parity_check/request_spec.rb
spec/models/parity_check/response_spec.rb
spec/requests/migration/parity_check_spec.rb

We want to add a page that shows the details of a parity check request and links in to each of the responses.
- Add view helpers for parity check responses
Add view helpers to render out details of a parity check response; we want to show the status code as a colour-coded tag and the comparison emoji for matching/different responses.
- Expose different? method on parity check response
To avoid `unless matching?` in various places its going to be helpful to have `different?` exposed publicly.
- Don't set page on single responses
When a request only has a single response its most likely not a paginated result; seed single responses with a `nil` page for more realistic data.
- Improve parity check request factory
When generating a completed request we should make sure the run is also in a …

Show a parity check request in detail

---

app/migration/builders/ect/school_periods.rb
app/migration/builders/ect/training_periods.rb
app/migration/builders/mentor/school_periods.rb
app/migration/builders/mentor/training_periods.rb
app/migration/migrators/ect_at_school_period.rb
app/migration/migrators/mentor_at_school_period.rb
app/migration/migrators/teacher.rb
app/migration/migrators/training_period.rb
app/models/lead_provider_delivery_partnership.rb
app/models/migration/induction_record.rb
app/models/migration/participant_identity.rb
app/models/migration/participant_profile.rb
app/models/migration/school_cohort.rb
app/models/migration/user.rb
app/models/school_partnership.rb
spec/factories/migration/induction_programme_factory.rb
spec/factories/migration/induction_record_factory.rb
spec/factories/migration/participant_identity_factory.rb
spec/factories/migration/participant_profile_factory.rb
spec/factories/migration/schedule_factory.rb
spec/factories/migration/school_cohort_factory.rb
spec/factories/migration/teacher_profile_factory.rb
spec/factories/migration/user_factory.rb
spec/migration/migrators/ect_at_school_period_spec.rb
spec/migration/migrators/mentor_at_school_period_spec.rb
spec/migration/migrators/teacher_spec.rb
spec/migration/migrators/training_period_spec.rb

Currently there is a "Teacher" migrator that creates `Teacher` records, `ECTAtSchoolPeriod`, `MentorAtSchoolPeriod` and `TrainingPeriod` records from ECF data.
There are lots of data issues to sort out as this is the main part of the participant migration.  If we split these into separate migrators it will allow a clearer view of the issues and where they appear and also make it easier to work on in parallel, at the cost of some duplication at this stage.
Refactor teacher migrator into migrators for the separate models

Splitting up teacher migrator

---

Gemfile
Gemfile.lock
app/assets/stylesheets/migration/parity_check.scss
app/controllers/migration/parity_checks/responses_controller.rb
app/helpers/parity_check_helper.rb
app/models/parity_check/request.rb
app/models/parity_check/response.rb
app/models/parity_check/run.rb
app/views/migration/parity_checks/requests/show.html.erb
app/views/migration/parity_checks/responses/show.html.erb
app/views/migration/parity_checks/show.html.erb
config/routes.rb
db/seeds/parity_checks.rb
spec/factories/parity_check/response_factory.rb
spec/features/migration/view_completed_parity_checks_spec.rb
spec/features/migration/view_parity_check_request_spec.rb
spec/features/migration/view_parity_check_response_spec.rb
spec/features/migration/view_parity_check_spec.rb
spec/helpers/parity_check_helper_spec.rb
spec/models/parity_check/request_spec.rb
spec/models/parity_check/response_spec.rb
spec/models/parity_check/run_spec.rb
spec/requests/migration/parity_check_spec.rb

We want to be able to click into a response that is different in order to see a diff of the response bodies and identify what's changed.
Add routes/actions for showing a parity check response.
Add `diffy` to generate diffs of the response bodies.
Add more realistic JSON bodies to the seed data.
Add convenience methods to models and view helper methods.
| Single response | Page response |
| -- | -- |
| <img width="1142" alt="Screenshot 2025-06-30 at 14 17 24" src="https://github.com/user-attachments/assets/b0830807-4309-4e72-b01d-ace350e9d001" /> | <img width="1142" alt="Screenshot 2025-06-30 at 14 17 50" src="https://github.com/user-attachments/assets/6883a092-414d-4437-a87e-66ecfd3e990e" /> |

Show parity check response

---

spec/features/schools/ects/register/edge_cases/appropriate_body_selection/independent_school_selects_istip_spec.rb
spec/features/schools/ects/register/edge_cases/appropriate_body_selection/independent_school_selects_teaching_school_hub_spec.rb
spec/features/schools/ects/register/happy_path_spec.rb

I saw these tests change in a recent PR, and this popped into my head. Keen to hear others thoughts 💚
Before, we defined a private, memoized method `one_month_ago_today` to refer to the date 1 month ago.
This seemed superfluous, but I'm mindful I might be missing something.
How do we feel about leaning on [`ActiveSupport::Duration`][docs] in these situations?
I find it clear and intuitive, but I wonder what other people think?
There might be other places we could make similar changes, but I figured it's worth discussing before digging any deeper!
[docs]: https://api.rubyonrails.org/classes/ActiveSupport/Duration.html
- Run the relevant tests

Lean on `ActiveSupport::Duration` in tests

---

app/models/training_period.rb
spec/models/training_period_spec.rb

Ticket: https://github.com/DFE-Digital/register-early-career-teachers-public/issues/774
Using `has_one` with `through` to get `delivery_partner` and `lead_provider`, instead of method or delegation.
As we're using ActiveRecord it allows us to avoid N+1 issues by using includes/joins:
```ruby
TrainingPeriod.includes(:delivery_partner).each do |tp|
puts tp.delivery_partner_name
end
```
We should avoid using `delegate` for associations.

[774] use has_one through for lead_provider and delivery_partner

---

lib/tasks/db.rake

This hopefully fixes the bug we've all encountered where attempting to run the specs after doing a `rails db:migrate` or `rails db:rollback` caused errors.
The key line that makes the difference is:
```ruby
Rake::Task['db:test:prepare'].enhance(['db:setup_search_configuration'])
```
The rest of the PR makes the rake task easier to follow by separating the steps into methods.
The `add_configuration` can now be run repeatedly as it will return early if the `configuration_already_exists?`

Attempt to fix bug caused by unaccent config

---

app/controllers/appropriate_bodies/teachers_controller.rb
app/models/teacher.rb
app/services/teachers/induction_period.rb

We saw some [N+1 queries in Sentry](https://dfe-teacher-services.sentry.io/issues/6621363705/?project=4508369974788096&query=is%3Aunresolved&referrer=issue-stream&stream_index=6) on the appropriate bodies teachers index. We fixed one in #849, and this resolves the other.
Following on from #849 (and in a similar vein to #843), this introduces a couple of associations to the `Teacher` model for their first and last induction periods.
Before, we would retrieve these to return various pieces of information (e.g induction start date) and present them to the User. This worked, but resulted in N+1 queries since we iterate a collection of teachers.
By defining these relationships as associations, we can lean on Active Record's automatic pre-loading to prevent them.
**Before**
**After**

Fix N+1 query on AB teachers page

---

app/views/admin/finance/statements/index.html.erb
spec/views/admin/finance/statements/index.html.erb_spec.rb

#713 
Before, the links to statements in the admin finance dashboard weren't helpful for users using assistive technologies (i.e they all said "View").
This updates the links to include some visually hidden content that more clearly communicates the intent of each link to these users.
I've followed the approach suggested in #713.
Closes #713.
Inspect the links to statements on the admin finance page.

Make links to statements more accessible

---

lib/tasks/db.rake

The changes in #871 made things better but not perfect.
This change does the following:
* switch enhancing from `db:test:prepare` to `db:test:purge` - `db:test:prepare` always throws the database away and recreates it, so if the enhancement happens before it's disregarded. `db:test:purge` happens within `db:test:prepare`, before the schema is loaded or migrations run
* simplifies the job by removing the checks for database presence, we're hooking on to events that happen when the database exists so it's unnecessary

Make db test prepare work properly

---

spec/features/appropriate_bodies/process_batch_combo_spec.rb

This test [failed recently in CI][fail] since the events were returned in a different order.
Since we're not explictly ordering the Events when we call `Event.all`, the order isn't guaranteed.
To avoid this, we can use `contain_exactly` instead of `eq`.
[fail]: https://github.com/DFE-Digital/register-early-career-teachers-public/actions/runs/16076939703/job/45374245792?pr=872

Fix flaky test

---

spec/spec_helper.rb

The `FactoryBot::Syntax::Methods` module has been re-included multiple times with good intentions. 
To try and prevent this from happening in future, this comment explains why it's deliberately omitted. Hopefully, this prevents further changes without discussion.

Clarify omission of `FactoryBot::Syntax::Methods`

---

Gemfile
Gemfile.lock
config/initializers/mission_control.rb
config/routes.rb

We want to know more about our background jobs easily. When someone asked "what's happening with OTP", my instinct was to reach for Sidekiq UI (or similar), but we didn't have anything setup.
Mission Control looks to be Rails' take on a basic jobs dashboard, and it supports Solid Queue.
This introduces the [mission control] gem from Rails so that we can use the lightweight dashboard to see more about the status of our background jobs.
I tried to keep the setup straight-forward, so the dashboard is enabled in all environments.
Admins are the only users who can access the dashboard, and they should authenticate in the usual way. This adds some complexity (the default is HTTP basic auth), but I think it's worthwhile in the interests of security.
Closes #1929.
[mission control]: …

Introduce Mission Control

---

config/queue.yml

Worker pod was in a crash loop with `OOMKilled`. MissionControl job failures suggest this is the culprit.
Remove second worker temporarily to mitigate crashes and restore OTP mailing

Revert SolidQueue queue config to a single worker

---

config/queue.yml

In production we're seeing OOMKilled errors on workers when under load.
We suspect that the second worker in the default settings is causing each worker to have half the memory. The migration env currently has 2GB but production only has 1GB (it does far less, for now)
This change gives the migration env a parity-check spec second worker but leaves production with just one multipurpose one.
Note, this follows on from #892 and should restore any functionality removed there.

Add env-specific entries to queue.yml

---

config/terraform/application/config/production.tfvars.json

Following on from #896 bump the web apps from 1Gi to 2Gi too as they're running a bit high.

Update production webapp memory max to 2Gi

---

.github/workflows/restore-snapshot-db-from-azure-storage.yml

They appear as 'Backup' in GitHub actions which looks a bit worrying when they're doing the opposite!

Fix job labels in restore action

---

app/models/concerns/batch_rows.rb
app/services/appropriate_bodies/process_batch/action.rb
app/services/appropriate_bodies/process_batch/base.rb
app/services/appropriate_bodies/process_batch/claim.rb
spec/models/concerns/batch_rows_spec.rb
spec/services/appropriate_bodies/process_batch/action_spec.rb
spec/services/appropriate_bodies/process_batch/claim_spec.rb

Prevalidate rows using logic from `SharedInductionPeriodValidation`
- no future dates
- no start dates before Sept 2021

Add future date and predating ECF rollout checks to bulk journeys

---

app/assets/javascripts/application.js
app/assets/stylesheets/migration/parity_check.scss
app/controllers/migration/parity_checks/responses_controller.rb
app/helpers/parity_check_helper.rb
app/javascript/controllers/index.js
app/javascript/controllers/parity_check/response_body_filter_controller.js
app/migration/parity_check/runner.rb
app/models/parity_check/filter/response_body.rb
app/models/parity_check/response.rb
app/views/migration/parity_checks/responses/_diff.html.erb
app/views/migration/parity_checks/responses/_filter.html.erb
app/views/migration/parity_checks/responses/show.html.erb
config/cable.yml
config/parity_check_endpoints.yml
db/seeds/parity_checks.rb
spec/features/migration/run_parity_check_spec.rb
spec/features/migration/view_parity_check_response_spec.rb
spec/helpers/parity_check_helper_spec.rb
spec/migration/parity_check/runner_spec.rb
spec/models/parity_check/filter/response_body_spec.rb
spec/models/parity_check/response_spec.rb

When we are reviewing diffs in the parity check responses it would be helpful to be able to add/remove fields from the diff in order to better understand the changes.
- Pretty format JSON bodies in Response setters
At the moment, we pretty-format the JSON before saving a `Response`. Going forward, we are going to be updating the response bodies as part of the filter, so its better to format them in the setters.
- Add nested JSON bodies to parity check response seeds
This will allow us to check the diff filtering more easily.
- Add ParityCheck::Filter::ResponseBody model
This model will be used in the form to filter a response body diff by the available JSON keys.
It will accept a `response` and `selected_key_paths` submitted from the form (via checkboxes).
It exposes a …

Allow filtering out attributes from the parity check response diffs

---

spec/features/migration/run_parity_check_spec.rb

This file kept creeping into my commits when it's saved to the root of the app, moving it to the tmp dir means it'll be ignored by git.

Remove the debugging screenshot from parity check spec

---

config/analytics.yml
db/migrate/20250714101747_remove_lead_provider_id_from_ect_at_school_periods.rb
db/schema.rb

Following on from #852, here we make the database changes to drop `lead_provider_id` from `ECTAtSchoolPeriod`.
- Check that everything that references the `lead_provider_id` on `ECTAtSchoolPeriod` been removed from the codebase.
- Check that everything still works as it did before.

[1705] Remove `lead_provider_id` from `ECTAtSchoolPeriod` (db change)

---

config/terraform/application/config/production.tfvars.json

RECT gets scanned and although we added rate limiting 1 pod is not coping with the load and the app is getting downtime
Bump pods to 2 for both workers and web app incase for contingency, we might need more later, after monitoring
Will keep monitoring

Bump workers and web apps to at least 2 pods

---

app/controllers/migration/teacher_failures_controller.rb

In migration, the list of teachers with failures contains duplicates because of the joins to failure records, so adding a `distinct` clause to the query so that the list of teachers and the count of teachers with the failure is correct.
Add distinct clause to query

Make teacher failure query a distinct list of teachers in Migration env

---

app/models/contract_period.rb
app/wizards/schools/register_ect_wizard/ect.rb
app/wizards/schools/register_ect_wizard/start_date_step.rb
lib/schools/validation/ect_start_date.rb
lib/schools/validation/hash_date.rb
spec/lib/schools/validation/ect_start_date_spec.rb
spec/models/contract_period_spec.rb
spec/wizards/schools/register_ect_wizard/start_date_step_spec.rb

We are adding two new validation checks for the start date when registering an ECT. 
I considered extracting the previous registration logic into a `ECTRegistrationHistory` service object. However the existing methods in the ECT wrapper already provided the neccssary functionality.  Also a lack of a `Teacher` at times during the wizard flow would have added complexity so I decided against it in the end but happy to revisit if others feel strongly.

[1502] Add extra validation checks for start date when registering an ECT

---

config/analytics.yml
config/analytics_blocklist.yml

This data won't be present until the main Register ECTs service goes live next year, so blocking for now.
Also tidied up a few trailing bits of whitespace while I was there.

Move `ECTAtSchoolPeriod` fields to the blocklist (for now)

---

documentation/policy/induction-for-early-career-teachers.adoc

Here my matching for paragraph numbers added links to decimal term values, so 2.5 terms linked to section 2 paragraph 5 🙈
Easiest to see in word diff mode `git log -n1 --patch --word-diff`

Fix bad terms links in the service manual

---

spec/factories/migration/delivery_partner_factory.rb
spec/migration/migrators/delivery_partner_spec.rb

A flaky spec was spotted related to duplicate names (assume a small pool in `Faker`) so moved to a name with a sequence number:
```
1) Migrators::LeadProviderDeliveryPartnership behaves like a migrator .prepare! when there are enough models for two workers creates two pending data migrations
Failure/Error: FactoryBot.create(:delivery_partner, name: dp.name, api_id: dp.id)
ActiveRecord::RecordInvalid:
Validation failed: Name has already been taken
Shared Example Group: "a migrator" called from ./spec/migration/migrators/lead_provider_delivery_partnership_spec.rb:2
Finished in 2 minutes 38.9 seconds (files took 9.28 seconds to load)
4262 examples, 1 failure, 11 pending
Failed examples:
rspec ./spec/migration/migrators/lead_provider_delivery_partnership_spec.rb[1:1:1:2:1] # …
```

Fix flaky spec for `LeadProviderDeliveryPartnership`

---

app/assets/javascripts/application.js
app/assets/stylesheets/migration/parity_check.scss
app/controllers/migration/parity_checks/responses_controller.rb
app/helpers/parity_check_helper.rb
app/javascript/controllers/index.js
app/javascript/controllers/parity_check/response_body_filter_controller.js
app/migration/parity_check/runner.rb
app/models/parity_check/filter/response_body.rb
app/models/parity_check/response.rb
app/views/layouts/shared/_head.html.erb
app/views/migration/parity_checks/responses/_diff.html.erb
app/views/migration/parity_checks/responses/_filter.html.erb
app/views/migration/parity_checks/responses/show.html.erb
config/cable.yml
config/parity_check_endpoints.yml
db/seeds/parity_checks.rb
spec/features/migration/run_parity_check_spec.rb
spec/features/migration/view_parity_check_response_spec.rb
spec/helpers/parity_check_helper_spec.rb
spec/migration/parity_check/runner_spec.rb
spec/models/parity_check/filter/response_body_spec.rb
spec/models/parity_check/response_spec.rb

This pr reverts the revert of https://github.com/DFE-Digital/register-early-career-teachers-public/pull/863 by @ethax-ross where the original description is:
When we are reviewing diffs in the parity check responses it would be helpful to be able to add/remove fields from the diff in order to better understand the changes.
- Pretty format JSON bodies in Response setters
At the moment, we pretty-format the JSON before saving a `Response`. Going forward, we are going to be updating the response bodies as part of the filter, so its better to format them in the setters.
- Add nested JSON bodies to parity check response seeds
This will allow us to check the diff filtering more easily.
- Add ParityCheck::Filter::ResponseBody model
This model will be used in the form to filter a response body …

Reverted: Allow filtering out attributes from the parity check response diffs

---

config/terraform/application/config/sandbox.tfvars.json

We are getting scraped and with 1 web app pod there is downtime
Bump sandbox to 2 web apps and 2 workers to avoid any issues especially since providers will be testing, we'll probably need more then

Bump sandbox to 2 web/workers apps

---

app/components/schools/ects/listing_card_component.html.erb
app/components/schools/ects/listing_card_component.rb
app/helpers/ect_helper.rb
app/models/training_period.rb
app/services/ect_at_school_periods/training.rb
spec/components/schools/ects/listing_card_component_spec.rb
spec/factories/ect_at_school_period_factory.rb
spec/services/ect_at_school_periods/training_spec.rb

If there is no confirmed partnership (`school_partnership`), but there is an expression of interest (EOI), we want to surface that. On the ECT index page:
- The **lead provider** section should display the name from the EOI.
- The **delivery partner** section should show fallback text: *"Their lead provider will confirm this."*
- Show EOI lead provider name if the most recent training period has an EOI but no `school_partnership`
- Show fallback text in the delivery partner section in this scenario
- Add `only_expression_of_interest?` method to `TrainingPeriod` to capture this logic
- Add `with_eoi_only_training_period` trait to the ECT factory (creates a `training_period` with no `school_partnership`, but with an EOI)
- When a confirmed `school_partnership` exists, show lead provider and …

[1696] Show EOI lead provider if no confirmed partnership

---

config/terraform/domains/environment_domains/config/staging.tfvars.json

We are being scraped and added rate limits to different environments. However we went to 2000 in sandbox/production as our rate limit for the API is 1000/5 minutes. However for staging we don't need that limit
We aren't serving the API to providers from staging, and being scraped quite heavily. Instead of scaling up staging we can safely raise the rate limit.
We should stop seeing downtime/restarts in staging hopefully.

Raise rate limit for staging

---

app/services/contract_periods/for_ect.rb
spec/services/contract_periods/for_ect_spec.rb

Implementing a service object for identifying the contract period for a given ECT
This uses the `started_on` date from the `ECTAtSchoolPeriod` to identify the correct `ContractPeriod` for the ECT. If no match is found, it falls back to the `created_at` timestamp, which acts as the registration date.
We use the `ContractPeriod.ongoing_on(date)` scope, which checks whether a given date falls within a contract periods date range. This range is calculated by a virtual column (range) using`started_on..finished_on`.

[1940] Implement SO for identifying the contract period for a given ECT

---

app/components/teachers_index/header_section_component.rb
config/routes.rb
spec/components/teachers_index/header_section_component_spec.rb

Make the URLs friendlier by matching params
- Update routes for filtering open/closed teacher inductions as an AB
- Simplify component testing
- `/appropriate-body/teachers?status=closed` becomes `/appropriate-body/teachers/closed`
- add corresponding `/appropriate-body/teachers/open` which is the default view of `/appropriate-body/teachers`

AB teacher search URLs

---

config/terraform/application/config/migration.yml

When running the parity check on the migration environment we get 302s instead of getting responses. This is because the API isn't enabled
Enable API in migration env

Enable Lead provider API in migration

---

app/migration/school_mentors_to_school_periods.rb
app/migration/school_period_extractor.rb
app/models/migration/school_period.rb
spec/factories/migration/school_period_factory.rb

Ticket: https://github.com/DFE-Digital/register-ects-project-board/issues/1994
The MentorAtSchoolPeriod migrator instantiates Migration::SchoolPeriod without passing `training_programme` and `lead_provider_id`, triggering a missing keywords error that breaks MentorAtSchoolPeriod creation and affects dependent records.
The `lead_provider_id` however is no longer stored on school periods, so the attribute is now redundant and can be removed.
- Pass the missing argument `training_programme` when creating the Migration::SchoolPeriod objects
- Remove the redundant `lead_provider_id` attribute from the Migration::SchoolPeriod class and factory
- Remove the redundant `discover_lead_provider_id` method from the SchoolPeriodExtractor

Ensure required attributes are set when creating a Migration::SchoolPeriod

---

app/models/migration/induction_record.rb
app/services/migration/analyse_induction_sequences.rb
app/services/migration/induction_sequence_analyser.rb
app/services/migration/induction_sequence_exporter.rb
app/services/migration/induction_sequence_formatter.rb
spec/models/migration/induction_record_spec.rb

Ticket: https://github.com/DFE-Digital/register-ects-project-board/issues/1269
This PR adds functionality to analyze participants' induction records grouped by lead providers, to identify timeline gaps, overlaps, and data quality issues in ECF participant induction records that we will need to migrate over.
- Add service class to orchestrate the analysis
- Add class to export the results in csv
- Add class to print the results
- Add model associations to `Migration::InductionRecord` required for the analysis
1. Get a list of participants you want to analyse i.e. participants with multiple induction records with blank end dates
```
participant_profiles = ::Migration::ParticipantProfile.joins(:induction_records).where(induction_records: { end_date: nil …
```

Add induction records analysis

---

app/components/teachers/details/past_induction_periods_component.html.erb
app/components/teachers/details/past_induction_periods_component.rb
spec/components/teachers/details/past_induction_periods_component_spec.rb

As highlighted by Avin in #936, we can simplify the logic for rendering action links in the summary list.
This refactors the component and adds some tests for when editing is enabled and when it isn't.

Simplify `Teachers::Details::PastInductionPeriodsComponent`

---

app/services/events/describe_modifications.rb
app/services/events/record.rb
app/services/events/transition_description.rb
db/scripts/fix_event_headings_with_empty_strings.rb
spec/features/appropriate_bodies/process_batch_combo_spec.rb
spec/services/events/transition_description_spec.rb

#761 
Before, we described event modifications one way, but described some event headings another way.
At first we thought this was due to a bug #761, but in fact it was a consequence of this inconsistency.
This introduces an `Events::TransitionDescription` service that returns a human-readable description of an event transition. It gracefully handles blank values like the existing code, as well as handling some extra edge cases.
Now, we can use this to describe event modifications and for event headings when reporting events. Event timelines should now be clearer in all circumstances!
- Record some teacher name change and induction status change events
- Look at the timeline!

Describe event transitions consistently

---

config/initializers/sentry.rb

In #981, I missed the `.rails`.
We didn't catch it because Sentry is disabled in review apps, but it blew up on Staging.
This fixes things.
Verified locally with `ENABLE_SENTRY=true bin/dev` before/after the change.

Fix Sentry config

---

app/assets/stylesheets/api_guidance.scss
app/controllers/api/guidance_controller.rb
app/views/api/guidance/release_notes.html.erb
app/views/api/guidance/show.html.erb
app/views/layouts/api_guidance.html.erb

Release notes `<code>` style/css is overriding css on swagger docs.
- Restrict `<code>` style/css to release notes page only.
[Review app docs](https://cpd-ec2-review-996-web.test.teacherservices.cloud/api/docs/v3#/Statements/get_api_v3_statements)
[Review app release notes](https://cpd-ec2-review-996-web.test.teacherservices.cloud/api/guidance/release-notes)
Before:
After:

Fix code block style bug on swagger docs

---

app/services/schools/query.rb
app/services/schools/training_programme.rb
spec/services/schools/query_spec.rb
spec/services/schools/training_programme_spec.rb

We're moving the `training_programme` field from `ECTAtSchoolPeriod` to `TrainingPeriod` bit by bit.
#982 added the `training_programme` field to `TrainingPeriod` and this change updates the school queries so they use it instead of the one on `ECTAtSchoolPeriod`.
Thankfully it was quite minimal as the query objects had joined the relevant tables already.
Refs DFE-Digital/register-ects-project-board#2013

Update school queries to use the training programme from training periods

---

config/routes.rb
spec/features/schools/ects/register/edge_cases/teacher_at_school_already_registered_spec.rb

https://github.com/DFE-Digital/register-early-career-teachers-public/issues/556
This path was the only route_with_underscores in the wizard.
Now it-has-dashes-like-the-others.
Closes #556

Use dashes in Register ECT wizard

---

app/controllers/migration/parity_checks/requests_controller.rb
app/controllers/migration/parity_checks_controller.rb
app/migration/parity_check/dynamic_request_content.rb
app/migration/parity_check/runner.rb
app/migration/parity_check/token_provider.rb
app/models/parity_check/response.rb
app/views/migration/parity_checks/new.html.erb
config/parity_check_endpoints.yml
spec/features/migration/run_parity_check_spec.rb
spec/features/migration/view_parity_check_request_spec.rb
spec/migration/parity_check/dynamic_request_content_spec.rb
spec/migration/parity_check/runner_spec.rb
spec/migration/parity_check/token_provider_spec.rb
spec/models/parity_check/response_spec.rb

Now that we have the schools endpoint setup in RECT we want to run the parity check against them to determine if we have parity with ECF.
- Ensure lead providers are present and have an ecf_id
This is just a small housekeeping update to avoid running into a silent failure when trying to run the parity check when there are no lead providers that have an `ecf_id` (it would hang/fail trying to get tokens).
Prevent running the migrator until there are valid lead providers present.
Only queue requests for lead providers with an `ecf_id`.
- Display parity check responses in page order
When we have multiple pages of responses its helpful to view them in page order.
- Add schools endpoints to parity check
Include the schools endpoints in the parity check; this includes all the filters applied …

Add school endpoints to the parity check

---

app/migration/builders/gias/school.rb
app/migration/migrators/school.rb
app/models/migration/school.rb
app/services/gias/school_row.rb
spec/migration/builders/gias/school_spec.rb
spec/migration/migrators/school_spec.rb

[Issue](https://github.com/DFE-Digital/register-ects-project-board/issues/2015)
We are importing only open schools from GIAS into RECT.
Similarly, we are comparing only open schools on ECF1 with those in RECT.
However, some closed schools still registered have school partnerships defined.
As those partnerships will need to be migrated into RECT, we need their schools to be migrated as well.
Extend the schools comparision migrator to migrate these school to RECT.

[2015] - Migrate closed schools on ECF1 with induction records

---

.rubocop.yml
public/api/docs/v3/swagger.yaml
spec/requests/api/docs/v3/schools_spec.rb
spec/requests/api/docs/v3/statements_spec.rb
spec/support/shared_contexts/api/docs/api_index_endpoint_documentation_support.rb
spec/support/shared_contexts/api/docs/api_show_endpoint_documentation_support.rb
spec/support/shared_contexts/api_doc_request_auth.rb
spec/swagger_helper.rb
spec/swagger_schemas/concerns/sorting.rb
spec/swagger_schemas/filters/school.rb
spec/swagger_schemas/filters/schools.rb
spec/swagger_schemas/models/school.rb
spec/swagger_schemas/responses/school.rb
spec/swagger_schemas/responses/schools.rb

Ticket: https://github.com/DFE-Digital/register-ects-project-board/issues/1785
This is to set up Swagger documentation for schools, initial swagger set up was done as part of statements
- Add schools endpoints to swagger docs
[Review app swagger docs](https://cpd-ec2-review-997-web.test.teacherservices.cloud/api/docs/v3)

[1785] Add schools endpoints to swagger docs

---

.github/dependabot.yml

Reverting  DFE-Digital/register-early-career-teachers-public#1006. 
The behaviour of `multi-ecosystem-groups` was a bit unexpected and It doesn't guarantee version sync between dependencies, so we're better off relying on CI to catch mismatches for now.
Can revisit with a custom github action if it becomes a pain.

Revert "Group Ruby and JS Playwright updates"

---

app/views/schools/register_ect_wizard/_use_previous_ect_choices.html.erb
app/views/schools/register_ect_wizard/check_answers.html.erb
app/wizards/schools/register_ect_wizard/ect.rb
spec/factories/ect_at_school_period_factory.rb
spec/features/schools/ects/register/happy_path_spec.rb
spec/views/schools/register_ect_wizard/check_answers.html.erb_spec.rb
spec/views/schools/register_ect_wizard/shared_examples/use_previous_ect_choices_view.rb
spec/wizards/schools/register_ect_wizard/ect_spec.rb

This PR introduces support for the "rollover" concept from ECF1, where schools can reuse previously selected training programme choices (e.g. lead provider and delivery partner) when registering a new ECT - but only when those choices are still valid for the current contract period.
- **Check Your Answers (CYA) Logic**  
- The Delivery Partner row now appears on the CYA page **only if**:
- `use_previous_ect_choices` is `true`, and
- there is a confirmed school partnership between the previous lead provider and the school for the relevant contract period.
- This ensures we only show delivery partner info when it reflects an actual partnership.
- **Use Previous Choices View**
- Now conditionally shows the lead provider and delivery partner from the previous ECT if a confirmed partnership …

[1441] Allow schools to re use lead provider and delivery partner choices for a new ECT where possible

---

app/components/shared/top_search_component.rb

Use `secondary: true` on govuk_submit instead of the class.
See: https://github.com/x-govuk/govuk-form-builder/blob/main/lib/govuk_design_system_formbuilder/builder.rb#L912-L914

[xxxx] Use secondary true on `govuk_submit`

---

app/serializers/delivery_partner_serializer.rb
app/services/delivery_partners/query.rb
spec/serializers/delivery_partner_serializer_spec.rb
spec/services/delivery_partners/query_spec.rb

As part of the delivery partners epic we want to add the query service that can be called from the controller. This should mimic the behaviour of the delivery partners query service in ECF.
- Add DeliveryPartners::Query
Add a query service for retrieving delivery partners, which will be called from the controller. The results will be passed into the `DeliveryPartnerSerializer`.
We calculate a `transient_cohort` in the query service for efficiency and fallback to looking it up from sratch if its not present. This will be replaced in the future by a pre-calculated field.

Add `DeliveryPartners::Query` service

---

app/models/concerns/interval.rb
app/services/teachers/search.rb
db/seeds/lead_provider_delivery_partnerships.rb
db/seeds/school_partnerships.rb
db/seeds/teacher_histories.rb
db/seeds/teachers.rb
spec/factories/ect_at_school_period_factory.rb
spec/models/concerns/interval_spec.rb
spec/services/teachers/search_spec.rb

Update the schools ECT index so future joiners are listed too.
To support this there are a few new scopes that are relative to the current date, and a new person in the seed data who has a future joining date so we can see how things look in review apps.
* Add new scopes so we can search for current **or** future teachers
* Update `Teachers::Search#ect_at_school` so it searches for `ECTAtSchoolPeriod` records that are either currently ongoing or start in the future
* Add seed data so this kind of teacher can be previewed
| Searching for teacher who hasn't started yet | Seed data with appropriate description |
| ------ | ------ |
| <img width="1033" height="511" alt="image" src="https://github.com/user-attachments/assets/17647657-17e9-479b-b0e7-20dbeff0f846" /> | <img width="912" …

Show future ECTs in the school list

---

app/components/teachers_index/search_section_component.html.erb
app/views/admin/finance/adjustments/edit.html.erb
app/views/admin/finance/adjustments/new.html.erb
app/views/admin/induction_periods/new.html.erb
app/views/personas/index.html.erb
spec/components/teachers_index/search_section_component_spec.rb
spec/features/admin/teachers/add_induction_period_spec.rb

Rather than adding `govuk-button` classes manually, we can use the `govuk_submit` form element from the Form Builder.
In an ideal world, we might introduce a Cop for this and integrate it with a tool like `erblint`, but that's a problem for another day!
Inspired by #1051

Always use `govuk_submit` in forms

---

app/migration/migrators/school.rb
spec/migration/migrators/school_spec.rb

[Issue](https://github.com/DFE-Digital/register-ects-project-board/issues/2014)
We are importing only open schools from GIAS into RECT. 
Similarly, we are comparing only open, eligible or cip_only schools on ECF1 with those in RECT.
However, other open schools have school partnerships associated.
As those partnerships will need to be migrated into RECT, we need their schools to be migrated as well.
Extend the schools comparison migrator to migrate these school to RECT.

[2014] - Migrate ECF open schools with partnerships when they are missing on RECT

---

app/controllers/api/v3/delivery_partners_controller.rb
app/models/lead_provider_delivery_partnership.rb
app/serializers/delivery_partner_serializer.rb
app/services/delivery_partners/query.rb
app/services/queries/condition_formats.rb
config/routes.rb
spec/models/lead_provider_delivery_partnership_spec.rb
spec/requests/api/v3/delivery_partners_spec.rb
spec/serializers/delivery_partner_serializer_spec.rb
spec/services/delivery_partners/query_spec.rb
spec/services/queries/condition_formats_spec.rb
spec/support/shared_contexts/api/filterable_endpoint.rb
spec/support/shared_contexts/api/index_endpoint.rb
spec/support/shared_contexts/api/show_endpoint.rb

Now that we have the query and serializer in place, we can flesh out the `index` and `show` actions of the delivery partner APIs.
- Ignore non-integer cohorts in DeliveryPartners::Query
At the moment it will throw a postgres error when filtering on non-integer contract period values.
Add `integers:` option to `ConditionFormats` so that we can restrict the input.
- Add lead_provider relationship for convenience
To make it a bit cleaner to reference the active lead provider of a delivery partnership.
- Cast serialized cohorts to strings
To be consistent with the lead provider API and the behaviour of the transient cohort logic, we want to cast the cohorts to strings.
- Implement index and show actions for delivery partners
Integrate the query and serializer to flesh out the delivery partner …

Add delivery partner APIs

---

app/services/teachers/full_name_parser.rb
spec/services/teachers/full_name_parser_spec.rb

Occasionally we have a failing spec like this:
```
1) Migrators::Teacher behaves like a migrator #migrate! creates a Teacher records for each ECF TeacherProfile
Failure/Error: expect(Teachers::Name.new(teacher).full_name).to eq user.full_name
expected: "Missy Sippy"
got: "y Sippy"
```
It's because the full name parser strips 'Miss' from the first name (to protect against occasions where a user has accidentally included the title in their first name field).
Some names, e.g., Missy, start with a title. Now the matcher looks for a space after the title.

Fix bug where names starting with titles are stripped

---

app/components/navigation/primary_navigation_component.rb
app/views/admin/appropriate_bodies/index.html.erb
app/views/admin/bulk/batches/index.html.erb
spec/components/navigation/primary_navigation_component_spec.rb
spec/views/admin/appropriate_bodies/index.html.erb_spec.rb

https://github.com/DFE-Digital/register-ects-project-board/issues/2080
In testing, Admin users could navigate to the bulk uploads page via the service navigation menu.
This was always a temporary decision.
Now we've found a permanent home for it, we can move it!
This moves the link to navigate to bulk uploads to the appropriate bodies page.

Move bulk uploads to appropriate bodies page

---

app/models/appropriate_body.rb
app/views/admin/appropriate_bodies/show.html.erb
config/analytics.yml
db/migrate/20250724140228_remove_redundant_appropriate_bodies_columns.rb
db/schema.rb
db/seeds/appropriate_bodies.rb
documentation/domain-model.md
spec/factories/appropriate_body_factory.rb
spec/models/appropriate_body_spec.rb

https://github.com/DFE-Digital/register-early-career-teachers-public/issues/941
We're not using this data anywhere (we just imported it from DQT as a starting point).
This removes it in the interests of maintenance!
~~- [ ] Data pipelines not borked!~~ We're leaving `dqt_id` since the analytics team are still using it to associate historical induction periods to appropriate bodies

Remove redundant columns from appropriate bodies

---

public/api/docs/v3/swagger.yaml
spec/requests/api/docs/v3/delivery_partners_spec.rb
spec/requests/api/docs/v3/schools_spec.rb
spec/support/shared_contexts/api/docs/api_index_endpoint_documentation_support.rb
spec/swagger_helper.rb
spec/swagger_schemas/filters/delivery_partners.rb
spec/swagger_schemas/filters/sort_order.rb
spec/swagger_schemas/models/delivery_partner.rb
spec/swagger_schemas/responses/delivery_partner.rb
spec/swagger_schemas/responses/delivery_partners.rb
spec/swagger_schemas/sorting/timestamps.rb

We want to add the delivery partner swagger documentation to support the APIs recently added.
- Add delivery partners swagger documentation
Add request/docs spec for delivery partners `index` and `show` actions.
Add schemas for delivery partners.
Move `SortOptions` schema out of `concerns` and into `filters`.
Update schools specs to use `sorting_schema_ref` instead of `default_sortable`.
- Move and rename sorting schema
To avoid confusion and allow other sorting schemas this is moving to the `sorting` directory and renamed to `SortingTimestamps` so its clearer what its doing.
[Link to swagger docs](https://cpd-ec2-review-1059-web.test.teacherservices.cloud/api/docs/v3)

Add delivery partner swagger docs

---

app/migration/parity_check/request_builder.rb
config/parity_check_endpoints.yml
spec/migration/parity_check/request_builder_spec.rb

On some of the new RECT endpoints we are omitting `ecf` from the path of the endpoint (schools, for example). This means we need to call different endpoints depending on the application.
- Add support for different parity check URLs
Add support to parity check endpoint options for `ecf_url` or `rect_url` - this will be used with preference over the default URL provided as the key to the check.
[Example run](https://cpd-ec2-migration-web.teacherservices.cloud/migration/parity-checks/8)

Add support for different parity check URLs

---

app/migration/induction_record_sanitizer.rb
app/migration/migrators/ect_at_school_period.rb
app/migration/migrators/mentor_at_school_period.rb
app/migration/school_period_extractor.rb
spec/migration/induction_record_sanitizer_spec.rb

In an attempt to fix some migration errors I've added the ability to validate induction records by group. The group can be by `:school` or `:provider`.  This will segregate the induction records into those groups and perform the validations on each group individually.  This appears to help fix a number of issues with interleaved timelines (e.g. retrospective provider updates) but has only been tested with real data for `ECTAtSchoolPeriod` migrations. This resulted in ~10x reduction in errors raised.  In addition we decided to skip checks regarding to end dates, at least for school periods, because we can focus on when a participant started at a school and any subsequent starts at different schools would close the previous period.  This no doubt has had a big contribution in the reduction …

Grouping induction records for validation

---

app/components/schools/ects/listing_card_component.html.erb
app/components/schools/ects/listing_card_component.rb
app/controllers/schools/ects_controller.rb
app/models/ect_at_school_period.rb
app/models/teacher.rb
app/views/schools/ects/index.html.erb
db/seeds/teacher_histories.rb
spec/components/schools/ects/listing_card_component_spec.rb
spec/factories/training_period_factory.rb
spec/models/ect_at_school_period_spec.rb
spec/models/teacher_spec.rb
spec/views/schools/ects/index.html.erb_spec.rb

The `Schools::ECTs::ListingCardComponent` currently recives one object, an `ECTAtSchoolPeriod` when being initialised and then uses `ECTatSchoolPeriods::Training` to determine the training information. This made sense when we weren't concerned about future periods but now we need to take that into consideration.
To hopefully simplify things, there are now `has_one` relationships that retrieve the `current_ect_at_school_period` from the `Teacher`, and the `current_training_period` from the `ECTatSchoolPeriod`.
This means we can pass into the listing component all of the objects we will need, and use them directly.
The moving of `training_programme` from `ECTAtSchoolPeriod` to `TrainingPeriod` means there's a chance we'll have teachers who are neither `school-led` or `provider-led`. We'll …

Rework listing card component to accept teacher and training period

---

app/controllers/api/v3/schools_controller.rb
app/controllers/api/v3/statements_controller.rb
spec/requests/api/v3/delivery_partners_spec.rb
spec/requests/api/v3/schools_spec.rb
spec/requests/api/v3/statements_spec.rb
spec/support/shared_contexts/api/filterable_endpoint.rb

Currently the filtering will also be applied to the `show` action; we don't allow/document this, so we want to restrict filtering to the `index` endpoint only.
- Only support filtering on `index` actions
Restrict the query conditions so that filters only get passed in on `index` actions (apart from filtering on `contract_period_id` for the schools `show` action as we allow this).

Only support filtering on `index` actions

---

spec/lib/tasks/mermaid_erd_spec.rb

Since the test stubs `Rails.env` to development and invokes the `erd:generate` task, the success message is printed to stdout, which is noisy in CI.
Use an `expect { ... }.to output(...).to_stdout` block to capture and assert the message instead, keeping CI logs clean while verifying the behaviour.

Capture ERD rake task output in test instead of printing to shell

---

Gemfile
app/services/sandbox_seed_data/base.rb
app/services/sandbox_seed_data/delivery_partners.rb
app/services/sandbox_seed_data/helpers/school_urn_generator.rb
app/services/sandbox_seed_data/school_partnerships.rb
app/services/sandbox_seed_data/schools.rb
lib/tasks/sandbox_seed_data.rake
spec/factories/delivery_partner_factory.rb
spec/factories/gias/school_factory.rb
spec/services/sandbox_seed_data/delivery_partners_spec.rb
spec/services/sandbox_seed_data/helpers/school_urn_generator_spec.rb
spec/services/sandbox_seed_data/school_partnerships_spec.rb
spec/services/sandbox_seed_data/schools_spec.rb

Ticket: https://github.com/DFE-Digital/register-ects-project-board/issues/1808
LPs need to be able to view schools on the GET Schools endpoint in sandbox env.
- Add schools generator to the existing sandbox seeds generator task;
- Some schools will get partnerships created;
- Fetch branch locally (`git fetch`)
- Checkout to the branch (`git checkout 1808-add-schools-to-sandbox-seeds`)
- Run rake task:
- `bundle exec rake sandbox_seed_data:generate`
- Check new schools in admin dashboard

[1808] Add schools to sandbox seeds generator task

---

spec/components/appropriate_bodies/claim_ect_actions_component_spec.rb
spec/components/teachers/details/induction_outcome_actions_component_spec.rb
spec/components/teachers_index_component_spec.rb
spec/requests/admin/induction_periods_spec.rb
spec/requests/appropriate_bodies/claim_an_ect/find_ect_spec.rb
spec/requests/appropriate_bodies/induction_periods_spec.rb
spec/services/appropriate_bodies/claim_an_ect/find_ect_spec.rb
spec/services/schools/eligible_mentors_spec.rb
spec/services/teachers/induction_period_spec.rb
spec/services/teachers/induction_spec.rb
spec/wizards/schools/register_ect_wizard/find_ect_step_spec.rb
spec/wizards/schools/register_mentor_wizard/find_mentor_step_spec.rb
spec/wizards/schools/register_mentor_wizard/mentor_spec.rb
spec/wizards/schools/register_mentor_wizard/national_insurance_number_step_spec.rb
spec/wizards/schools/register_mentor_wizard/wizard_spec.rb

Following on from feedback in #1083, this updates some of the language used to describe ongoing periods in tests (from "active").

Update ongoing period variable names in tests

---

config/queue.yml
config/terraform/application/config/migration.tfvars.json

We need to bump resources for migration to try to see if we can run things faster
- Lower processes and threads on the migration queues: We don't want too many jobs running on a pod, limit this to 2 jobs (threads) per process, so 2 jobs per pod for migration queue
- Bump web/worker memory and pods on migration: This makes sure that we don't lose out on jobs running but we're giving them more memory. Web apps bump is for parity checks
I'll bump db resources later in the week

Bump migration resources

---

app/components/admin/statements/filter_component.html.erb
app/components/admin/statements/filter_component.rb
app/components/admin/statements/selector_component.html.erb
app/components/admin/statements/selector_component.rb
app/controllers/admin/finance/statements_controller.rb
app/migration/builders/ect/training_periods.rb
app/migration/builders/mentor/training_periods.rb
app/migration/migrators/active_lead_provider.rb
app/migration/migrators/base.rb
app/migration/migrators/lead_provider_delivery_partnership.rb
app/migration/migrators/statement.rb
app/models/active_lead_provider.rb
app/models/school.rb
app/serializers/delivery_partner_serializer.rb
app/serializers/school_serializer.rb
app/services/delivery_partners/query.rb
app/services/lead_providers/active.rb
app/services/sandbox_seed_data/delivery_partners.rb
app/services/schools/training_programme.rb
config/analytics_blocklist.yml
db/migrate/20250806082156_rename_contract_period_id_to_year.rb
db/schema.rb
spec/components/admin/statements/filter_component_spec.rb
spec/components/admin/statements/selector_component_spec.rb
spec/migration/migrators/active_lead_provider_spec.rb
spec/migration/migrators/school_partnership_spec.rb
spec/models/active_lead_provider_spec.rb
spec/models/school_spec.rb
spec/services/schools/query_spec.rb
spec/services/schools/training_programme_spec.rb

The primary key of `contract_periods` is called `year` rather than ID, as there is one per year and we don't need to generate them using a sequence.
The foreign key from `active_lead_providers` was called `contract_period_id`, which is confusing. It should be `contract_period_year`.
This PR makes the change in the database, model and switches all references to `contract_period_id` to `contract_period_year`.

Rename `contract_period_id` to `contract_period_year`

---

db/migrate/20250806082156_rename_contract_period_id_to_year.rb

I accidentally broke the migration in my last PR while doing a subsequent find and replace. This should fix it, it was renaming the column to itself 🫣

Fix incorrect migration

---

config/terraform/application/config/sandbox.tfvars.json

We bumped the pods but we need to also bump memory
Bump worker memory as its hovering at 96%, bumping web as well just because this is provider facing for testing
keep on monitoring

Bump memory for sandbox as its alerting

---

app/migration/parity_check/dynamic_request_content.rb
app/migration/parity_check/request_builder.rb
app/models/parity_check/filter/response_body.rb
config/parity_check_endpoints.yml
spec/migration/parity_check/dynamic_request_content_spec.rb
spec/migration/parity_check/request_builder_spec.rb
spec/models/parity_check/filter/response_body_spec.rb

We want to run the delivery partner APIs on the parity check now that they are complete to find any differences/issues.
- Add delivery partner API requests to the parity check.
Update `DynamicRequestContent` to retrieve a `delivery_partner_id`.
- Support response bodies with arrays of values
Currently we expect all arrays to contain objects (which can be mapped into a hash). When we return `cohort` for delivery partners, however, it is an array of strings and trips up the `ParityCheck::Filter::ResponseBody` logic.
Ignore nested items in the key hash mapping unless they are also a hash.
[Run in migration](https://cpd-ec2-migration-web.teacherservices.cloud/migration/parity-checks/31)
From the most part it looks like the updated_at/created_at are different and a handful of `cohort` entries …

Add delivery partners APIs to parity check

---

app/migration/parity_check/dynamic_request_content.rb

I think this got lost in the big refactor PR yesterday; the tests are failing on `main` now.

Fix query attribute on `DyanmicRequestContent`

---

app/migration/migrators/base.rb
config/queue.yml
config/terraform/application/config/migration.tfvars.json

We noticed that the "*" and "migration" was including migration jobs and creating 3 threads per process, which hammered the db with 20 workers.
Remove "migration" and "*" from the queue so it respects 1 thread 1 process.
Bump record number to 3000 and drop workers to see if this helps with the speed of the migration

Amend Migration queues

---

app/views/layouts/api_guidance.html.erb

Ticket: https://github.com/DFE-Digital/register-ects-project-board/issues/2133
Swagger docs page is not loading properly after clicking on `Swagger documentation` link from the guidance page.
- Add missing data-turbo attribute to the guidance template.
[Review app](https://cpd-ec2-review-1110-web.test.teacherservices.cloud/api/guidance/swagger-api-documentation)

[2133] Add missing data-turbo attribute

---

app/services/appropriate_bodies/process_batch/action.rb
app/services/appropriate_bodies/process_batch/claim.rb
spec/services/appropriate_bodies/process_batch/action_spec.rb
spec/services/appropriate_bodies/process_batch/claim_spec.rb

Replace
- `#{name} is already claimed by another appropriate body`
- `#{name} is completing their induction with another appropriate body`
With 
- `#{name} is already claimed by another appropriate body (#{ab.name})`
- `#{name} is completing their induction with another appropriate body (#{ab.name})`

Use AB name in error messages when validating claims and outcomes

---

app/services/appropriate_bodies/process_batch/action.rb
spec/services/appropriate_bodies/process_batch/action_spec.rb

Replace 
- `#{name} has already completed their induction`
With 
- `#{name} has already passed their induction`
- `#{name} has already failed their induction`

Bulk passed/failed errors

---

app/models/school.rb
app/serializers/school_serializer.rb
app/services/metadata/handlers/school.rb
app/services/metadata/manager.rb
app/services/metadata/resolver.rb
spec/models/school_spec.rb
spec/services/metadata/handlers/school_spec.rb
spec/services/metadata/manager_spec.rb
spec/services/metadata/resolver_spec.rb

Now that we have metadata models for `SchoolContractPeriod` and `SchoolLeadProviderContractPeriod` we want to implement the core service for managing the refreshing of metadata, starting with schools.
- Add metadata service and school handler
Add the foundations for the metadata service, consisting of:
- `Metadata::Manager`
- `Metadata::Resolver`
- `Metadata::Handlers`
Add the `Metadata::Handlers::School` handler that will refresh school metadata for both `SchoolContractPeriod` and `SchoolLeadProviderContractPeriod`.
Testing this on migration to do a full sync of schools would be ~3 hours. I think performance-wise its probably OK for small/individual updates, but I'm going to look at optimising batch updates as part of [this ticket](https://github.com/DFE-Digital/register-ects-project-boar …

Add metadata service and school handler

---

app/models/gias/school.rb
db/migrate/20250811143143_allow_null_establishment_number_in_gias_schools.rb
db/schema.rb
spec/models/gias/school_spec.rb

Ticket: https://github.com/DFE-Digital/register-ects-project-board/issues/2207
With the inclusion of type 47 schools the `GIAS::Importer` is failing because not all of these have an `establishment_number` which is required in the RECT schema.
As we want these schools included we should relax the requirement for the `establishment_number` on the `GIAS::School` record. This was never imported in ECF and is not currently used in RECT.
- Update the validation for the establishment_number to allow `nil` values
- Remove the `null: false` restriction from the schema
Trigger the gias import with ```bin/rails gias:import```. It should be working fine and also importing schools with blank establishment number.

Allow to add GIAS Schools with blank establishment number

---

app/jobs/begin_ect_induction_job.rb
app/jobs/fail_ect_induction_job.rb
app/jobs/pass_ect_induction_job.rb
app/jobs/reopen_induction_job.rb
app/jobs/reset_induction_job.rb
app/jobs/teachers/sync_teacher_with_trs_job.rb
app/models/concerns/trs/retryable_client.rb
app/services/teachers/refresh_trs_attributes.rb
spec/jobs/fail_ect_induction_job_spec.rb
spec/jobs/pass_ect_induction_job_spec.rb
spec/jobs/teachers/sync_teacher_with_trs_job_spec.rb

As part of [this investigation] into mismatched TRS induction statuses, we identified that our background jobs are not retrying by default.
That meant that any intermittent API error (e.g service unavailability) would result in some jobs failing, and the corresponding updates *never happening*.
Now, in jobs that use the TRS API, we retry on API request errors. As part of this change, the `Teachers::RefreshTRSAttributes` service has been refactored so we can use a single `api_client` in a job, rather than instantiating several.
[this investigation]: https://github.com/DFE-Digital/register-ects-project-board/issues/2134

Retry background jobs when the TRS API errors

---

config/environments/production.rb
config/recurring.yml

We would like to clear jobs from the database when they are successfully finished. The number currently is at 7million in production as there has been no recurring job in place to cull those jobs.
Add job that clears finished jobs every hour on the 12th minute in batches.
This job was taken from solid queue: https://github.com/rails/solid_queue?tab=readme-ov-file#other-configuration-settings
I've changed the defaults for `clear_finished_jobs_after` from 1 day to a week instead in production.
I'm going to test this in migration env, even though the job runs deletions in batches it's worth monitoring deleting 7 million jobs at once and might require an initial manual task first

Add recurring job to clear finished solid queue jobs

---

spec/migration/migrators/teacher_spec.rb

A flaky spec was spotted. This was occurring because the teacher name was generated by Faker in the ECF User model and could contain a title which wasn't catered for in the spec.
Use parsed first and last names in the spec

Fix flaky `Teacher` spec

---

app/services/events/record.rb
app/services/schools/register_mentor.rb
app/views/schools/register_mentor_wizard/_review_mentor_details.html.erb
app/views/schools/register_mentor_wizard/check_answers.html.erb
app/views/schools/register_mentor_wizard/confirmation.md.erb
app/views/schools/register_mentor_wizard/eligibility_lead_provider.html.erb
app/views/schools/register_mentor_wizard/review_mentor_eligibility.html.erb
app/wizards/schools/register_mentor_wizard/check_answers_step.rb
app/wizards/schools/register_mentor_wizard/eligibility_lead_provider_step.rb
app/wizards/schools/register_mentor_wizard/mentor.rb
app/wizards/schools/register_mentor_wizard/review_mentor_details_step.rb
app/wizards/schools/register_mentor_wizard/wizard.rb
config/routes.rb
spec/features/schools/mentors/register_mentor/selecting_a_different_lead_provider_when_registering_a_new_mentor_spec.rb
spec/services/events/record_spec.rb
spec/views/schools/register_mentor_wizard/shared_examples/review_mentor_details_view.rb
spec/wizards/schools/register_mentor_wizard/mentor_spec.rb
spec/wizards/schools/register_mentor_wizard/shared_examples/review_mentor_details_step.rb
spec/wizards/schools/register_mentor_wizard/wizard_spec.rb

This PR adds support for selecting a different lead provider during the mentor registration flow.
Previously:
- Users could only continue with the ECT’s existing lead provider.
- The CYA page showed only the previous lead provider
Now:
- Users can choose an alternative lead provider from the list of LPs active in the mentor’s contract year.
- The CYA page shows the previous lead provider or the newly chosen lead provider, depending on the option chosen
---
- Added **Eligibility Lead Provider** step:
- Lists lead providers active in the relevant contract period.
- Includes validation
- Includes correct back link handling (returns to CYA if reached from CYA).
- Linked from "Mentor can receive mentor training" page when user clicks  
**"[ECT’s LP name] will not be providing mentor training …

[1864] Allow users to select a different lead provider than the ECTs when registering a new mentor

---

app/assets/stylesheets/admin/button-group.scss
app/assets/stylesheets/application.scss
app/controllers/admin/teachers/reopen_induction_controller.rb
app/jobs/reopen_induction_job.rb
app/views/admin/teachers/reopen_induction/confirm.html.erb
app/views/admin/teachers/show.html.erb
config/routes.rb
spec/features/admin/teachers/reopen_induction_spec.rb
spec/jobs/reopen_induction_job_spec.rb
spec/requests/admin/teachers/reopen_induction_spec.rb
spec/views/admin/teachers/show.html.erb_spec.rb

https://github.com/DFE-Digital/register-ects-project-board/issues/2142
Before, reopening a Teacher's induction was a one-click action.
We've seen some mistakes since launching this feature, so we think we've made it too easy to use accidentally. Especially considering the action is destructive and irreversible.
This adds some friction to the journey by introducing a confirmation screen.
Now, admins must confirm they are sure before then can reopen a Teacher's induction.
https://github.com/user-attachments/assets/55445094-5c7e-43b1-afde-f099e3ba546e

Admins must confirm before reopening an induction

---

.github/actions/directly-backup-and-restore-snapshot-database/action.yml
.github/actions/refresh-migration-database/action.yml
.github/workflows/directly-copy-main-db-into-snapshot-db.yml
.github/workflows/refresh_migration_database.yml

We want to have the option to exclude jobs tables when doing backups of the production database for the snapshot and migration environments so that the backups run quicker.
Add inputs to the migration/snapshot database refresh jobs so that we can ignore job tables and backup more quickly.
Include the jobs tables by default in snapshot.
Exclude the jobs tables by default in migration.
Tables excluded:
solid_queue_jobs – the master record of every enqueued job (active, scheduled, or finished) 
solid_queue_ready_executions – jobs ready to run now 
solid_queue_claimed_executions – jobs actively being worked on by a worker 
solid_queue_blocked_executions – jobs blocked due to concurrency limits 
solid_queue_failed_executions – failed job logs
solid_queue_processes – background process …

Add input to ignore jobs tables during backups

---

app/controllers/migration/parity_checks_controller.rb
app/migration/parity_check/request_dispatcher.rb
app/views/migration/parity_checks/show.html.erb

The parity check views have a few N+1 queries where we need to preload associations of the runs.
There was also a view that was re-querying grouped requests instead of operating on the already in-memory results.
Update `dispatch_requests` to batch-queue jobs to avoid an N+1 in SolidQueue.
- Fix N+1 queries in parity check

Fix N+1 queries in parity check

---

app/migration/migrators/school.rb

This PR improves the way we look up GIAS schools in the School migrator by replacing array scans with hash lookups, allowing constant-time access.
- Memoise GIAS school records in a hash keyed by `urn` instead of an array
- Look up GIAS schools directly from the hash by `urn`
- Remove unnecessary `.sort` on school URNs

Speed up GIAS school lookups in School migrator

---

app/models/metadata/delivery_partner_lead_provider.rb
app/services/metadata/handlers/base.rb
app/services/metadata/handlers/delivery_partner.rb
app/services/metadata/handlers/school.rb
app/services/metadata/resolver.rb
spec/factories/metadata/delivery_partner_lead_provider_factory.rb
spec/models/metadata/delivery_partner_lead_provider_spec.rb
spec/services/metadata/handlers/delivery_partner_spec.rb
spec/services/metadata/handlers/school_spec.rb
spec/services/metadata/resolver_spec.rb
spec/support/shared_examples/metadata_support.rb

We want to add the metadata handler for populating `DeliveryPartnerLeadProvider` metadata, so that we simplify our `DeliveryPartners::Query` and `DeliveryPartnerSerializer`.
- Add `Metadata::Handlers::DeliveryPartner`
Add a handler for delivery partners so that we can populate the `DeliveryPartnerLeadProviderMetadata`.
Extract shared logic into `Metadata::Handlers::Base` and DRY up specs with a shared context.
- Improve contract_period_years validation
We were getting validation errors due to some `ContractPeriod` records that are created for future years (2026). To make this more robust we can check that the `ContractPeriod` for each year exists in the database. It will be a bit slower, but the numbers should be fairly low for `DeliveryPartnerLeadProvider`.
It wasn't part of this ticket, …

Add `Metadata::Handlers::DeliveryPartner`

---

app/migration/builders/builder_helpers.rb
app/migration/builders/ect/training_periods.rb
app/migration/builders/mentor/training_periods.rb
app/migration/induction_record_sanitizer.rb
app/migration/migrators/ect_at_school_period.rb
app/migration/migrators/mentor_at_school_period.rb
app/migration/migrators/training_period.rb
app/migration/training_period_extractor.rb
app/models/migration/training_period_data.rb
spec/factories/migration/training_period_factory.rb
spec/migration/builders/ect/training_periods_spec.rb
spec/migration/builders/mentor/training_periods_spec.rb

For the `ECTAtSchoolPeriod` and `MentorAtSchoolPeriod` we've had good results by grouping the participant's ECF `InductionRecord`s by school.  This PR was original a spike to check if we could get better results (i.e. less validation errors) when migrating `TrainingPeriod` by grouping the `InductionRecord`s by the provider.  This has yielded an improvement (albeit not as big as for the school periods) so is worth pursuing further.
Group participant's induction records by provider when parsing and validating them.

Group induction records by provider for training period migration

---

app/controllers/api/v3/partnerships_controller.rb
app/controllers/concerns/api/paginatable.rb
app/models/lead_provider_delivery_partnership.rb
app/models/school_partnership.rb
app/serializers/partnership_serializer.rb
app/services/school_partnerships/query.rb
config/routes.rb
spec/models/lead_provider_delivery_partnership_spec.rb
spec/models/school_partnership_spec.rb
spec/requests/api/v3/partnerships_spec.rb
spec/serializers/partnership_serializer_spec.rb
spec/support/shared_contexts/api/filterable_endpoint.rb
spec/support/shared_contexts/api/paginated_endpoint.rb

Ticket: https://github.com/DFE-Digital/register-ects-project-board/issues/2055
We need to allow Lead Providers to view all partnerships they manage, or just view details of a specific partnership.
- Add partnership api endpoints
- Return cohort value as a string in partnership endpoint
- Fix n+1 queries in partnership query service
- Postman calls to the review app url:
- GET `https://cpd-ec2-review-1148-web.test.teacherservices.cloud/api/v3/partnerships`
- GET `https://cpd-ec2-review-1148-web.test.teacherservices.cloud/api/v3/partnerships/{id}`
- Use the available filter options (`cohort`, `updated_since` and `delivery_partner_id`)
- Use the sort option
- Use the pagination option

[2055] Add partnership api endpoints

---

public/api/docs/v3/swagger.yaml
spec/requests/api/docs/v3/partnerships_spec.rb
spec/swagger_helper.rb
spec/swagger_schemas/filters/partnerships.rb
spec/swagger_schemas/models/partnership.rb
spec/swagger_schemas/responses/partnership.rb
spec/swagger_schemas/responses/partnerships.rb

Ticket: https://github.com/DFE-Digital/register-ects-project-board/issues/2056
Swagger documentation allows for LP developer and integrations team to read the API structure based off of our libraries.
- Add partnership endpoints to swagger
- [Review app swagger docs](https://cpd-ec2-review-1153-web.test.teacherservices.cloud/api/docs/v3)

[2056] Add partnership endpoints to swagger

---

app/jobs/sample_job.rb

We're not using this, so I figured we can remove it.

Remove `SampleJob`

---

.rubocop.yml
.rubocop/cop/rspec/require_rails_helper.rb
app/components/api/guidance/sidebar_component.rb
app/components/appropriate_bodies/claim_ect_actions_component.rb
app/components/schools/summary_card_component.rb
app/controllers/schools/register_ect_wizard_controller.rb
app/mailers/application_mailer.rb
app/services/appropriate_bodies/search.rb
app/services/gias/importer.rb
app/services/migration/induction_sequence_exporter.rb
app/services/migration/induction_sequence_formatter.rb
app/wizards/schools/register_ect_wizard/email_address_step.rb
app/wizards/schools/register_ect_wizard/find_ect_step.rb
app/wizards/schools/register_ect_wizard/national_insurance_number_step.rb
app/wizards/schools/register_ect_wizard/review_ect_details_step.rb
app/wizards/schools/register_ect_wizard/wizard.rb
app/wizards/schools/register_mentor_wizard/national_insurance_number_step.rb
config/initializers/sentry.rb
config/puma.rb
db/scripts/fix_mismatched_induction_statuses.rb
lib/schools/validation/date_of_birth.rb
lib/schools/validation/ect_start_date.rb
lib/schools/validation/hash_date.rb
lib/schools/validation/mentor_start_date.rb
lib/trs/teacher.rb
spec/components/appropriate_bodies/claim_ect_actions_component_spec.rb
spec/support/rack_attack.rb
spec/support/rspec_playwright.rb
spec/support/shared_examples/declarative_touch.rb
spec/support/shared_examples/rate_limiting_support.rb

Ruby 3.4 [freezes string literals by default](https://www.ruby-lang.org/en/news/2024/05/16/ruby-3-4-0-preview1-released/), making the magic comment and `.freeze` on strings redundant.
- Enable `StringLiteralsFrozenByDefault` in RuboCop
- Set `TargetRubyVersion` to 3.4
- Remove magic comments and `.freeze` from string literals
- Keep `.freeze` on arrays, hashes, and non literals
- Simplify `ENV.fetch` defaults in Puma config
- Disallow `# frozen_string_literal` comments via RuboCop
Commit by commit.

[1195] Remove frozen string comments and redundant `.freeze`

---

app/services/mentor_at_school_periods/latest_registration_choices.rb
app/views/schools/register_mentor_wizard/previous_training_period_details.html.erb
app/wizards/schools/register_mentor_wizard/mentor.rb
app/wizards/schools/register_mentor_wizard/programme_choices_step.rb
app/wizards/schools/register_mentor_wizard/started_on_step.rb
app/wizards/schools/register_mentor_wizard/wizard.rb
spec/services/mentor_at_school_periods/latest_registration_choices_spec.rb
spec/wizards/schools/register_mentor_wizard/mentor_spec.rb
spec/wizards/schools/register_mentor_wizard/programme_choices_step_spec.rb
spec/wizards/schools/register_mentor_wizard/started_on_step_spec.rb
spec/wizards/schools/register_mentor_wizard/wizard_spec.rb

When re-registering a mentor who has previously been registered, we show the previous registration details (school name, lead provider, and delivery partner) if their previous training period was `provider_led` and they are eligible for funding.
This step appears after the `started_on` step, if applicable.
---
- Adds logic to render previous registration details (`school`, `lead provider`, and `delivery partner`) on the `has been registered before` page
- Falls back to `"Not confirmed"` if LP/DP/School is missing
- Redirect to `check_answers` if:
- `school_led` or  not eligible for funding
- Pre-fills with:
- school partnership (if present)
- or expression of interest (EOI)
---
- The `MentorAtSchoolPeriods::LatestRegistrationChoices` service encapsulates logic for looking up the most …

[1249] Redirect to `has been registered before` page when applicable (`#MentorRegistrationFlow`)

---

app/models/event.rb
app/services/events/record.rb
app/services/school_partnerships/update.rb
spec/services/events/record_spec.rb
spec/services/school_partnerships/update_spec.rb

We want to add a service that will enable school partnerships to change delivery partner in order to support the `PUT /api/v3/partnerships/:id` endpoint.
- Add `Partnerships::Update` service
Add service to update the delivery partner for a given partnership.
Send an update event that tracks the change (including the previous delivery partner in the metadata).
In order to perform an update, there must: 
- be a school partnership and delivery partner matching the provided ids.
- be a lead provider delivery partnership for the lead provider and delivery 
partner.
- not already be a partnership with the same lead provider and delivery partner.
We don't appear to need to refresh any metadata off the back of a partnership update.

Add `Partnerships::Update` service

---

app/controllers/schools/assign_existing_mentor_wizard_controller.rb
app/controllers/schools/mentorships_controller.rb
app/views/schools/assign_existing_mentor_wizard/confirmation.md.erb
app/views/schools/assign_existing_mentor_wizard/lead_provider.html.erb
app/views/schools/assign_existing_mentor_wizard/review_mentor_eligibility.html.erb
app/wizards/schools/assign_existing_mentor_wizard/confirmation_step.rb
app/wizards/schools/assign_existing_mentor_wizard/lead_provider_step.rb
app/wizards/schools/assign_existing_mentor_wizard/review_mentor_eligibility_step.rb
app/wizards/schools/assign_existing_mentor_wizard/step.rb
app/wizards/schools/assign_existing_mentor_wizard/wizard.rb
app/wizards/schools/shared/mentor_assignment_context.rb
config/routes.rb
spec/features/schools/mentorship/add_a_mentor_to_a_provider_led_ect_spec.rb
spec/features/schools/mentorship/add_a_mentor_to_a_school_led_ect_spec.rb
spec/requests/schools/assign_existing_mentor_wizard_spec.rb
spec/requests/schools/mentorships_spec.rb
spec/support/features/view_helpers.rb
spec/wizards/schools/assign_existing_mentor_wizard/lead_provider_step_spec.rb
spec/wizards/schools/assign_existing_mentor_wizard/review_mentor_eligibility_step_spec.rb
spec/wizards/schools/assign_existing_mentor_wizard/wizard_spec.rb
spec/wizards/schools/shared/mentor_assignment_context_spec.rb

Introduce a mini wizard into the mentor assignment flow. This will allows us to handle new questions in a structured way and makes the flow easier to extend or adjust in future.
- Add a **mentor eligible page** leading onto the confirmation step
- Add **lead provider selection page**, accessible from the eligibility step
- Add a **confirmation page** for completing the flow
- Introduce `Schools::Shared::MentorAssignmentContext` PORO to encapsulate wizard logic
Login as **Serena** and assign a mentor to **Harriet Walter**, choose **Dame Helen Mirren**. You will then be on the new journey. Click the link below the continue button to get to the Lead provider selection page.

[1834] update journey for school led mentor being assigned to a provider led ECT for the first time

---

app/components/schools/ect_induction_details_component.rb
app/components/schools/ect_training_details_component.rb
app/components/schools/teacher_profile_summary_list_component.html.erb
app/components/schools/teacher_profile_summary_list_component.rb
app/services/ect_at_school_periods/current_training.rb
app/views/schools/ects/show.html.erb
config/initializers/constants.rb
spec/components/schools/ect_induction_details_component_spec.rb
spec/components/schools/ect_training_details_component_spec.rb
spec/components/schools/teacher_profile_summary_list_component_spec.rb
spec/initializers/constants_spec.rb
spec/views/schools/ects/show.html.erb_spec.rb

This is #1139 re-reverted so we can fix some failing tests around training programme and its new location in `training_periods`.

Update ECT details page (2nd attempt)

---

public/api/docs/v3/swagger.yaml
spec/requests/api/docs/v3/partnerships_spec.rb
spec/support/shared_contexts/api/docs/api_create_endpoint_documentation_support.rb
spec/swagger_helper.rb
spec/swagger_schemas/requests/partnership.rb
spec/swagger_schemas/responses/bad_request.rb
spec/swagger_schemas/responses/unprocessable_content.rb

We want to add the swagger docs for the POST /api/v3/partnerships endpoint.
- Add API documentations for POST /api/v3/partnerships
Add the swagger documentation for POST /api/v3/partnerships.
Use shared context so that we can re-use it for other POST requests.
Add needed response schemas.
[Swagger docs](https://cpd-ec2-review-1202-web.test.teacherservices.cloud/api/docs/v3)
Note the attribute names in the error response will be incorrect for the time being; these will be fixed when we address the general API/RECT error message/terminology consistency issues.

Add swagger docs for POST /api/v3/partnerships

---

app/services/api/errors/mapper.rb
app/services/api/errors/response.rb
app/services/school_partnerships/create.rb
app/services/school_partnerships/update.rb
config/api_error_mappings.yml
spec/fixtures/files/api_error_mappings.yml
spec/services/api/errors/mapper_spec.rb
spec/services/api/errors/response_spec.rb
spec/services/school_partnerships/create_spec.rb
spec/services/school_partnerships/update_spec.rb

We need to be able to swap out the RECT terminology used in the service errors and attribute names with ECF terminology that lead providers are familiar with.
- Update school partnership service errors to use RECT terminology
At the moment we use RECT attribute names and ECF error messages. Going forward we're going to keep the service using RECT terminology and swap out the errors in the API responses.
- Add API error mapping service
Add `API::Errors::Mapper` service that will transform RECT terms to ECF.
Hook into the `API::Errors::Response` service to replace error messages.
Initially I thought we would be replacing whole error messages and was worried about how we would catch changes to error messages in the service, but as we're only replacing terms I don't think it will be as big of …

Replace RECT terminology with ECF terminology in API error messages

---

app/migration/migrate_entity.rb
app/migration/migrators/active_lead_provider.rb
app/migration/migrators/contract_period.rb
app/migration/migrators/delivery_partner.rb
app/migration/migrators/ect_at_school_period.rb
app/migration/migrators/lead_provider.rb
app/migration/migrators/lead_provider_delivery_partnership.rb
app/migration/migrators/mentor_at_school_period.rb
app/migration/migrators/mentorship_period.rb
app/migration/migrators/reconcile_adjustment.rb
app/migration/migrators/school_partnership.rb
app/migration/migrators/statement.rb
app/migration/migrators/statement_adjustment.rb
app/migration/migrators/teacher.rb
app/migration/migrators/training_period.rb
spec/migration/migrate_entity_spec.rb

Often when testing we need a small amount of known data to work with. Currently the only way to get everything is to do a full migration which takes around 5 hours.
This PR adds the ability to migrate a teacher, school partnership and active lead provider with all of their dependencies from the console.
The only dependency expected to already exist in your DB (ie. that won't get migrated) is the `School` as we import these from GIAS.
This could be expanded to other entities however the addition of `migrate_one!` to the migrators allows a simple migration of a single entity via the migrator (as long as any dependencies exist in this case).
Add `MigrateEntity` class
Adds `migrate_one!` to existing migrators
From the Rails console:
```
MigrateEntity.new.teacher(trn:)
```
or
``` …
```

Add ability to migrate single entity

---

config/parity_check_endpoints.yml

When running parity check we currently get a missing cohort filter error as we aren't including the require dfilter
- Add all cohort years for school
- Ensure cohort is called on getting a single school as it is required

Add more cases for schools parity check

---

app/models/training_period.rb
app/services/ect_at_school_periods/current_training.rb
app/views/schools/register_ect_wizard/_use_previous_ect_choices.html.erb
app/views/schools/register_mentor_wizard/review_mentor_eligibility.html.erb
app/wizards/schools/register_mentor_wizard/mentor.rb
app/wizards/schools/register_mentor_wizard/programme_choices_step.rb
app/wizards/schools/register_mentor_wizard/review_mentor_eligibility_step.rb
spec/models/training_period_spec.rb
spec/services/ect_at_school_periods/current_training_spec.rb

This (hopefully) fixes DFE-Digital/register-ects-project-board#2213 where the lead provider name wasn't shown because there was only an EOI lead provider present and not one via school partnership.
It also adds new relationships to `TrainingPeriod` that allow us to find the lead provider and contract period via the expression of interest as well as via school partnership.
For now the:
* the _confirmed_ relations are unprefixed as they are the _actual_ values
* the _expression of interest_ relations are prefixed as they aren't yet official
We may make both prefixed for extra explicitness if this is still confusing!
- **Add expression_of_interest prefixed relationships**
- **Add method to select relevant lead provider**
The changes made in `_use_previous_ect_choices.html.erb` aren't great, …

Make the review mentor eligibilty screen show the relevant lead provider

---

app/controllers/api/base_controller.rb
app/controllers/api/v3/partnerships_controller.rb
spec/requests/api/v3/partnerships_spec.rb
spec/support/shared_contexts/update_endpoint.rb

Now that we have the `SchoolPartnerships::Update` service, we want to connect it to the `PUT /partnerships/:id` endpoint to allow lead providers to create partnerships.
- Add PUT /api/v3/partnerships/:id endpoint
Call the `SchoolPartnerships::Update` service from the `update` action of the `PartnershipsController`.
Add shared context for testing `update` actions.
- Switch partnerships controller to use params.expect
Note we need to still `require(:data)` as the result of `expect(data: { attributes: %i[attr] })` is a hash of `{ attributes: ... }` when we just want the bottom-level attributes.

Add PUT /partnerships/:id endpoint 

---

public/api/docs/v3/swagger.yaml
spec/requests/api/docs/v3/partnerships_spec.rb
spec/support/shared_contexts/api/docs/api_update_endpoint_documentation_support.rb
spec/swagger_helper.rb
spec/swagger_schemas/requests/partnership_create.rb
spec/swagger_schemas/requests/partnership_update.rb

We want to add the swagger docs for the PUT /api/v3/partnerships/:id endpoint.
- Add API documentations for PUT /api/v3/partnerships/:id
Add the swagger documentation for PUT api/v3/partnerships/:id.
Use shared context so that we can re-use it for other PUT requests.
[Swagger docs](https://cpd-ec2-review-1221-web.test.teacherservices.cloud/api/docs/v3)
Note the attribute names in the error response will be incorrect for the time being; these will be fixed when we address the general API/RECT error message/terminology consistency issues.

Add swagger docs for PUT /api/v3/partnerships/:id

---

app/migration/parity_check/dynamic_request_content.rb
app/models/contract_period.rb
config/parity_check_endpoints.yml
spec/factories/parity_check/endpoint_factory.rb
spec/features/migration/run_parity_check_spec.rb
spec/migration/parity_check/dynamic_request_content_spec.rb
spec/models/contract_period_spec.rb

We want to include the POST and PUT partnership endpoints in the parity check so that we can verify it behaves consistently with ECF.
- Add partnerships POST/PUT endpoints to parity check
Add the POST and PUT endpoints to the parity check endpoints config file.
Update the `DynamicRequestContent` with the relevant request body methods.
Fallback to returning a `nil` body if required data can't be found to make a valid request; this will result in a 422 in the parity check, which should be fine and will prevent it from just falling over.
Tested in migration - a few things identified that will be raised as new tickets.

Add POST/PUT partnership parity check endpoints

---

app/controllers/admin/induction_periods_controller.rb
app/services/events/record.rb
app/services/induction_periods/delete_induction_period.rb
app/views/admin/induction_periods/confirm_delete.html.erb
spec/features/admin/teachers/delete_induction_period_spec.rb
spec/requests/admin/induction_periods_spec.rb
spec/services/induction_periods/delete_induction_period_spec.rb
spec/views/admin/induction_period/confirm_delete.html.erb_spec.rb

Building on #1176, this ensures Admin users provide extra information (in the form of a Zendesk ticket ID or a note) when they delete an induction period.

Admins must add context when deleting an induction period

---

app/wizards/schools/register_mentor_wizard/programme_choices_step.rb
spec/wizards/schools/register_mentor_wizard/programme_choices_step_spec.rb

Update validation error message on programme choices step in line with `FE21`
|<img width="866" height="775" alt="image" src="https://github.com/user-attachments/assets/e533216a-8937-4b3a-96fc-a1b2ca1cd7f6" />|<img width="833" height="796" alt="image" src="https://github.com/user-attachments/assets/dd0c0eb0-e365-4108-829e-a01404f7365d" />|

[1249] Update validation error message (#MentorRegistrationFlow)

---

app/services/sessions/users/appropriate_body_user.rb

Old sessions cannot be expired without first instantiating the session user

Allow old AB sessions to be loaded

---

app/models/school.rb
config/analytics_blocklist.yml
db/migrate/20250901173600_remove_api_id_from_gias_schools.rb
db/schema.rb
spec/models/school_spec.rb

Ticket: [2303](https://github.com/DFE-Digital/register-ects-project-board/issues/2303)
The `api_id` is on `GIAS::School`. This poses a risk as GIAS data can be cleared and repopulated as it is deemed refreshable data. The `api_id` needs to remain intact regardless.
- [First commit](https://github.com/DFE-Digital/register-early-career-teachers-public/pull/1259/commits/be7a5e13333025edf449c3c743f35565798d2360) - Add new column called `api_id` to `School` which follows the `api_id`;
- [Second commit](https://github.com/DFE-Digital/register-early-career-teachers-public/pull/1259/commits/9d82b274b190fb813e0e50b1b92b091f5e1bf0e0) - Update writes to new column from `GIAS::School` to `School`;
- [Third commit](https://github.com/DFE-Digital/register-early-career-teachers-public/pull/1259/commits/a …

[2303] Move `GIAS::School` `api_id` field to `School`

---

app/wizards/schools/register_mentor_wizard/check_answers_step.rb
spec/wizards/schools/register_mentor_wizard/check_answers_step_spec.rb

Fix the back link logic on the Check Answers page for the "previously registered mentor" journey.
Specifically:
- Return to `:mentoring_at_new_school_only` if the user selected 'no' to "Mentoring only at your school"
- Return to `:programme_choices` if the user selected 'yes' to both "Mentoring only at your school" and "Use same programme choices"
- Return to `:lead_provider` if not using previous programme choices

[1249] Fix back links on CYA page for previously registered mentor journey (#MentorRegistrationFlow)

---

app/migration/legacy_data_importer.rb
app/migration/migrators/base.rb
app/services/metadata/handlers/base.rb
app/services/metadata/handlers/delivery_partner.rb
app/services/metadata/handlers/school.rb
app/services/metadata/manager.rb
spec/migration/legacy_data_importer_spec.rb
spec/services/metadata/handlers/delivery_partner_spec.rb
spec/services/metadata/handlers/school_spec.rb
spec/services/metadata/manager_spec.rb
spec/support/shared_examples/migrator_support.rb

We want to prevent any metadata from being created during a data migration, as it will lead to a slower migration time and multiple changes to the same object over the duration of a run. It's going to be more performant to instead trigger a 'refresh all metadata' once the data migration has completed.
-  Clear metadata on `LegacyDataImporter.reset!`
To be consistent with the other migration data, we want to clear out the metadata when the migration is reset.
- Kck off metadata refresh after migration finishes
We want to populate the metadata once a migration has finished, but we don't want to block/slow the migration process down.
Kick off an async metadata refresh after migrating all data.
- Prevent metadata from being created during data migration
We want to stop metadata from being …

Refresh metadata after a data migration

---

app/helpers/parity_check_helper.rb
app/models/parity_check/request.rb
app/models/parity_check/response.rb
app/views/migration/parity_checks/requests/_response_body_ids_diff.html.erb
app/views/migration/parity_checks/requests/show.html.erb
app/views/migration/parity_checks/responses/_body_diff.html.erb
app/views/migration/parity_checks/responses/_body_ids_diff.html.erb
app/views/migration/parity_checks/responses/show.html.erb
config/initializers/inflections.rb
db/seeds/parity_checks.rb
spec/features/migration/view_parity_check_request_spec.rb
spec/features/migration/view_parity_check_response_spec.rb
spec/helpers/parity_check_helper_spec.rb
spec/models/parity_check/request_spec.rb
spec/models/parity_check/response_spec.rb

When a parity check request fails its often hard to figure out if the underlying objects are the same (even if their contents are different).
- Add response ID diffs to parity check
Add response ID diff section to both the request page (to show differences across all responses) and the individual response page.
| Request    | Response |
| -------- | ------- |
| <img width="3384" height="4036" alt="screencapture-0-0-0-0-3000-migration-parity-checks-2-requests-29-2025-09-05-14_16_30" src="https://github.com/user-attachments/assets/5919e99e-9afc-44df-9158-3e3f72719eae" />  | <img width="3384" height="4866" alt="screencapture-0-0-0-0-3000-migration-parity-checks-2-responses-56-2025-09-05-14_15_37" src="https://github.com/user-attachments/assets/b1160b5b-64c5-471a-864d-920e3db42118" />   |

Add response ID diffs to parity check

---

db/seeds/api_tokens.rb
db/seeds/appropriate_bodies.rb
db/seeds/contract_periods.rb
db/seeds/delivery_partners.rb
db/seeds/lead_provider_delivery_partnerships.rb
db/seeds/parity_checks.rb
db/seeds/persona_users.rb
db/seeds/school_partnerships.rb
db/seeds/schools.rb
db/seeds/statements.rb
db/seeds/teacher_histories.rb
db/seeds/teachers.rb

Ticket: [2304](https://github.com/DFE-Digital/register-ects-project-board/issues/2304)
Currently, DB seeds use normal method creation on models to create records. We have moved now to create sandbox seeds from Factory Bot and should do the same in normal seeds.
- Use factory bot in DB seeds for creating records;
- Ensure consistency with the expected records in the seeds and tidy up if necessary;
Review app

[2304] Use FactoryBot in DB seeds

---

.rubocop_todo.yml
app/services/sessions/manager.rb
spec/services/sessions/session_manager_spec.rb

See https://github.com/DFE-Digital/register-early-career-teachers-public/pull/1284
We struggled with a production release when user session objects changed the required class parameters or session variables. An upcoming change that will face the same issue is when RECT logins use DSI UUID instead of URN to find the School.
- Make it easier to change session objects in the future
- Mitigate crashes when new arguments are added or old ones removed
- Rescue and report when session objects have evolved
- Add unit test for session manager role switching
Edit the stored session from an earlier login by either removing an essential value or adding a new one. The session should be successfully purged so a new login attempt can be made.
This means production users need not clear session data and …

Support session object breaking changes

---

app/controllers/schools/ects_controller.rb
app/models/concerns/interval.rb
app/models/ect_at_school_period.rb
app/models/teacher.rb
app/services/ect_at_school_periods/current_training.rb
app/services/ect_at_school_periods/finish.rb
app/services/ect_at_school_periods/mentorship.rb
app/services/schools/assign_mentor.rb
app/services/teachers/search.rb
app/views/schools/ects/index.html.erb
spec/models/concerns/interval_spec.rb
spec/models/ect_at_school_period_spec.rb
spec/models/teacher_spec.rb
spec/services/ect_at_school_periods/current_training_spec.rb
spec/services/ect_at_school_periods/mentorship_spec.rb
spec/services/schools/assign_mentor_form_spec.rb
spec/services/schools/assign_mentor_spec.rb

The ordering of ECTs should be ECTs without mentors first, then start date (latest first).
This was broken by ordering being added to another scope which was also used by the query, which preceeded the custom sorting.
To fix this I moved `.earliest_first` from the scope to the `current_*` relationships and renamed those relationship to `current_or_next`.
- **Rename scope to current_or_future**
- **Move earliest_first call from scope to relationships**
- **Rename current relationships to current_or_next**

Fix ECT ordering bug

---

app/models/appropriate_body.rb
app/models/delivery_partner.rb
app/models/lead_provider.rb
app/models/teacher.rb
spec/models/appropriate_body_spec.rb
spec/models/delivery_partner_spec.rb
spec/models/lead_provider_spec.rb
spec/models/teacher_spec.rb

Rails' [normalizes](https://api.rubyonrails.org/v7.1/classes/ActiveRecord/Normalization/ClassMethods.html) method allows us to apply formatting, in this case the removal of leading/trailing whitespace via ActiveSupport's `String#squish`.
Squishing removes:
* leading whitespace `" Appropriate body"` becomes `"Appropriate body"`
* trailing whitespace `"Appropriate body "` becomes `"Appropriate body"`
* contiguous whitespace `"Appropriate  body"` becomes `"Appropriate body"`
These often creep in when people are editing and paste in a name from another source. We never want them and they're likely to make formatting look wonky if we ever end up with them.

Strip extra whitespace on names

---

app/components/schools/mentors/details_component.rb
app/controllers/schools/mentors/change_name_wizard_controller.rb
app/views/schools/mentors/change_name_wizard/check_answers.html.erb
app/views/schools/mentors/change_name_wizard/confirmation.html.erb
app/views/schools/mentors/change_name_wizard/edit.html.erb
app/wizards/schools/mentors/change_name_wizard/check_answers_step.rb
app/wizards/schools/mentors/change_name_wizard/confirmation_step.rb
app/wizards/schools/mentors/change_name_wizard/edit_step.rb
app/wizards/schools/mentors/change_name_wizard/wizard.rb
app/wizards/schools/mentors/wizard.rb
config/routes.rb
spec/factories/change_mentor_name_wizard_factory.rb
spec/features/schools/mentors/change/name_spec.rb
spec/wizards/schools/mentors/change_name_wizard/check_answers_step_spec.rb
spec/wizards/schools/mentors/change_name_wizard/confirmation_step_spec.rb
spec/wizards/schools/mentors/change_name_wizard/edit_step_spec.rb
spec/wizards/schools/mentors/change_name_wizard/wizard_spec.rb

School users need to edit mentor details.
Mentor version of #1253 
- `/school/mentors/N/change-name/edit`
- `/school/mentors/N/change-name/check-answers`
- `/school/mentors/N/change-name/confirmation`

Change a mentor's name

---

app/migration/parity_check/dynamic_request_content.rb
spec/migration/parity_check/client_spec.rb
spec/migration/parity_check/dynamic_request_content_spec.rb
spec/support/shared_examples/parity_check_support.rb

Ticket: https://github.com/DFE-Digital/register-ects-project-board/issues/2384
Currently, the parity check is sending different PUT/POST requests to ECF and RECT. Instead we'd like them to be similar
- Memoise calls to `dynamic_request_content` service class so same endpoints calls to both ecf & rect will use the same params in the body.

[2384] Fix parity check POST/PUT endpoints

---

app/assets/stylesheets/migration/parity_check.scss
app/migration/parity_check/client.rb
app/models/parity_check/request.rb
app/views/migration/parity_checks/requests/show.html.erb
app/views/migration/parity_checks/responses/_filter.html.erb
app/views/migration/parity_checks/responses/show.html.erb
config/analytics_blocklist.yml
db/migrate/20250915065439_add_request_details_to_parity_check_responses.rb
db/schema.rb
spec/factories/parity_check/response_factory.rb
spec/features/migration/view_parity_check_response_spec.rb
spec/migration/parity_check/client_spec.rb
spec/models/parity_check/request_spec.rb
spec/support/shared_examples/parity_check_support.rb

We want to store and surface the request URIs and body from parity check requests in the UI to help us notice/debug potential issues with the check/requests.
- Ensure ParityCheck::Client makes consistent requests
We ran into an issue with the parity check where the request bodies were being uniquely generated for a particular `ParityCheck::Request` (so one sent to ECF and another to RECT).
This is hard to debug in the user interface; we have since fixed the underlying issue, but this puts a safety net in place to ensure at the `Client` level it is verifying the requests are being consistently made by comparing `method`, `request_body`, `request_headers` and `query`.
- Retain request URIs and body in ParityCheck::Response
We want to surface the request body and URIs in the parity check …

Show request body in parity check

---

app/services/schools/register_mentor.rb
spec/services/schools/register_mentor_spec.rb

Previously we used `.prev_day`, which introduced an unnecessary gap and prevented re-registering a mentor the day after their previous period.
Update `finish_existing_at_school_periods!` to pass `finished_on: started_on` instead of `started_on.prev_day`.
- Register a mentor at one school, then register the same mentor at another school using tomorrow's date - it should work.
- Try the same flow on `main` or `staging` - it should blow up.

Finish periods on new start date instead of previous day

---

.rubocop_todo.yml
spec/components/admin/statements/adjustments_component_spec.rb
spec/components/admin/statements/filter_component_spec.rb
spec/components/admin/statements/selector_component_spec.rb
spec/misc/terraform_versions_spec.rb
spec/models/ect_at_school_period_spec.rb
spec/models/induction_period_spec.rb
spec/models/mentor_at_school_period_spec.rb
spec/models/mentorship_period_spec.rb
spec/models/school_spec.rb
spec/models/statement_spec.rb
spec/services/teachers/induction_period_spec.rb
spec/wizards/schools/ects/change_name_wizard/check_answers_step_spec.rb
spec/wizards/schools/ects/change_name_wizard/edit_step_spec.rb
spec/wizards/schools/mentors/change_name_wizard/check_answers_step_spec.rb
spec/wizards/schools/mentors/change_name_wizard/edit_step_spec.rb
spec/wizards/schools/register_ect_wizard/check_answers_step_spec.rb
spec/wizards/schools/register_ect_wizard/email_address_step_spec.rb
spec/wizards/schools/register_ect_wizard/find_ect_step_spec.rb
spec/wizards/schools/register_ect_wizard/national_insurance_number_step_spec.rb
spec/wizards/schools/register_ect_wizard/review_ect_details_step_spec.rb
spec/wizards/schools/register_ect_wizard/start_date_step_spec.rb
spec/wizards/schools/register_ect_wizard/training_programme_step_spec.rb
spec/wizards/schools/register_ect_wizard/use_previous_ect_choices_step_spec.rb
spec/wizards/schools/register_ect_wizard/working_pattern_step_spec.rb
spec/wizards/schools/register_mentor_wizard/check_answers_step_spec.rb
spec/wizards/schools/register_mentor_wizard/find_mentor_step_spec.rb
spec/wizards/schools/register_mentor_wizard/national_insurance_number_step_spec.rb
spec/wizards/schools/register_mentor_wizard/shared_examples/review_mentor_details_step.rb

We should be using `describe` to test methods and `context` to test different scenarios.
The cop is now re-enabled.
Refs #1318

Change `context` to `describe` when testing methods

---

app/services/schools/register_ect.rb
spec/services/schools/register_ect_spec.rb

When registering an ECT, we store the school's last chosen appropriate body, lead provider, and training programme.  
A previous refactor introduced `choices.compact` in `update_school_last_choices!`. This skipped updating attributes when the value was `nil`.
When switching from **provider-led** to **school-led** training, the `last_chosen_lead_provider` attribute was left populated (because the `nil` update was compacted away).  
This caused a validation failure:
`Validation failed: Last chosen lead provider must be nil`
- Restored the original behaviour so that all three attributes are always updated.
- This ensures irrelevant fields are explicitly cleared (`nil`) when moving between training types.
- Confirm that school-led journeys now succeed when registering an ECT after a …

[2400] Fix validation error when switching from provider-led to school-led ECT registration

---

config/analytics_blocklist.yml
db/migrate/20250916071240_add_payments_frozen_years_to_teacher.rb
db/schema.rb
db/seeds/teachers.rb
documentation/domain-model.md
spec/factories/ect_at_school_period_factory.rb
spec/factories/mentor_at_school_period_factory.rb

We need to store if a participant has migrated from a payments frozen contract period so that we can surface this information in the API. In ECF we store a `boolean` flag to indicate this, but it makes determining the particular year they migrated from more complicated as we have to dive into their declarations. In RECT we are opting to store the contract period year on the `Teacher` model; we need this for both ECTs and mentors, so are adding attributes for each.
We will revisit this approach down the line when we are building the change schedule service and have a better idea of how all these ECT/mentor specific attributes could hang together.
- Add ect/mentor_payments_frozen_year to Teacher
We want to track the payments frozen year for teachers, so we can expose this information in the …

Add payments frozen attributes to `Teacher`

---

app/models/ect_at_school_period.rb
app/models/event.rb
app/models/training_period.rb
app/services/api/school_partnerships/create.rb
app/services/events/record.rb
app/services/school_partnerships/assign_training_periods.rb
app/services/school_partnerships/create.rb
app/services/training_periods/search.rb
spec/models/ect_at_school_period_spec.rb
spec/models/training_period_spec.rb
spec/services/api/school_partnerships/create_spec.rb
spec/services/events/record_spec.rb
spec/services/school_partnerships/assign_training_periods_spec.rb
spec/services/school_partnerships/create_spec.rb
spec/services/training_periods/search_spec.rb

When a lead provider submits a partnership over the API, we need to ensure the partnership is linked to any relevant ECTs or mentors. This ensures the lead provider and delivery partner appear correctly on the teacher's record. 
- Builds on the `SchoolPartnerships::Create` service
- Automatically links eligible training periods (ECTs or mentors in provider-led training) to the new school partnership.
- Records a `training_period_assigned_to_school_partnership` event for each linked training period
**Check:**
```ruby
Event.where(event_type: "training_period_assigned_to_school_partnership").pluck(:event_type, :heading, :school_partnership_id, :training_period_id)
```
**Result:**
```plaintext
=> [["training_period_assigned_to_school_partnership", "First name 1 Last name 1’s ECT training …
```

[2172] Link relevant training periods when creating a school partnership

---

app/migration/migrators/school_partnership.rb
spec/migration/migrators/school_partnership_spec.rb

The migrator for `SchoolPartnership` should migrate the timestamps from the ECF `Partnership` record
- Migrates the ECF `Partnership.created_at` to `SchoolPartnership.created_at`
- Migrates the ECF `Partnership.updated_at` to `SchoolPartnership.api_updated_at`

Add timestamps to `SchoolPartnership` migrator

---

spec/services/sandbox_seed_data/school_partnerships_spec.rb

The school partnerships spec compared arrays of ActiveRecord objects with `==`,  which is order sensitive. This caused flakiness when the same records were returned in a different order:
```plaintext
expected: [LeadProvider(2191), LeadProvider(2192)]
got: [LeadProvider(2192), LeadProvider(2191)]
```
[See failure in CI here](https://github.com/DFE-Digital/register-early-career-teachers-public/actions/runs/17826787050/job/50681751295)
Replace `==` with `match_array`. This asserts that all lead providers and contract periods are covered without requiring a specific order.
Run the spec multiple times, It should never fail.

Relax order sensitive assertions in school partnerships spec

---

app/services/teachers/induction_status.rb

Also refactor the class a little. Originally this class's only purpose was to splat arguments into the status tag, however it's now also used to provide the status name elsewhere.
Now its use has shifted, moving the raw statuses away from a hash allows us to make the public methods a little clearer by calling the attribute on the Status struct.
I also switched the in_progress/paused clauses around which:
* allowed me to remove the `false` check, so only `true` returns `in_progress` and anything else (including `nil`) returns `paused` - meaning we can get rid of the `|| false`
* line up the `trs_induction_status` values nicely

Remove unused methods from `Teachers::InductionStatus`

---

config/queue.yml

This PR brings back single-threaded process queues for the migrations.

Fix queues

---

app/views/migration/parity_checks/requests/_response_body_ids_diff.html.erb
app/views/migration/parity_checks/responses/_body_ids_diff.html.erb
spec/features/migration/view_parity_check_request_spec.rb
spec/features/migration/view_parity_check_response_spec.rb

Currently we are showing only ecf diff ids, we need to show the RECT ids in green. Also playwrite specs weren't rendering correctly for list/span components
- In both response/request views show the RECT id diff
- Fix rendering the ids in the diff span as those weren't rendering correctly in playwrite

Fix parity check ids to show both rect and ecf diffs

---

db/seeds/lead_provider_delivery_partnerships.rb

We are finding that only a couple of lead providers have delivery partners, and of those there is only one per lead provider. It makes testing easier when there are multiple delivery partners and at least one per lead provider/contract period pairing.
- Add more delivery partnerships for review seed data
Add more delivery partnerships for each lead provider; between 1 and 3 per contract period.
Example seed output:
```
🪴 planting db/seeds/lead_provider_delivery_partnerships.rb
🌱 Artisan Education Group are working with Ambition Institute in 2021
🌱 Artisan Education Group are working with Ambition Institute in 2022
🌱 Artisan Education Group are working with Ambition Institute in 2023
🌱 Artisan Education Group are working with Ambition Institute in 2024
🌱 Artisan Education Group are working …
```

Add more delivery partnerships for review seed data

---

public/api/docs/v3/swagger.yaml
spec/requests/api/docs/v3/partnerships_spec.rb

Ticket: https://github.com/DFE-Digital/register-ects-project-board/issues/2479
An error is displayed when `POST /api/v3/partnerships` endpoint is section is opened.
```
Resolver error at paths./api/v3/partnerships.post.requestBody.content.application/json.schema.$ref
Could not resolve reference: Could not resolve pointer: /components/schemas/PartnershipRequest does not exist in document
```
- Fix POST partnership endpoint swagger docs bug.
[Review app](https://cpd-ec2-review-1409-web.test.teacherservices.cloud/api/docs/v3#/Partnerships/post_api_v3_partnerships)

[2479] Fix POST partnership endpoint swagger docs bug

---

app/services/appropriate_bodies/record_outcome.rb
spec/factories/induction_period_factory.rb
spec/services/appropriate_bodies/record_outcome_spec.rb

@cpjmcquillan spotted this validation failure which is caused by old records having no `training_programme` when they come to be closed by the AB.
https://dfe-teacher-services.sentry.io/issues/6900212741/?environment=production&project=4508369974788096&query=is%3Aunresolved&referrer=issue-stream
Insert new programme type when recording an outcome.

Fix AppropriateBodies::RecordOutcome for old induction period programme types

---

spec/requests/admin/batches_spec.rb
spec/requests/admin/teachers/record_failed_outcome_spec.rb
spec/requests/admin/teachers/record_passed_outcome_spec.rb
spec/requests/appropriate_bodies/claim_an_ect/check_ect_spec.rb
spec/requests/appropriate_bodies/claim_an_ect/find_ect_spec.rb
spec/requests/appropriate_bodies/claim_an_ect/register_ect_spec.rb
spec/requests/appropriate_bodies/process_batch/actions/index_spec.rb
spec/requests/appropriate_bodies/process_batch/actions/show_spec.rb
spec/requests/appropriate_bodies/process_batch/claims/index_spec.rb
spec/requests/appropriate_bodies/process_batch/claims/show_spec.rb
spec/requests/appropriate_bodies/teachers/extensions/index_spec.rb
spec/requests/appropriate_bodies/teachers/index_spec.rb
spec/requests/appropriate_bodies/teachers/record_failed_outcome_spec.rb
spec/requests/appropriate_bodies/teachers/record_passed_outcome_spec.rb
spec/requests/appropriate_bodies/teachers/release_ect_spec.rb
spec/requests/appropriate_bodies/teachers/show_spec.rb
spec/requests/schools/mentorships_spec.rb

A little housekeeping. 
Use the `expect(response).to redirect_to(path)` matcher consistently in specs and remove any redundant `expect(response).to be_redirection` matchers

Use the combined redirection and destination matcher

---

app/controllers/schools_controller.rb
app/services/schools/latest_registration_choices.rb
app/views/schools/register_ect_wizard/_use_previous_ect_choices.html.erb
app/wizards/schools/decorated_school.rb
spec/services/schools/latest_registration_choices_spec.rb
spec/views/schools/register_ect_wizard/shared_examples/use_previous_ect_choices_view.rb
spec/wizards/schools/decorated_school_spec.rb

This branch attempts to make the ECT previous choices page simpler and ensures the previous choice information is accurate.
It does this by using the `Schools::LatestRegistrationChoices` service (DFE-Digital/register-early-career-teachers-public#856). Because this is very much a school level thing, rather than pulling it via the wizard's `ECT` class I added a new `DecoratedSchool` instance variable which has a couple of school-specific methods.
I think this is a sensible first move when it comes to simplifying the `ECT` class.
Fixes #1393, DFE-Digital/register-ects-project-board#2309

Rework previous choices page

---

spec/jobs/refresh_metadata_job_spec.rb

We get a flakey test that compares the array to an active record relation, adding the `a_collection_containing_exactly` ensures we always compare both collections instead.
Compare schools using `a_collection_containing_exactly` to avoid comparing an array to a relation
failure reported by @leandroalemao here https://github.com/DFE-Digital/register-early-career-teachers-public/actions/runs/18033991795/job/51316626282

Fix flakey test by comparing the collection

---

app/models/teacher.rb
spec/models/teacher_spec.rb

We need to be able to get the earliest ECT/mentor at school period so that we can surface the `created_at` date in the participants API endpoint response. This is mapped from the `ParticipantProfile` (`ECT`/`Mentor`) in ECF.
- Add `has_one` relationships for earliest ECT/mentor at school period

Add `has_one` relationships for earliest ECT/mentor at school period

---

lib/schools/validation/ect_start_date.rb
spec/lib/schools/validation/ect_start_date_spec.rb

2494. Update error message to remove reference to 'registration periods'.
The message currently uses the term '2 registration periods'. We think this is language that won't be fully understood by our users.
Update error message for past start dates to remove reference to 'registration periods'.

Update error message for past start dates

---

spec/services/schools/register_ect_spec.rb

This spec was failing on main because no `ContractPeriod` existed for the current year. This caused `TrainingPeriodSources` to raise `ActiveRecord::RecordNotFound`.
```
Failures:
1) Schools::RegisterECT#register! when provider led when provider-led when a Teacher record with the same TRN has a future period at different school allows registration with non-overlapping future date
Failure/Error: @active_lead_provider ||= ActiveLeadProvider.find_by!(lead_provider:, contract_period:)
ActiveRecord::RecordNotFound:
Couldn't find ActiveLeadProvider with [WHERE "active_lead_providers"."lead_provider_id" = $1 AND "active_lead_providers"."contract_period_year" IS NULL]
Finished in 2.03 seconds (files took 5.31 seconds to load)
20 examples, 1 failure
Failed examples:
rspec …
```

Fix failing `RegisterECT` spec on main

---

app/services/schools/register_mentor.rb
spec/services/schools/register_mentor_spec.rb

It should not be possible to reach the point of creating a `TrainingPeriod` for an ineligible mentor. However, we have added an explicit safeguard to ensure this cannot happen.
- Prevent creation of a `TrainingPeriod` for ineligible mentors.
- Raise a `MentorIneligibleForTraining` error instead of returning silently,  so that if the flow ever does reach this point it is caught explicitly.
- Added service spec coverage using the `:ineligible_for_mentor_funding` factory trait.
🚢

[2393] Prevent `TrainingPeriod` creation for ineligible mentors

---

app/helpers/programme_helper.rb

Updating content for Induction programme type from 'Training programme is not recognised' to 'Pre-2021 induction'.

Update default training programme name 

---

app/models/induction_period.rb
app/services/appropriate_bodies/record_outcome.rb
spec/factories/induction_period_factory.rb
spec/models/induction_period_spec.rb
spec/services/appropriate_bodies/record_outcome_spec.rb

Legacy `induction_programme` types of `unknown` and `pre_september_2021` cannot automatically be mapped to the new `training_programme` types.
We have decided that rather than have the AB edit the period and choose `school_led` or `provider_led` we will allow `nil` values.
Closes https://github.com.mcas.ms/DFE-Digital/register-ects-project-board/issues/2531
Related to https://github.com/DFE-Digital/register-early-career-teachers-public/pull/1458
- Make validation conditional
- Update factory traits and specs

Change Induction Period validation for training programme to be conditional

---

app/migration/migrators/base.rb
app/migration/migrators/gias_import.rb
app/migration/migrators/school.rb
app/services/gias/importer.rb
spec/factories/migration/csv_school_row_factory.rb
spec/migration/legacy_data_importer_spec.rb
spec/migration/migrators/gias_import_spec.rb
spec/support/shared_examples/migrator_support.rb

[Issue](https://github.com/DFE-Digital/register-ects-project-board/issues/2242)
The Reset all migration data action on the migration page causes migration failures and inconsistent migration behavior across runs.
Migration failures:
Migrations expect School records to already exist, but resetting migration data removes these School records, causing subsequent runs to fail. The root cause is that the LeadProvider migrator uses TRUNCATE CASCADE to clear the lead_providers table. Because the schools table has a [foreign key](https://github.com/DFE-Digital/register-early-career-teachers-public/blob/5eaef55ead63b93c6c95ea8e9b6db80f9eae353e/db/schema.rb#L802) to lead_providers, PostgreSQL automatically truncates the schools table as well.
Inconsistent migrator behavior:
The first migration run …

[2242] - school migrator fails after migration data reset

---

app/components/test_guidance_component.rb
app/services/appropriate_bodies/process_batch/claim.rb
spec/fixtures/seeds_claim.csv

Bulk errors didn't match the manual journey, if an ECT was passed and also prohibited, the `already passed` error was shown.
Reorder the validations and annotate the prohibited test teachers.
Bulk claim using seed fixtures

Fix bulk claims validations so prohibited comes before passed

---

config/environments/test.rb

We use the test guidance functionality to help with manual testing by providing users with clues on how to fill in certain fields.
We never want this when running the automated tests as it can trigger false positives - especially now as it controls the session debug info in the footer. i.e. some tests were failing locally because '2025' was expected on the page and also appeared in the session info.

Disable test guidance in the test env

---

spec/models/training_period_spec.rb

We have a few instances of these specs failing because the sequence in the training period factory appears to push the start date beyond the finish date.
```
ActiveRecord::StatementInvalid:
PG::DataException: ERROR:··range lower bound must be less than or equal to range upper bound
```
In the longer term I think we ought to stop using the base dates (or restrict them to traits) and hardcode them where possible, as in the long run it'll be more robust (at the expense of being a bit more verbose).

Fix a failing spec by hardcoding the period dates

---

app/serializers/api/teacher_serializer.rb
spec/serializers/api/teacher_serializer_spec.rb

We want to add the skeleton for the `TeacherSerializer` so that we can press on with the rest of the participant endpoint.
- Add the `TeacherSerializer` for the participants endpoint.
Include TODO: comments for fields that we can't implement yet.
It looks like there is validation on `Teacher#trn` that prevents invalid TRNs (they must be numerical and have a length of 5) so I haven't addressed the point in the ticket around returning `nil` for invalid TRNs.
The `schedule` also doesn't exist on a `TrainingPeriod` yet, so we can't populate the schedule identifier as detailed in the ticiket.

Add `TeacherSerializer`

---

app/migration/builders/ect/school_periods.rb
app/migration/migrators/ect_at_school_period.rb
spec/migration/builders/ect/school_periods_spec.rb

[Ticket](https://github.com/DFE-Digital/register-ects-project-board/issues/2198)
When we migrate a ParticipantProfile::ECT record we store the ECF ID on the Teacher record in the attribute ecf_ect_profile_id. We also need to store the ParticipantProfile.created_at attribute in RECT alongside this.
We should store the ParticipantProfile::ECT.created_at timestamp in the earliest/first ECTAtSchoolPeriod.created_at
Updates the Migrators::ECTAtSchoolPeriod to store the ParticipantProfile::ECT.created_at in the first ECTAtSchoolPeriod.created_at.

[2198] - set first school_period created_at time to that of its participant profile migrated from ECF1

---

app/services/api/teachers/query.rb
spec/factories/teacher_id_change_factory.rb
spec/services/api/teachers/query_spec.rb

We are adding the `Teachers::Query` service to allow us to query teachers according to the API specification.
- Make api_from_teacher_id optionally set
If we want to specify our own `api_from_teacher_id` to avoid extra creations (which throws off our tests of the `Teachers::Query`, for example) its useful to be able to pass in the `api_from_teacher_id`.
- Add Teachers::Query
Note that we have to `eager_load` instead of `includes` when preloading the associations in order to be able to filter out the metadata not associated with the given lead provider. As `eager_load` can be a little less efficient that `includes` (it creates a single, bloated query and the results are paired back in memory) we may want to drop the metadata filtering and `includes` instead if we find performance is an …

Add `Teachers::Query` service

---

db/seeds/statements.rb

Ticket: https://github.com/DFE-Digital/register-ects-project-board/issues/2515
* Set deadline date to be the last day of the previous month
* Set payment date to be the 25th of the month
* Set output fee statements for January, April, August and October.
* Set status to `paid` only if output fee, otherwise `payable`.

[2515] Make statement seed more realistic and similar to ecf1

---

app/models/teacher.rb
db/migrate/20251008144737_remove_autogeneration_from_api_training_record_ids.rb
db/schema.rb
spec/factories/ect_at_school_period_factory.rb
spec/factories/mentor_at_school_period_factory.rb
spec/models/teacher_spec.rb

This is causing issues in participant profile migration, we should not set automatically and only set when a teacher is registered as an ect or mentor
- Remove autogeneration on those fields for teacher
- Set in factories for ect or mentor
Setting those values explicitly in the services will happen in a followup pr this is just to unblock migration

Remove autogeneration from training records
